packages/zent-datetimepicker/src/DatePicker.js, packages/zent-datetimepicker/src/utils/format.js
=> Fix format bug

packages/zent-table/assets/index.scss, packages/zent-table/examples/simple.js, packages/zent-table/src/helper.js, packages/zent-table/src/modules/Head.js, packages/zent-table/src/modules/Td.js
=> flex-style-table

.eslintignore, packages/zent-datetimepicker/examples/simple.js, packages/zent-datetimepicker/src/DatePicker.js, packages/zent-datetimepicker/src/DateRangePicker.js, packages/zent-datetimepicker/src/MonthPicker.js, packages/zent-datetimepicker/src/TimePicker.js, packages/zent-datetimepicker/src/utils/format.js
return the same type value as user passed in.
=> Fix value return

packages/zent-datetimepicker/assets/index.scss, packages/zent-datetimepicker/src/DateRangePicker.js
=> Fix year panel display

packages/zent-pop/README.md, packages/zent-pop/__tests__/index.js, packages/zent-pop/assets/_zent-pop.scss, packages/zent-pop/examples/02-position.js, packages/zent-pop/package.json, packages/zent-pop/scripts/validate-pop-size.sh, packages/zent-pop/src/Pop.js, packages/zent-pop/src/position.js, packages/zent-popover/__tests__/index.js, packages/zent-popover/assets/01-simple.scss, packages/zent-popover/examples/01-simple.js, packages/zent-popover/examples/02-dialog.js, packages/zent-popover/src/Content.js, packages/zent-popover/src/trigger/ClickTrigger.js, packages/zent-popover/src/trigger/HoverTrigger.js, packages/zent/scripts/prepublish.sh, scripts/publish.sh
Add support for aligning pop content relative to its arrow, and arrow is always aligned to the center of trigger.
=> Pop arrow at center

packages/zent-tabs/README.md, packages/zent-tabs/examples/basic.js, packages/zent-tabs/src/components/TabPanel/TabPanel.js
=> feat: zent-tabs空间支持tab传react组件

scripts/npm-sync.sh
=> npm_sync shell

packages/zent-pop/README.md, packages/zent-pop/__tests__/index.js, packages/zent-pop/examples/04-confirm.js, packages/zent-pop/examples/05-controlled.js, packages/zent-pop/src/NoneTrigger.js, packages/zent-pop/src/Pop.js, packages/zent-popover/README.md, packages/zent-popover/__tests__/index.js, packages/zent-popover/examples/03-controlled.js, packages/zent-popover/src/Content.js, packages/zent-popover/src/Popover.js, packages/zent-popover/src/trigger/ClickTrigger.js, packages/zent-popover/src/trigger/HoverTrigger.js
1. onConfirm, onCancel支持异步
2. 支持外部通过visible和onVisibleChange控制显示隐藏
1. 支持外部通过visible和onVisibleChange控制显示隐藏
2. onBeforeShow, onBeforeClose支持异步
=> Refactor pop

packages/zent-breadcrumb/README.md
=> 文档更新-zent-breadcrumb

packages/zent-button/README.md
=> 文档更新-zent-button

packages/zent-checkbox/README.md
=> 文档更新-zent-checkbox

packages/zent-datetimepicker/README.md
=> 文档更新-zent-datetimepicker

packages/zent-icon/README.md
=> 文档更新: zent-icon

packages/zent-dialog/README.md
=> 文档更新: zent-dialog

packages/zent-input/README.md
=> 文档更新: zent-input

packages/zent-loading/README.md
=> 文档更新: zent-loading

packages/zent-pagination/README.md
=> 文档更新: zent-pagination

packages/zent-button/examples/2-link.js, packages/zent-button/src/Button.js
o_O||
https://github.com/youzan/zent/issues/15
=> Fix issues#15

packages/zent-portal/README.md
=> 文档更新: zent-portal

packages/zent-radio/README.md
=> 文档更新: zent-radio

packages/zent-notify/README.md
=> 文档更新: zent-notify

packages/zent-switch/README.md
=> 文档更新: zent-switch

packages/zent-sweetalert/README.md
=> 文档更新: zent-sweet

packages/zent-popover/README.md
=> 文档更新: zent-popover

packages/zent-utils/README.md
=> 文档更新: zent-utils

packages/zent-tree/README.md
_(:з」∠)_
这个组件文档本身的质量不是太好. 
先别合, 我等下改一下.
=> 文档更新: zent-tree

packages/zent-tabs/README.md
=> 文档更新: zent-tabs

packages/zent-table/README.md
=> 文档更新: zent-table

packages/zent-form/README.md
=> form 文档的一点微调

packages/zent-checkbox/assets/index.scss, packages/zent-radio/assets/index.scss
=> 在不可用状态下，讲整个区域的数标都置成not-allowed

packages/zent-tree/assets/_zent-tree.scss, packages/zent-tree/examples/CustomOperationNodeTree.js, packages/zent-tree/package.json
1. disableCheck节点内容改为灰色
2. disableCheck节点选择框cursor改为not-allowed
3. 节点hover样式去掉border
4. check样式优化
5. CustomOperation🌰 增加深拷贝浅拷贝选项
=> feat: 优化tree组建案例，优化样式

packages/zent-tabs/assets/index.scss, packages/zent-tabs/src/components/Nav/Nav.js
=> style: 支持新ui

packages/zent-pagination/src/data/parser.js
=> fix pagination分页

packages/zent-pop/README.md, packages/zent-portal/README.md
=> Lc doc portal

packages/zent-pop/README.md
=> doc: update pop doc

packages/zent-datetimepicker/__tests__/utils.js
=> remove utc test

packages/zent-button/__tests__/Button.js, packages/zent-button/src/Button.js
=> fix: allow addional attributes in link Button

packages/zent-dialog/assets/zent-dialog.scss
=> fix: center dialog with a ghost inline-block element

packages/zent-popover/__tests__/index.js, packages/zent-popover/src/trigger/HoverTrigger.js
=> feat: close popover on window blur

packages/zent-select/src/Select.js
- 修复select会自动弹出的问题，改为设置了open参数才会弹出
=> 修复select弹出问题

packages/zent-table/assets/index.scss
=> fix table 样式

packages/zent-datetimepicker/README.md, packages/zent-datetimepicker/src/DatePicker.js, packages/zent-datetimepicker/src/DateRangePicker.js
- Datepicker 移除自动添加 time format 的逻辑
- Datepicker 添加 valueType 的示例
=> Datepicker: 移除自动添加时间 format 逻辑，使用者自己传入完整的 format。 

packages/zent-notify/README.md, packages/zent-notify/src/Notify.js
=> notify: change notify default duration to 2s

packages/zent-dialog/README.md, packages/zent-dialog/__tests__/Dialog.js, packages/zent-dialog/__tests__/open.js, packages/zent-dialog/src/index.js, packages/zent-dialog/src/open.js
Add `Dialog.closeDialog`, deprecate using `openDialog`'s return value to close dialog.
=> Dialog: Add closeDialog static method in Dialog.

packages/zent-table/assets/index.scss, packages/zent-table/src/helper.js, packages/zent-table/src/modules/Head.js, packages/zent-table/src/modules/Td.js
- fix table text algin (use justify-content replace text-align)
=> fix table text align

packages/zent-popover/README.md, packages/zent-popover/__tests__/index.js, packages/zent-popover/src/trigger/ClickTrigger.js
Fixed Click trigger's isOutside hook.
=> popover: isOutside on click trigger now works as expected

packages/zent-table/assets/index.scss
=> table border && background

README-en_US.md
=> doc: add English README

packages/zent-popover/README.md, packages/zent-popover/__tests__/index.js, packages/zent-popover/examples/01-simple.js, packages/zent-popover/src/Popover.js, packages/zent-popover/src/trigger/ClickTrigger.js, packages/zent-popover/src/trigger/HoverTrigger.js, packages/zent-popover/src/trigger/Trigger.js, packages/zent-popover/src/withPopover.js
Implements stacking of Popovers.
Fixes #149
=> popover: support stacked popovers

packages/zent-popover/__tests__/index.js, packages/zent-popover/assets/01-simple.scss, packages/zent-popover/examples/01-simple.js, packages/zent-popover/src/placement/auto-bottom-center.js, packages/zent-popover/src/placement/auto-bottom-left.js, packages/zent-popover/src/placement/auto-bottom-right.js, packages/zent-popover/src/placement/auto-top-center.js, packages/zent-popover/src/placement/auto-top-left.js, packages/zent-popover/src/placement/auto-top-right.js, packages/zent-popover/src/placement/index.js
Add AutoBottomRight, AutoBottomCenter, AutoTopLeft, AutoTopRight, AutoTopCenter.
Fixes #156
=> popover: support more auto postions

packages/zent-icon/assets/index.scss, packages/zent-icon/examples/02-react.js
```scss
@import '../node_modules/a/lib/index.css';
// to
@import 'a/lib/index.css';
```
=> icon: fix relative style import from node_modules

packages/zent-popover/Dropdown.md, site/src/nav.config.js
=> doc: Add Dropdown doc

packages/zent-input/assets/zent-input.scss, packages/zent-input/examples/01-simple.js, packages/zent-input/examples/05-textarea.js
Fixes #190 .
- 修复input/textarea disabled样式 #190
- 去掉ipad/iphone下的默认样式
=> zent-input: disabled字体色调整个及去除浏览器默认样式

.eslintrc, package.json, packages/zent/__tests__/loading.js, packages/zent/__tests__/popover.js, packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/MonthPicker.js, scripts/run-tests.sh, yarn.lock
Use `prettier` from CLI instead of a eslint plugin. The eslint plugin approach is not consistent with `prettier`.
Add `prepush` hook to run all tests.
=> style: run prettier on all files

packages/zent/assets/table.scss, packages/zent/src/table/README.md, packages/zent/src/table/Table.js
- fix hover style
- add third params to onSelection callback
=> table: 修改hover样式，onSelection增加一个新的参数，让用户可以做到单选功能

packages/zent/__tests__/utils/WindowEventHandler.js, packages/zent/__tests__/utils/WindowResizeHandler.js, packages/zent/__tests__/utils/findPositionedParent.js, packages/zent/__tests__/utils/getViewportSize.js, packages/zent/__tests__/utils/isBrower.js, packages/zent/__tests__/utils/isPromise.js, packages/zent/src/utils/dom/findPositionedParent.js
Add unit tests for utils.
Fixes #214
=> test: add tests for utils

.circleci/config.yml, .travis.yml, README-en_US.md, README.md, package.json, packages/zent/__tests__/select.js, packages/zent/package.json, packages/zent/scripts/test.sh, packages/zent/src/datetimepicker/utils/clickOutside.js, packages/zent/src/select/Select.js, packages/zent/src/table/Table.js, packages/zent/yarn.lock, scripts/check-git-hooks.sh, yarn.lock
这个脚本在CI上确保所有人都正确安装了git hooks.
很多人在本地不跑hook的，导致代码有问题。
=> Add script to check git hooks

packages/zent/assets/switch/_zent-switch.scss
=> switch: 修改 switch 样式

packages/zent/assets/datetimepicker.scss
- Datepicker: 确认按钮添加 hover cursor 样式
=> Datepicker: add confirm button cursor

packages/zent/__tests__/notify.js, packages/zent/__tests__/pagination.js, packages/zent/__tests__/pop.js, packages/zent/__tests__/table/helper.js, packages/zent/__tests__/tree.js, packages/zent/jest.config.json, packages/zent/scripts/test.sh, packages/zent/src/dialog/DialogEl.js, packages/zent/src/dialog/open.js, packages/zent/src/utils/dom/focusWithoutScroll.js, packages/zent/src/utils/dom/getScollPosition.js
1. Focus to dialog when open. Fixes #243 .
2. Updated tests.
=> dialog: Focus to dialog when open

packages/zent/__tests__/notify.js, packages/zent/src/notify/Notify.js, packages/zent/src/notify/README.md
fix bug: (Notify) callback is not called when clear notify.
=> Notify: callback is not called when clear notify.

packages/zent/__tests__/loading.js, packages/zent/__tests__/popover.js
Add tests for layout related codes.
=> test: Add tests for layout related code path

packages/zent/assets/datetimepicker.pcss, packages/zent/src/datetimepicker/DateRangePicker.js, packages/zent/src/datetimepicker/README.md
=> datepicker: fix_rangepicer_clear_bug

packages/zent/assets/badge.pcss, packages/zent/src/badge/README.md
Fixes #254 
- modify style of dot in badge
- modify readme of badge
=> fix: fix style and doc of badge

.gitignore, packages/zent/__tests__/popover.js, packages/zent/src/popover/Popover.js
Prevent setState call if Popover is unmounted.
=> popover: Prevent setState call if Popover is unmounted

packages/zent/__tests__/datetimepicker/utils.js, packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/DateRangePicker.js, packages/zent/src/datetimepicker/MonthPicker.js, packages/zent/src/datetimepicker/README.md, packages/zent/src/datetimepicker/date/DatePanelBody.js, packages/zent/src/datetimepicker/utils/date.js
1. 日期选择面板默认的时间值为 '00:00:00';
2. 添加 presetTime api 支持设置日期默认的时间值。
=> datetimepicker: add presetTime api

packages/zent/__tests__/number-input.js, packages/zent/src/number-input/NumberInput.js, packages/zent/src/number-input/README.md
##修复value抛出问题，和对于支持动态改变min和max的功能
1.在外部value改变的时候，内部计算抛出新value值
2.支持min和max动态改变后，输出value值的变化
=> NumberInput: 修复props更新组件不刷新的问题

packages/zent/.babelrc, packages/zent/package.json, packages/zent/yarn.lock
A small performance optimization(possibly).
Implements #298
=> Add transform-react-constant-elements

packages/babel-plugin-zent/package.json, packages/babel-plugin-zent/yarn.lock, packages/zent/package.json, packages/zent/yarn.lock, site/yarn.lock
Upgrade dev packages.
Fixes #272
=> Upgrade packages

packages/zent/package.json, packages/zent/scripts/make-icon-grid.js, packages/zent/src/icon/README.md, packages/zent/yarn.lock
=> Add right-circle icon

packages/zent/__tests__/form/CreatForm-Field.js, packages/zent/src/form/Field.js, packages/zent/src/form/README.md
Field默认把value设置为空字符串 
更新文档中的按钮为zent-button
=> Field默认value设置为空字符串 & 更新文档中的按钮为zent-button

packages/zent/src/datetimepicker/DateRangePicker.js, site/yarn.lock
=> 修复range 的值显示不正确

packages/zent/assets/dialog.pcss, packages/zent/src/copy-button/CopyToClipboard.js, site/src/components/PageHeader/style.pcss
=> Enlarge dialog close button area

packages/zent/src/number-input/NumberInput.js
问题：只对外部传value做重新render，减少render次数，存在问题
1.componentWillReceiveProps的生命周期里，props浅比较后有不同，重新render。
=> numberinput: differ improve

packages/zent/src/select/Popup.js, packages/zent/src/select/Select.js, packages/zent/src/select/triggers/InputTrigger.js
- 修复Option变化的时候，Select的下拉菜单数据没有更新的bug 
Fixes #313
=> 修复Option变化的时候，Select的下拉菜单数据没有更新的bug

packages/zent/assets/cascader.pcss, packages/zent/assets/index.pcss, packages/zent/src/cascader/Cascader.js, packages/zent/src/cascader/README.md, packages/zent/src/cascader/index.js, packages/zent/src/index.js, site/src/nav.config.js
=> 新增级联组件cascader

packages/zent/__tests__/table/combine.js, packages/zent/__tests__/table/helper.js, packages/zent/assets/table.pcss, packages/zent/src/table/README.md, packages/zent/src/table/Table.js, packages/zent/src/table/helper.js, packages/zent/src/table/modules/Body.js, packages/zent/src/table/modules/Foot.js, packages/zent/src/table/modules/Head.js, packages/zent/src/table/modules/Td.js
- add radio select feature
- fix style bug
=> table: support radio box in single selection mode

package.json, packages/zent/__tests__/number-input.js, packages/zent/src/number-input/NumberInput.js, packages/zent/src/number-input/README.md, yarn.lock
修复：this.change.bind(this)与()=>{this.change}方法在用法上，关于前者生成多引用问题
导致在componentWill生命周期里出现死循环问题
=> 修复关于change事件用bind方式造成的多引用问题

packages/zent/src/swiper/Swiper.js, packages/zent/src/swiper/SwiperDots.js
=> fix: Swiper typo

packages/zent/src/select/Select.js
Fixes #333 
- 修复onChange里面调了setState组件重新render以后不能正确显示选中项的问题
=> 修复onChange里面调了setState组件重新render以后不能正确显示选中项的问题

packages/zent/__tests__/search-input.js, packages/zent/assets/index.pcss, packages/zent/assets/search-input.pcss, packages/zent/jest.config.json, packages/zent/src/index.js, packages/zent/src/search-input/README.md, packages/zent/src/search-input/index.js, site/src/nav.config.js
* Implement SearchInput
* tests
* docs
=> Add search-input

packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/DateRangePicker.js, packages/zent/src/datetimepicker/MonthPicker.js, packages/zent/src/datetimepicker/README.md
- 添加 openPanel 属性
- 添加 name 属性
- 修复 datepicker props 不更新bug
=> Datepicker: fix #326

packages/zent/assets/colorpicker.pcss
fix: 按照UI要求，修改 color-picker 样式
=> fix: colorpicker css

package.json, packages/zent/__tests__/table/batch-components.js, packages/zent/__tests__/table/comp/batch-components.js, packages/zent/__tests__/table/helper.js, packages/zent/src/table/Table.js, packages/zent/src/table/helper.js, packages/zent/src/table/modules/Foot.js, packages/zent/src/table/modules/Head.js, yarn.lock
=> remove un use pack

packages/zent/src/colorpicker/PopoverClickTrigger.js, packages/zent/src/colorpicker/index.js
优化：点击button关闭pop调色盘，覆盖Popover.Trigger.Click
=> fix: 点击button 关闭pop

packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/form/createForm.js, packages/zent/src/table/modules/Body.js, packages/zent/src/tree/index.js, site/package.json, site/webpack/vendor-entry.js, site/webpack/webpack.dev.config.js, site/webpack/webpack.prd.config.js, site/yarn.lock
Use lodash/xxx to replace es6 methods.
=> Fix es6 methods

packages/zent/assets/alert.pcss
=> Update alert style

packages/zent/src/table/README.md, packages/zent/src/table/modules/Foot.js, packages/zent/src/table/modules/Head.js, packages/zent/src/table/modules/Td.js
Fixes #367.
- 修正 isMoney设置之后对齐不一致问题
=> 修复pageInfo传null的报错和money class的对齐问题

packages/zent/assets/checkbox.pcss, packages/zent/assets/radio.pcss
- Checkbox组件的input元素添加`cursor: pointer`样式
- Radio组件的input元素添加`cursor: pointer`样式
=> 修复Checkbox和Radio组件的鼠标手势

packages/zent/assets/switch/_zent-switch-status.pcss, packages/zent/src/switch/README.md
small size switch add loading status.
=> switch: small size switch add loading animation

packages/zent/assets/datetimepicker.pcss, packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/DateRangePicker2.js, packages/zent/src/datetimepicker/README.md, packages/zent/src/index.js
=> datepicker: add a new RangePicker

packages/zent/src/select/Popup.js, packages/zent/src/select/README.md
=> select: 修复onEmptySelected的bug

packages/zent/src/table/README.md
=> table: add pageInfo doc

packages/zent/package.json, packages/zent/src/icon/README.md, packages/zent/yarn.lock
* pending-circle
* forbidden-circle
=> icons: Add 2 new icons

packages/zent/src/tabs/index.js
Allow react element in tabs.title
=> tabs: Allow react element in tabs.title

packages/zent/src/table/README.md, packages/zent/src/table/Table.js, packages/zent/src/table/helper.js
Fixes #328
- selection.needCrossPage 控制是否开启跨页多选
=> table: cross page selection

packages/zent/src/table/README.md
`bodyRender`实际上接收任意参数，所以改为`any`
=> 修改table组件的reademe中关于bodyRender的描述

packages/zent/src/number-input/NumberInput.js
Add preventDefault and stopPropagation.
=> numberinput: Add event methods

packages/zent/assets/button/_zent-button.pcss, packages/zent/assets/checkbox.pcss, packages/zent/assets/radio.pcss
Add a transition effect to the following components
- Button
- Checkbox
- Radio
=> Add a transition effect to the following components

packages/zent/__tests__/select.js, packages/zent/src/select/Popup.js, packages/zent/src/select/README.md, packages/zent/src/select/Select.js
=> 为Select组件增加默认选项，调整Popup键盘事件逻辑。

packages/zent/src/number-input/NumberInput.js, packages/zent/src/select/Select.js
- 初始化的时候setState会产生warning，将初始化逻辑移到componentWillMount中
=> select: 去掉warning

packages/zent/src/table/modules/Td.js
table组件bodyRender函数，假如传递进来的props类型是函数，多增加一个name参数
=> table组件bodyRender函数增加参数

packages/zent/__tests__/select.js, packages/zent/assets/select.pcss, packages/zent/src/select/README.md, packages/zent/src/select/Select.js
=> Select: 多选 bug 修复

packages/zent/__tests__/preview-image.js, packages/zent/assets/preview-image.pcss, packages/zent/src/preview-image/Image.js
fix: 补全 preview-image 的className
=> fix: preview-image className

packages/zent/src/date-range-quick-picker/DateRangeQuickPicker.js, packages/zent/src/date-range-quick-picker/README.md, packages/zent/src/date-range-quick-picker/constants.js, packages/zent/src/date-range-quick-picker/helper.js, packages/zent/yarn.lock
1、增加昨日、今日的快速选择支持。
2、增加日期选择限制（min/max Date）。
=> DateRangeQuickPicker: support Today and Yestoday, min/max

packages/zent/__tests__/select.js, packages/zent/assets/select.pcss, packages/zent/assets/sku.pcss, packages/zent/src/select/Popup.js, packages/zent/src/select/Select.js, packages/zent/src/select/triggers/InputTrigger.js, packages/zent/src/sku/SKU.js, packages/zent/src/sku/components/SKUContainer.js, packages/zent/src/sku/components/SKUGroup.js
- 优化键盘控制选中元素滚动到不可见区域的体验
- popup代码简化，删除不需要的逻辑
=> select: 体验优化

packages/zent/assets/design/preview-item.pcss, packages/zent/src/design/Design.js, packages/zent/src/table/README.md
=> design: Add default selection when removing a value

packages/zent/package.json
=> fix typings files

packages/zent/assets/select.pcss, packages/zent/src/select/README.md, packages/zent/src/select/Select.js
- className加到trigger上
- popup上新增加一个popupClassName的配置
- 增加has-error样式
=> select: 修正className，添加popupClassName

packages/zent/assets/select.pcss
=> select: 恢复scrollbar

packages/zent/assets/datetimepicker.pcss, packages/zent/src/datetimepicker/CombineDateRangePicker.js, packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/MonthPicker.js, packages/zent/src/datetimepicker/README.md, packages/zent/src/datetimepicker/WeekPicker.js, packages/zent/src/datetimepicker/constants/index.js, packages/zent/src/datetimepicker/date/DatePanelBody.js, packages/zent/src/index.js
1. add weekpicker
2. add popPosition support
=> datetimepicker: add weekpicker

packages/zent/__tests__/datetimepicker/DatePicker.js, packages/zent/assets/datetimepicker.pcss, packages/zent/src/datetimepicker/CombineDateRangePicker.js, packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/MonthPicker.js, packages/zent/src/datetimepicker/README.md, packages/zent/src/datetimepicker/SplitDateRangePicker.js, packages/zent/src/datetimepicker/WeekPicker.js, packages/zent/src/datetimepicker/constants/index.js, packages/zent/src/datetimepicker/date/DatePanelBody.js, packages/zent/src/datetimepicker/month/MonthPanel.js, packages/zent/src/datetimepicker/month/MonthPanelBody.js
- weekpicker support startDay props 
- monthpicker support max and min
close #423
=> weekpicker support startDay props and monthpicker support max and min

packages/zent/src/datetimepicker/DatePicker.js
=> remove default showTime

packages/zent/src/datetimepicker/CombineDateRangePicker.js, packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/SplitDateRangePicker.js
- update props
- allow falsy value for splitRangePicker
=> update proptypes and allow falsy value

packages/zent/src/datetimepicker/README.md
=> fix readme

packages/zent/assets/form.pcss, packages/zent/src/form/Form.js, packages/zent/src/form/README.md
- form: modify README
- form: add new form layout
=> form: modify README, add new form layout

packages/zent/__tests__/datetimepicker/DatePicker.js, packages/zent/src/date-range-quick-picker/DateRangeQuickPicker.js, packages/zent/src/date-range-quick-picker/README.md, packages/zent/src/date-range-quick-picker/helper.js
Add valueType for date-range-quick-picker , you can choose return value as 'number' or 'string'.
=> datetimepicker: fix date range quick picker add valueType

packages/zent/__tests__/datetimepicker/DatePicker.js
=> datepicker: fix test

packages/zent/src/select/Select.js
=> select: Fix Select proptypes

packages/zent/assets/select.pcss, packages/zent/src/select/README.md
=> [bug fix] Select: 组件占据高度修正

packages/zent/src/tabs/README.md, packages/zent/src/tabs/index.js
=> [bug fix] Tabs: 修复activeId为0时无法选中的问题

packages/zent/assets/table.pcss
=> Fix table clearfix

packages/zent/src/form/Field.js, packages/zent/src/form/README.md, packages/zent/src/form/createForm.js, packages/zent/src/form/handleSubmit.js
Fixes #458 
- 修复validateOnChange和validateOnBlur同设为false时，表单提交时不显示校验的错误。
=> [bug fix] Form: validateOnChange和validateOnBlur同设为false时，表单提交时不显示校验错误问题

packages/zent/assets/select.pcss
1. 宽度样式破坏性修改还原。
2. 修复一些因为之前样式变动引发的bug。
=> [bug fix] Select: 宽度样式修正。

packages/zent/typings/libs/Tabs.d.ts
fix tabs typescript definition
=> [bug fix] Tabs: 修复 typescript 类型

packages/zent/src/table/Table.js
Fixes #456   
- 修复跨页全选没有带之前的选择信息的问题
=> [bug fix] Table: 修复跨页全选的bug

packages/zent/__tests__/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/CombineDateRangePicker.js, packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/MonthPicker.js, packages/zent/src/datetimepicker/README.md, packages/zent/src/datetimepicker/SplitDateRangePicker.js, packages/zent/src/datetimepicker/WeekPicker.js, packages/zent/src/datetimepicker/constants/index.js, packages/zent/src/datetimepicker/utils/index.js, packages/zent/src/select/Popup.js, packages/zent/src/select/README.md
- add onBeforeConfirm and onBeforeClear hooks
- fix select doc bug
- change to interval #453
=> [bug fix] DatePicker：支持 onBeforeConfirm 和 onBeforeClear 钩子

packages/zent/assets/design-line.pcss, packages/zent/assets/design.pcss, packages/zent/assets/design/components/index.pcss, packages/zent/assets/design/components/line/editor.pcss, packages/zent/assets/design/components/line/index.pcss, packages/zent/assets/design/components/line/preview.pcss, packages/zent/assets/design/editor-add-component.pcss, packages/zent/src/design/Design.js, packages/zent/src/design/README.md, packages/zent/src/design/components/line/LineEditor.js, packages/zent/src/design/components/line/LinePreview.js, packages/zent/src/design/components/line/index.js, packages/zent/src/design/editor/DesignEditorAddComponent.js, packages/zent/src/design/index.js, packages/zent/src/design/preview/DesignPreview.js, packages/zent/src/design/utils/InstanceCountMap.js, packages/zent/src/design/utils/component-group.js, packages/zent/src/design/utils/design-type.js
=> [new feature] Design: 支持组件分组展示以及限制组件可添加次数

packages/zent/src/table/README.md, packages/zent/src/table/Table.js, packages/zent/src/table/modules/Head.js
=> [bug fix] Table:  当前页都不可选时全选按钮禁用

packages/zent/src/form/Field.js, packages/zent/src/form/form_components/CheckboxField.js, packages/zent/src/form/form_components/CheckboxGroupField.js, packages/zent/src/form/form_components/InputField.js, packages/zent/src/form/form_components/RadioGroupField.js, packages/zent/src/form/form_components/SelectField.js, packages/zent/src/select/trigger/InputTrigger.js
=> [bug fix] Fix React 16 warnings

packages/zent/src/swiper/README.md
=> [docs] Swiper: 修复doc内示例的warning

packages/zent/typings/libs/DateTimePicker.d.ts
=> [bug fix]: 修复DateRangePicker类型定义

packages/zent/src/tabs/index.js
=> [bug fix]Tabs: 修复Tabs组件activeKey字段兼容问题

packages/zent/src/design/Design.js
Update selected value if value or defaultSelectedIndex changed and Design has no selected value.
=> [bug fix] Design: 修复 defaultSelectedIndex 应用逻辑

packages/zent/__tests__/form/GetControlGroup-Component_Fields.js, packages/zent/src/form/getControlGroup.js, packages/zent/src/form/utils.js
Control - functionial Component移除ref
=> [bug fix]Form: 修复ControlGroup内对Control的ref绑定

packages/zent/assets/design/preview-controller.pcss
design: preview区域右下角 action button 加 padding 样式.
=> [bug fix] design: preview区域右下角 action button 加 padding

packages/zent/__tests__/tree.js, packages/zent/jest.config.json, packages/zent/src/form/FieldArray.js, packages/zent/src/form/Fieldset.js, packages/zent/src/form/README.md, packages/zent/src/form/form_components/ColorPickerField.js, packages/zent/src/form/form_components/DateRangePickerField.js, packages/zent/src/form/form_components/FormComponentField.js, packages/zent/src/form/form_components/NumberInputField.js, packages/zent/src/form/form_components/SwitchField.js, packages/zent/src/grid/Cell.js, packages/zent/src/loading/LoadingInstance.js, packages/zent/src/loading/README.md, packages/zent/src/tree/index.js
- Form refs
- Grid shouldComponentUpdate
- Deprecate `Loading.on` and `Loading.off`, removed from docs
=> [bug fix] Fix React 16 issues

packages/zent/src/table/README.md, packages/zent/src/table/Table.js
=> [bugfix] Table: 修复某种情况下跨页多选的问题

packages/zent/src/design/Design.js, packages/zent/src/design/utils/design-type.js
`defaultType: number | string[] => string`
=> [new feature] Design: Support custom type callback in component

packages/zent/src/popover/Content.js
Add null guard in Popover.
Fixes #528
=> [bug fix] Popover: Add null guard in Popover

packages/zent/src/popover/README_en-US.md, packages/zent/src/portal/README_en-US.md, packages/zent/src/sku/README_en-US.md, packages/zent/src/tree/README_en-US.md, packages/zent/src/tree/demos/arrayData.md, packages/zent/src/tree/demos/basic.md, packages/zent/src/tree/demos/customNode.md, packages/zent/src/tree/demos/customOperate.md, packages/zent/src/tree/demos/option.md, packages/zent/src/tree/demos/size.md
1. Fork [the repository](https://github.com/youzan/zent) and create your branch from `master`.
2. Follow the [contributing guide](../CONTRIBUTING.md) to setup your develop environment.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Describe your pull request.
[bug fix / breaking change / new feature] 组件名字：修改内容描述
说明：
* 前面方括号用来区分 Issue / PR 的 类型：bug fix - 改 bug；breaking change: 不兼容的改动；new feature：新功能
* 修改内容尽可能言简意赅，总结 PR 的改动或者描述 Issue
* 描述请用中文
* 组件名字请用英文，首字母大写
示例：
* [bug fix] Button: 修改颜色
* [breaking change] Loading: 删除  `static` 属性
* [new feature] Form: 增加 `FormSelection` 支持
* [new feature] 新增 Abc 组件
* 默认情况下所有加了 bug / enhancement 这两个 …
=> feat: tree组件demo英文文档支持

packages/zent/src/datetimepicker/DatePicker.js
* [bug fix] Datepicker: 修复时间组件日期时间联动禁用逻辑
=> [bug fix] Datepicker: 修复时间组件日期时间联动禁用逻辑

packages/zent/src/input/README_en-US.md, packages/zent/src/input/demos/focusAndSelect.md
=> [doc] Input: Update Input doc

packages/zent/src/table/README_en-US.md, packages/zent/src/table/README_zh-CN.md
=> [doc] Table: 修改Table组件emptyLabel类型

packages/zent/src/datetimepicker/CombineDateRangePicker.js, packages/zent/src/datetimepicker/MonthPicker.js, packages/zent/src/datetimepicker/TimePicker.js, packages/zent/src/datetimepicker/WeekPicker.js, packages/zent/src/datetimepicker/date/DatePanel.js, packages/zent/src/datetimepicker/demos/basics.md, packages/zent/src/datetimepicker/month/MonthPanel.js, packages/zent/src/datetimepicker/month/MonthPanelBody.js
* [bug fix] Datepicker: 修复月份选择器禁用bug
=> [bug fix] Datepicker: 修复月份选择器禁用bug

packages/zent/assets/input.pcss, packages/zent/src/input/Input.js, packages/zent/src/input/demos/basic.md, packages/zent/src/input/demos/disabled.md, packages/zent/src/number-input/demos/basic.md, packages/zent/src/number-input/demos/disable.md, packages/zent/src/select/Select.js, packages/zent/src/upload/components/FileInput.js, packages/zent/src/upload/components/UploadLocal.js, packages/zent/src/upload/components/UploadPopup.js, packages/zent/src/upload/demos/basic.md, packages/zent/src/utils/createObjectURL.js
- Select data now can be `null` or `undefined`
- Fix disabled style for Input
- Selecting the same image in Upload now works. Fixes #543
=> [bug fix]: Fix bugs

packages/zent/assets/design.pcss, packages/zent/assets/design/editor-add-component.pcss, packages/zent/assets/design/preview-controller.pcss, packages/zent/src/design/Design.js, packages/zent/src/design/README_en-US.md, packages/zent/src/design/README_zh-CN.md, packages/zent/src/design/editor/DesignEditorAddComponent.js, packages/zent/src/design/utils/LazyMap.js, packages/zent/src/upload/components/FileInput.js
1. Support tooltip if a component reaches its limit
2. Update styles
=> [new feature] Design: Add tooltip support in components.

packages/zent/assets/design/editor-add-component.pcss, packages/zent/src/design/demos/basics.md, packages/zent/src/design/editor/DesignEditorAddComponent.js
=> [bug fix] Design: Update styles

packages/zent/assets/design/editor-add-component.pcss, packages/zent/src/design/demos/basics.md, packages/zent/src/design/editor/DesignEditorAddComponent.js
=> [bug fix] Design: Replace button with a in Design, workaround for React mouseleave event bug

packages/zent/assets/card.pcss, packages/zent/assets/cascader.pcss, packages/zent/assets/colorpicker.pcss, packages/zent/assets/datetimepicker.pcss, packages/zent/assets/design.pcss, packages/zent/assets/design/editor-add-component.pcss, packages/zent/assets/design/editor-item.pcss, packages/zent/assets/design/preview-controller.pcss, packages/zent/assets/dialog.pcss, packages/zent/assets/grid.pcss, packages/zent/assets/loading.pcss, packages/zent/assets/pop.pcss, packages/zent/assets/preview-image.pcss, packages/zent/assets/select.pcss, packages/zent/assets/sku.pcss, packages/zent/assets/slider.pcss, packages/zent/assets/switch/_zent-switch-status.pcss, packages/zent/assets/theme/default.pcss, packages/zent/assets/upload.pcss, packages/zent/src/design/Design.js, packages/zent/src/design/preview/DesignPreviewController.js, site/src/index.html, site/src/pages/colors/colors.js, site/src/react-docs.pcss
=> [new feature] Design: 更新组件交互

packages/zent/assets/design/preview-controller.pcss, packages/zent/src/design/preview/DesignPreviewController.js
=> [bug fix] Design: Update style

packages/zent/__tests__/form/CreateForm-Field.js, packages/zent/__tests__/form/CreateForm-FieldArray.js, packages/zent/src/form/Field.js, packages/zent/src/form/FieldArray.js, packages/zent/src/form/createForm.js, packages/zent/src/form/demos/asyncValidate.md, packages/zent/src/form/demos/basic.md, packages/zent/src/form/demos/buildinField.md, packages/zent/src/form/demos/cutomField.md, packages/zent/src/form/demos/fieldArray.md, packages/zent/src/form/demos/fieldset.md, packages/zent/src/form/demos/formSection.md, packages/zent/src/form/demos/layout.md, packages/zent/src/form/demos/multiValue.md, packages/zent/src/form/demos/otherOperation.md, packages/zent/src/form/demos/submit.md, packages/zent/src/form/demos/validate.md, packages/zent/src/form/demos/validateTime.md
Fixes #553 
- 修复fieldArray因删减导致的表单校验报错的问题；
- 修复fieldArray在嵌套使用时，部分域增删时数据不对问题；
- 修复form中英文readme中错误文字；
- 修复setFieldsValue和initialize方法无法设定表单域为0的问题；
- 修复validateOnChange和validateOnBlur同为false时，部分情况下仍然在非提交时报错
=> [bug fix] Form: 修复嵌套fieldArray嵌套在增删时错误，修复fieldArray删减时表单校验报错

packages/zent/assets/design/editor-add-component.pcss, packages/zent/src/design/preview/DesignPreviewController.js
1. Wrong item color in add component popup
2. Do not scroll when selecting component
=> [bug fix] Design: bug fixes

packages/zent/assets/datetimepicker.pcss, packages/zent/src/datetimepicker/YearPicker.js, packages/zent/src/datetimepicker/demos/basics.md, packages/zent/src/datetimepicker/month/MonthPanel.js, packages/zent/src/datetimepicker/utils/date.js, packages/zent/src/datetimepicker/year/YearPanel.js, packages/zent/src/datetimepicker/year/YearPanelBody.js, packages/zent/src/index.js
=> [new feature] datetimepicker：添加年份选择

packages/zent/src/form/createForm.js
- 修复部分field有asyncValidation时，表单提交时出报错问题
=> [bug fix] Form: 修复部分field有异步校验时导致form无法提交的问题

packages/zent/typings/libs/Pop.d.ts
=> [bug fix] Pop: 修复类型定义

packages/zent/assets/design/preview-controller.pcss, packages/zent/src/design/Design.js, packages/zent/src/design/README_en-US.md, packages/zent/src/design/README_zh-CN.md, packages/zent/src/design/preview/DesignPreview.js, packages/zent/src/design/preview/DesignPreviewController.js, packages/zent/src/upload/components/UploadPopup.js
1. Fix add icon cut off
2. Support hide add/delete button
3. Fix image remove in Upload. Fixes #567
=> [bug fix] bug fixes for Upload and Design

packages/zent/assets/number-input.pcss, packages/zent/src/number-input/NumberInput.js, packages/zent/src/number-input/README_en-US.md, packages/zent/src/number-input/README_zh-CN.md, packages/zent/src/number-input/demos/basic.md, packages/zent/src/number-input/demos/decimalPoint.md, packages/zent/src/number-input/demos/disable.md, packages/zent/src/number-input/demos/eventHandler.md, packages/zent/src/number-input/demos/range.md
=> [new feature] NumberInput: 新样式支持

packages/zent/src/upload/Upload.js
=> [bug fix] Upload: 修复audio不能修改accept的bug

packages/zent/src/pagination/modules/Prefix.js
=> [bug fix]Pagination: 增加空格，修改select配置

packages/zent/assets/upload.pcss, packages/zent/src/upload/README_zh-CN.md, packages/zent/src/upload/components/UploadPopup.js, packages/zent/src/upload/demos/basic.md, packages/zent/src/upload/demos/voice.md
=> upload: 语音上传bug修复

packages/zent/src/upload/components/UploadPopup.js
=> upload: 修复accept没获取到的bug

packages/zent/assets/design/preview-controller.pcss, packages/zent/src/design/Design.js, packages/zent/src/design/preview/DesignPreviewController.js, packages/zent/src/sku/demos/flatten.md, packages/zent/src/sku/demos/isSame.md
1. 删除/添加组件时不滚动
2. 优化删除组件时的选中逻辑
3. 优化添加组件按钮样式
=> [bug fix] Design: remove scroll behavior

packages/zent/assets/design/editor-add-component.pcss, packages/zent/assets/design/preview-controller.pcss
=> [bug fix] Design: Fix cursor style

packages/zent/src/upload/utils/file-type/index.js
Replace es6 only functions with lodash alternative
=> [bug fix] Upload: Replace es6 only functions with lodash alternative

packages/zent/__tests__/pop.js, packages/zent/__tests__/popover.js, packages/zent/assets/upload.pcss, packages/zent/src/pop/Pop.js, packages/zent/src/pop/README_en-US.md, packages/zent/src/pop/README_zh-CN.md, packages/zent/src/popover/Popover.js, packages/zent/src/popover/README_en-US.md, packages/zent/src/popover/README_zh-CN.md
Expose adjustPosition in Popover and Pop
=> [bug fix] Expose adjustPosition in Popover and Pop

packages/zent/assets/upload.pcss
=> upload: 样式优化

packages/zent/assets/upload.pcss
- 不加这个样式会被dialog的inline样式覆盖，所以这个样式不能删
=> [bug fix] Upload: 多删了一个样式

packages/zent/assets/button/_zent-button.pcss
=> [bug fix] Button: Update styles

package.json, packages/zent/assets/design.pcss, packages/zent/assets/design/_variable.pcss, packages/zent/assets/design/components/config/preview.pcss, packages/zent/assets/design/editor-add-component.pcss, packages/zent/assets/design/editor-item.pcss, packages/zent/src/design/stripUUID.js, postcss.config.js, yarn.lock
1. Now it's 375px, matches iPhone 6.
2. Fix `calc` not reduced in postcss.
=> [bug fix] Design: new preview width

packages/zent/assets/design.pcss, packages/zent/assets/design/_variable.pcss, packages/zent/assets/design/components/config/preview.pcss, packages/zent/assets/design/editor-add-component.pcss
=> [bug fix] Design: Revert Design preview width

packages/zent/src/upload/components/FileInput.js, packages/zent/src/upload/components/UploadPopup.js, packages/zent/src/upload/demos/basic.md
=> upload: 增加文件过滤

packages/zent/src/upload/components/FileInput.js
=> upload: 修复单文件上传bug

packages/zent/__tests__/menu.js, packages/zent/src/menu/README_en-US.md, packages/zent/src/menu/README_zh-CN.md, packages/zent/src/menu/index.js
Allow custom styles in top level menu.
=> [new feature] Menu: Allow custom styles

packages/zent/assets/design-richtext.pcss, packages/zent/assets/design/components/index.pcss, packages/zent/assets/design/components/richtext/editor.pcss, packages/zent/assets/design/components/richtext/index.pcss, packages/zent/src/design/components/richtext/RichtextEditor.js, packages/zent/src/design/components/richtext/RichtextPreview.js, packages/zent/src/design/components/richtext/editor/index.js, packages/zent/src/design/components/richtext/editor/plugins/Emotion.js, packages/zent/src/design/components/richtext/editor/plugins/Link.js, packages/zent/src/design/components/richtext/editor/plugins/Video.js, packages/zent/src/design/components/richtext/editor/plugins/index.js, packages/zent/src/design/components/richtext/index.js, packages/zent/src/design/demos/basics.md, packages/zent/src/table/demos/batch.md, site/src/docs.pcss
=> [new feature] Design: Add richtext component to Design

packages/zent/src/form/Field.js, packages/zent/src/form/README_en-US.md, packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/SubmissionError.js, packages/zent/src/form/createForm.js, packages/zent/src/form/demos/asyncValidate.md, packages/zent/src/form/demos/buildinField.md, packages/zent/src/form/demos/multiValue.md, packages/zent/src/form/handleSubmit.js
- [bug fix] Form：修复`validationOnChange` 为 `false` 时部分情况下组件重新渲染问题；
- [new feature] Form：支持通过 `options` 配置表单的 `scrollToError`，`onChange`，`onSubmitError`，`onSubmitSuccess`；
- [new feature] Form: `zentForm` 提供 `isFormAsyncValidated`，`validateForm`，`asyncValidateForm`；
=> [bug fix] Form：修复`validationOnChange` 为 `false` 时部分情况下组件重新渲染问题

packages/zent/src/utils/scroll.js
Don't crash on node.js.
Fixes #600
=> [bug fix] Utils: Fix scroll on node.js

packages/zent/src/button/demos/noborder.md
=> [bug fix] Button: Fix no border demo in Button

packages/zent/src/pop/Pop.js, packages/zent/src/pop/README_en-US.md, packages/zent/src/pop/README_zh-CN.md, packages/zent/src/popover/Content.js, packages/zent/src/popover/Popover.js, packages/zent/src/popover/README_en-US.md, packages/zent/src/popover/README_zh-CN.md
* Add onPositionUpdated callback to Popover and Pop
* Update docs
=> [new feature] Popover: Add onPositionUpdated callback to Popover and Pop

packages/zent/src/form/Field.js, packages/zent/src/form/Form.js, packages/zent/src/form/README_en-US.md, packages/zent/src/form/README_zh-CN.md
- [new feature] Form: 支持禁止回车提交表单
=> [new feature] Form: 支持禁止回车提交表单

packages/zent/assets/table.pcss, packages/zent/src/design/components/richtext/editor/plugins/Emotion.js, packages/zent/src/table/Table.js, packages/zent/src/table/demos/batch.md, packages/zent/src/table/demos/selection.md, packages/zent/src/table/modules/Foot.js
- 增加wrapper，为所有传入的批量操作按钮自动增加一个key
- 修复跨页多选个数不对的问题
=> [bug fix] Table: 给batchcomponents自动加个wrapper

packages/zent/assets/upload.pcss, packages/zent/package.json, packages/zent/src/upload/Upload.js, packages/zent/src/upload/components/UploadImageItem.js, packages/zent/src/upload/components/UploadPopup.js, packages/zent/yarn.lock
=> upload: 增加上传文件列表拖拽调整顺序

packages/zent/assets/upload.pcss, packages/zent/src/upload/components/UploadImageItem.js, packages/zent/src/upload/components/UploadLocal.js, packages/zent/src/upload/components/UploadPopup.js, packages/zent/src/upload/demos/basic.md, packages/zent/src/upload/utils/index.js
1. Extract constants
2. Fix demo upload limit
=> [bug fix] Upload: Refactor

packages/zent/src/upload/demos/basic.md, packages/zent/src/upload/demos/voice.md
=> [bug fix] Upload: 修复demo样式问题

packages/zent/assets/design/preview-controller.pcss, packages/zent/src/design/Design.js, packages/zent/src/design/preview/DesignPreview.js, packages/zent/src/design/preview/DesignPreviewController.js
1. Cursor style update
2. Allow custom footer in preview
=> [new feature] Design: Allow custom footer in preview

packages/zent/assets/block-header.pcss, packages/zent/src/block-header/BlockHeader.js
=> [new feature] BlockHeader: 修改pop提示的位置

packages/zent/src/infinite-scroller/InfiniteScroller.js, packages/zent/src/infinite-scroller/README_en-US.md, packages/zent/src/infinite-scroller/README_zh-CN.md
1.修复了Proptypes->propTypes
2.文档增加对于useWindow的描述
=> [bug fix] InfiniteScroller: typo，文档更新

packages/zent/assets/grid.pcss, packages/zent/src/grid/Body.js, packages/zent/src/grid/Grid.js, packages/zent/src/grid/Header.js, packages/zent/src/grid/README_en-US.md, packages/zent/src/grid/README_zh-CN.md, packages/zent/src/grid/demos/scrollX.md, packages/zent/src/grid/demos/scrollXY.md, packages/zent/src/grid/demos/scrollY.md
=> [new feature] Grid: 添加scroll.y

packages/zent/src/swiper/Swiper.js
=> [bug fix]  Swiper:  当只有一个children时隐藏arrows

packages/zent/src/upload/components/UploadPopup.js
=> upload: 变更backend是否存在的判断方式

packages/zent/src/form/validationRules.js
- 修改内置校验规则中 `required` 规则，不允许 `null`
=> [bug fix] Form: 修改内置validation rule中required规则

packages/zent/src/swiper/Swiper.js
Swiper:  Block user interaction during animation
=> [bug fix]  Swiper:  Block user interaction during animation

packages/zent/package.json, packages/zent/src/upload/components/UploadImageItem.js, packages/zent/src/upload/components/UploadPopup.js, packages/zent/src/upload/utils/sortable.js, packages/zent/yarn.lock
=> upload: 更换react-dnd为sortablejs

packages/zent/src/datetimepicker/CombineDateRangePicker.js, packages/zent/src/datetimepicker/MonthPicker.js, packages/zent/src/datetimepicker/SeasonPicker.js, packages/zent/src/datetimepicker/YearPicker.js, packages/zent/src/datetimepicker/common/PanelCell.js, packages/zent/src/datetimepicker/time/TimeCell.js, packages/zent/src/datetimepicker/year/YearPanelBody.js, packages/zent/src/swiper/Swiper.js
fix PropTypes -> propTypes to remove react16 warning
=> [bug fix]: typo PropTypes -> propTypes

packages/zent/src/design/Design.js, packages/zent/src/design/README_en-US.md, packages/zent/src/design/README_zh-CN.md, packages/zent/src/design/components/config/ConfigEditor.js, packages/zent/src/design/demos/basics.md, packages/zent/src/design/editor/DesignEditor.js, packages/zent/src/design/preview/DesignPreview.js, packages/zent/src/design/preview/DesignPreviewController.js, packages/zent/src/design/preview/constants.js, packages/zent/src/i18n/i18n-provider.js, packages/zent/src/i18n/i18n-reciever.js
Support custom settings with `settings` and `onSettingsChange`
=> [new feature] Design: Support custom settings

packages/zent/assets/datetimepicker.pcss
[bug fix] DatePicker: 修复 daterangepicker disabled 样式
=> [bug fix] DatePicker: 修复 daterangepicker disabled 样式

packages/zent/src/select/Select.js
=> Select: tag类型改为按value数组顺序选中标签

packages/zent/src/upload/components/FileInput.js, packages/zent/src/upload/components/UploadPopup.js
=> Upload: 保证按顺序显示添加的图片

packages/zent/src/number-input/NumberInput.js
blur事件抛出的数值是string类型，修复此问题，保证blur和change报出所有数据一致
=> 在form中blur抛出数据与onChange一致

packages/zent/src/design/Design.js, packages/zent/src/design/README_en-US.md, packages/zent/src/design/README_zh-CN.md
Add settings and globalConfig to getInitialValue
=> [new feature] Design: Add settings and globalConfig to getInitialValue

packages/zent/src/swiper/Swiper.js, packages/zent/src/swiper/demos/dynamic-add-child.md
=> [new feature] Swiper: support dynamic items

packages/zent/__tests__/form/ValidationRules.js, packages/zent/src/form/Field.js, packages/zent/src/form/README_en-US.md, packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/createForm.js, packages/zent/src/form/demos/multiValue.md, packages/zent/src/form/demos/validateTime.md, packages/zent/src/form/getControlGroup.js, packages/zent/src/form/handleSubmit.js, packages/zent/src/form/unknownProps.js, packages/zent/src/form/validationRules.js
- [break change] Form: `Field` 添加 `displayError` 属性支持从外部控制错误显示
- [new feature] Form: `Field` 支持 `relatedFields` 属性指定当前表单域校验时需要校验哪些表单域
=> [break change] Form: 修改错误显示逻辑

packages/zent/__tests__/tag.js, packages/zent/assets/notify.pcss, packages/zent/src/notify/NotifyContent.js, packages/zent/src/tag/README_en-US.md, packages/zent/src/tag/README_zh-CN.md, packages/zent/src/tag/Tag.js, packages/zent/src/tag/demos/controlled.md, packages/zent/src/tag/demos/onClose.md, site/src/docs.pcss
1. Support `visible` and `onVisibleChange` in `Tag`
2. Fix `Notify` styles
Fixes #657 #656
=> [bug fix ]Notify and Tag

packages/zent/assets/notify.pcss
=> [bug fix]Notify：调整出场动画

packages/zent/src/datetimepicker/CombineDateRangePicker.js
=>  [bug fix] Datepicker: 修复 CombineDateRangePicker 选中一个日期就 confirm 的bug

packages/zent/src/datetimepicker/month/MonthPanel.js, packages/zent/src/datetimepicker/month/MonthPanelBody.js
- MonthPicker控件，当前月份和选中的月份加上年份判断
=> [bugfix]MonthPicker: 当前月份和选中的月份加上年份判断

packages/zent/assets/button/_zent-button-size.pcss
Large button should have`font-size: 14px`.
=> [bug fix] Button: Fix large button font size

packages/zent/assets/grid.pcss, packages/zent/src/grid/Grid.js, packages/zent/src/grid/Row.js, packages/zent/src/utils/dom/measureScrollbar.js
修复以下bug:
- Safari样式问题
- fix时左右高度不一致问题
- 不插鼠标时样式问题
=> [bug fix] Grid: 修复不插鼠标样式问题

packages/zent/assets/grid.pcss, packages/zent/src/grid/Grid.js, packages/zent/src/upload/README_en-US.md, packages/zent/src/upload/README_zh-CN.md, packages/zent/src/upload/Upload.js, packages/zent/src/upload/components/FileInput.js, packages/zent/src/upload/constants/index.js
1. upload 添加bmp格式
2. 修复grid滚动条遮盖问题
=> [new feature] Upload: 添加bmp格式

packages/zent/assets/notify.pcss
=> [bug fix]Notify: 修复动画后样式回弹

packages/zent/assets/datetimepicker.pcss, packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/DateRangePicker.js, packages/zent/src/datetimepicker/demos/basic.md, packages/zent/src/datetimepicker/demos/show-time.md
- 修复未选择日期直接确认没有考虑最小时间的问题
- 修复 disabled 时样式问题
fix #686
=> [bugfix] DatePicker：修复未选择时间直接确认没有考虑最小时间的问题

packages/zent/src/sortable/Sortable.js
=> [bug fix] Sortable: filter bug修复

packages/zent/src/i18n/en-US.js, packages/zent/src/i18n/zh-CN.js, packages/zent/src/select/Popup.js
之前使用 Reciever 文档时, 引入位置写错了.
简单 fix
=> [bugfix]Select: 修复国际化导致的 emptyText 属性默认值消失的 bug

packages/zent/src/design/editor/DesignEditor.js, packages/zent/src/utils/shallowEqual.js
Design: DesignEditor 去除 PureComponent
=> [bug fix] Design: DesignEditor 去除 PureComponent

packages/zent/assets/menu.pcss, packages/zent/src/menu/README_en-US.md, packages/zent/src/menu/README_zh-CN.md, packages/zent/src/menu/SubMenu.js, packages/zent/src/menu/demos/with-icon.md, packages/zent/typings/libs/Menu.d.ts
=> [new feature] Menu: title中增加icon支持

packages/zent/assets/upload.pcss, packages/zent/src/i18n/en-US.js
=> [bug fix] Upload English doc fix

packages/zent/__tests__/datetimepicker/utils.js, packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/MonthPicker.js, packages/zent/src/datetimepicker/QuarterPicker.js, packages/zent/src/datetimepicker/WeekPicker.js, packages/zent/src/datetimepicker/quarter/QuarterPanelBody.js, packages/zent/src/datetimepicker/utils/index.js
- 挂载一些常用方法到 DatePicker 上
- 使用 date-fns 的一些时间工具方法
- 修复月份和周选择器的大小比较值不准确
=> [bugfix]DatePicker: 挂载一些常用方法到 DatePicker 上

packages/zent/src/upload/components/FileInput.js
=> Upload: 修复可以添加超过maxAmount数量的问题

packages/zent/assets/datetimepicker.pcss, packages/zent/src/datetimepicker/README_en-US.md, packages/zent/src/datetimepicker/README_zh-CN.md, packages/zent/src/datetimepicker/TimePicker.js, packages/zent/src/datetimepicker/TimeRangePicker.js, packages/zent/src/datetimepicker/demos/basic.md, packages/zent/src/datetimepicker/time/HourPanel.js, packages/zent/src/datetimepicker/time/MinutePanel.js, packages/zent/src/datetimepicker/time/SecondPanel.js, packages/zent/src/datetimepicker/time/TimePanel.js, packages/zent/src/i18n/en-US.js, packages/zent/src/i18n/zh-CN.js, packages/zent/src/index.js
- TimePicker组件
- TimeRangePicker组件
=> [new feature] TimePicker: TimePicker and TimeRangePicker

packages/zent/package.json, packages/zent/yarn.lock
=> [bugfix]: DatePicker：添加 date-fns 依赖

packages/zent/jest.config.json, packages/zent/src/form/README_en-US.md, packages/zent/src/form/README_zh-CN.md, packages/zent/src/pop/Pop.js
=> [doc] Update docs

packages/zent/src/datetimepicker/MonthPicker.js, packages/zent/src/datetimepicker/demos/basic.md, packages/zent/src/datetimepicker/month/MonthPanel.js, packages/zent/src/datetimepicker/utils/index.js
=> [bugfix]: MonthPicker: 修复月份选择返回日期不正确的问题

packages/zent/src/collapse/Collapse.js, packages/zent/typings/index.d.ts, packages/zent/typings/libs/Card.d.ts, packages/zent/typings/libs/Cascader.d.ts, packages/zent/typings/libs/Collapse.d.ts, packages/zent/typings/libs/Placeholder.d.ts
* Collapse
* Placeholder
Fixed some bugs in ts definition.
=> Add missing ts definition

packages/zent/src/input/Input.js, packages/zent/src/input/README_en-US.md, packages/zent/src/input/README_zh-CN.md, packages/zent/src/search-input/README_en-US.md, packages/zent/src/search-input/README_zh-CN.md
Useful if you want to tell if `onChange` is from clear button.
=> [new feature] Input: Add fromClearButton to Input onChange event

packages/zent/src/slider/Range.js, packages/zent/typings/index.d.ts, packages/zent/typings/libs/DateTimePicker.d.ts
1. DatePicker添加typing
2. Slider添加Resize事件
=> [bug fix] DatePicker: 添加typeing

packages/zent/src/select/Popup.js
=> Select: 修复可能会导致循环渲染的问题

packages/zent/src/sortable/Sortable.js
Sortable：修复onMove和onEnd与onChange同时传入时的问题
=> fix(Sortable): 修复onMove和onEnd与onChange同时传入时的问题

packages/zent/src/upload/components/FileInput.js
=> Upload: 修复文件类型判断不正确的问题

packages/zent/__tests__/steps.js, packages/zent/assets/steps.pcss, packages/zent/src/steps/README_en-US.md, packages/zent/src/steps/README_zh-CN.md, packages/zent/src/steps/components/NumberSteps.js, packages/zent/src/steps/components/Step.js, packages/zent/src/steps/demos/breadcrumb-step.md, packages/zent/src/steps/demos/card-step.md, packages/zent/src/steps/demos/vertical-step.md
Fixes #414 
- 增加 `direction` 参数， 可选值为 `horizontal` 和 `vertical`
=> [new feature] Steps: 增加竖直方向的样式

packages/zent/assets/checkbox.pcss, packages/zent/assets/radio.pcss, packages/zent/src/grid/Grid.js
1. [bug fix] Grid:修复表头高度不一致
2. [bug fix] Radio: 不可选颜色修改
3. [bug fix] Checkbox: 不可选颜色修改
=> [bug fix] Grid:修复表头高度不一致

packages/zent/package.json
=> Publish 4.2.2

site/src/components/search-box/index.js
=> [bug fix]: 文档网站使用zent的SearchInput组件

packages/zent/assets/tabs.pcss
[bug fix] Tabs：删除css内!important样式
=> [bug fix] Tabs：删除css内!important样式

packages/zent/src/sortable/Sortable.js
=> fix(Sortable): 当不传items传onEnd时的问题修复

packages/zent/assets/_popup-menu.pcss, packages/zent/assets/_popup.pcss, packages/zent/assets/auto-complete.pcss, packages/zent/assets/index.pcss, packages/zent/assets/select.pcss, packages/zent/jest.config.json, packages/zent/package.json, packages/zent/src/auto-complete/AutoComplete.js, packages/zent/src/auto-complete/README_en-US.md, packages/zent/src/auto-complete/README_zh-CN.md, packages/zent/src/auto-complete/demos/advanced.md, packages/zent/src/auto-complete/demos/basic.md, packages/zent/src/auto-complete/demos/controlled.md, packages/zent/src/auto-complete/index.js, packages/zent/src/index.js, packages/zent/src/select/constants.js, packages/zent/src/utils/dom/getDocumentClientSize.js, packages/zent/typings/index.d.ts, packages/zent/typings/libs/AutoComplete.d.ts, packages/zent/yarn.lock
=> [new feature] AutoComplete

packages/zent/assets/select.pcss, packages/zent/src/select/demos/tag.md, packages/zent/src/select/trigger/TagsTrigger.js
=> [bugfix]Select: 统一显示样式.

.circleci/config.yml, packages/zent/src/popover/Content.js
修复极端情况下Popover循环调用adjustPosition
=> [bug fix] Popover: 修复极端情况下Popover循环调用adjustPosition

packages/zent/assets/checkbox.pcss, packages/zent/assets/radio.pcss
- [bug fix] Radio: 修复多级 radio 的样式覆盖问题
- [bug fix] Checkbox: 修复多级 checkbox 的样式覆盖问题
=> [bug fix] Radio: 修复多级 radio 的样式覆盖问题

packages/zent/assets/pagination.pcss, packages/zent/src/pagination/modules/Prefix.js
=> [bug fix] Pagination: 调整pagination显示文案

packages/zent/assets/block-header.pcss
=> [bug fix] BlockHeader: Update block header style

packages/zent/__tests__/steps.js, packages/zent/assets/steps.pcss, packages/zent/src/steps/README_en-US.md, packages/zent/src/steps/README_zh-CN.md, packages/zent/src/steps/Steps.js, packages/zent/src/steps/components/Step.js, packages/zent/src/steps/demos/number-step.md, packages/zent/src/steps/demos/vertical-step.md
- [new feature] Steps: 新增表示当前状态的 process，并且样式按设计要求进行调整
- [breaking change] Steps: 默认状态改为 process
=> [breaking change] Steps: 默认状态改为 process

packages/zent/src/upload/README_en-US.md, packages/zent/src/upload/README_zh-CN.md, packages/zent/src/upload/Upload.js, packages/zent/src/upload/components/FileInput.js, packages/zent/src/upload/demos/basic.md, packages/zent/src/upload/utils/index.js
=> Upload: 增加errorMessages配置

packages/zent/__tests__/cascader.js, packages/zent/jest.config.json
Fixes #513 
- [test] Cascader: ReactWrapper api变更导致的单测不过问题，换种写法解决
=> [test] Cascader: ReactWrapper api变更导致的单测不过问题，换种写法解决

packages/zent/assets/select.pcss
=> Select: 去掉tag的滚动条

packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/DateRangePicker.js, packages/zent/src/datetimepicker/TimePicker.js, packages/zent/src/datetimepicker/YearPicker.js
* [bug fix] datetimepicker: YearPicker max 和 min 支持传入 date 实例
close #776
=> fix(datetimepicker): yearpicker support date value for max and min

packages/zent/assets/block-header.pcss, packages/zent/src/block-header/BlockHeader.js, packages/zent/src/block-header/README_en-US.md, packages/zent/src/block-header/README_zh-CN.md, packages/zent/src/block-header/demos/basic.md, packages/zent/typings/libs/BlockHeader.d.ts
BlockHeader增加childAlign属性，控制子元素位置
=> [new feature]: BlockHeader增加childAlign属性，控制子元素位置

packages/zent/assets/block-header.pcss, packages/zent/src/block-header/demos/basic.md
=> [bug fix] BlockHeader: fix pop style

packages/zent/__tests__/error-boundary.js, packages/zent/assets/error-boundary.pcss, packages/zent/assets/index.pcss, packages/zent/jest.config.json, packages/zent/src/error-boundary/ErrorBoundary.js, packages/zent/src/error-boundary/Fallback.js, packages/zent/src/error-boundary/README_en-US.md, packages/zent/src/error-boundary/README_zh-CN.md, packages/zent/src/error-boundary/demos/basic.md, packages/zent/src/error-boundary/demos/custom.md, packages/zent/src/error-boundary/demos/hoc.md, packages/zent/src/error-boundary/demos/on-error.md, packages/zent/src/error-boundary/index.js, packages/zent/src/error-boundary/withErrorBoundary.js, packages/zent/src/index.js, packages/zent/typings/index.d.ts, packages/zent/typings/libs/ErrorBoundary.d.ts
`ErrorBoundary` and an HOC `withErrorBoundary`
=> [new feature] ErrorBoundary: Add ErrorBoundary component

packages/zent/__tests__/dialog/Dialog.js, packages/zent/__tests__/dialog/open.js, packages/zent/__tests__/pop.js, packages/zent/__tests__/popover.js, packages/zent/__tests__/portal/Portal.js, packages/zent/__tests__/portal/PurePortal.js, packages/zent/__tests__/portal/utils.js, packages/zent/assets/animation/_zoom.pcss, packages/zent/assets/dialog.pcss, packages/zent/src/dialog/Dialog.js, packages/zent/src/dialog/DialogEl.js, packages/zent/src/dialog/demos/basic.md, packages/zent/src/dialog/demos/open.md, packages/zent/src/dialog/open.js, packages/zent/src/internal/animatedClosable.js, packages/zent/src/portal/LayeredPortal.js, packages/zent/src/portal/Portal.js, packages/zent/src/portal/PurePortal.js, packages/zent/src/portal/README_en-US.md, packages/zent/src/portal/README_zh-CN.md, packages/zent/src/portal/demos/basic.md, packages/zent/src/portal/index.js, packages/zent/src/portal/util.js, packages/zent/typings/libs/Portal.d.ts
- The refactor of Portal: more powerful LayeredPortal is provided, as well as PurePortal which replaces all the content inside its container.
- Solve the dialog open & close animation issue.
=> [new feature] Portal/Dialog: PurePortal, LayeredPortal, and Dialog animation

packages/zent/src/dialog/Dialog.js, packages/zent/src/dialog/open.js
- Fix the issue of dialog close animation origin
=> fix: dialog close mouse position issue

packages/zent/src/loading/Loading.js, packages/zent/src/loading/README_en-US.md, packages/zent/src/loading/README_zh-CN.md, packages/zent/src/loading/demos/wrapper-mode.md
=> [bug fix] Loading: Fix height not applied

packages/zent/README_en-US.md, packages/zent/README_zh-CN.md, packages/zent/src/form/demos/buildin-field.md
=> [doc] 更新中英文文档截图

packages/zent/assets/table.pcss, packages/zent/src/table/demos/basic.md, packages/zent/src/table/demos/empty.md, packages/zent/src/table/demos/loading.md, packages/zent/src/table/demos/pager.md, packages/zent/src/table/demos/sort.md
=> [bug fix] Table : 修改cell的样式，防止出现宽度错误的问题

packages/zent/src/dialog/Dialog.js, packages/zent/src/dialog/DialogEl.js, packages/zent/src/dialog/open.js
- fix the issue that closeDialog function do trigger any animation.
=> fix: dialog close with no animation issue.

packages/zent/src/block-header/BlockHeader.js, packages/zent/src/block-header/demos/basic.md
=> [bug fix] BlockHeader: change DOM structure

packages/zent/typings/libs/Avatar.d.ts, packages/zent/typings/libs/Sortable.d.ts, packages/zent/typings/libs/SplitButton.d.ts
- typings/libs/Avatar.d.ts
- typings/libs/Sortable.d.ts
- typings/libs/SplitButton.d.ts
=> [bug fix] Avatar & Sortable & SplitButton：修正Avatar、Sortable和SplitButton组件的TS类型定义文件

packages/zent/typings/index.d.ts, packages/zent/typings/libs/Grid.d.ts
=> [bug fix] Grid: 增加 Grid.d.ts

packages/zent/src/mention/Mention.js, packages/zent/typings/index.d.ts, packages/zent/typings/libs/Mention.d.ts
Add  typescript definition for Mention
=> [new feature] Mention: Add typescript definition for Mention

packages/zent/__tests__/pagination.js, packages/zent/src/pagination/README_en-US.md, packages/zent/src/pagination/README_zh-CN.md, packages/zent/src/pagination/demos/dynamic-page-size.md, packages/zent/src/pagination/index.js, packages/zent/typings/libs/Pagination.d.ts
Add `onPageSizeChange` callback. There was no way to know page size has changed.
=> [bug fix] Pagination: Add onPageSizeChange callback

packages/zent/package.json, packages/zent/src/icon/demos/all.md, packages/zent/yarn.lock
=> [new feature] Icon: Add new icons

packages/zent/src/grid/Grid.js, packages/zent/src/grid/README_en-US.md, packages/zent/src/grid/README_zh-CN.md, packages/zent/src/grid/demos/expand.md, packages/zent/typings/libs/Grid.d.ts
- 修复可扩展模式下表格的datasets变化时点击展开图标没反应的问题
- 新增onExpand属性监听点击展开图标的动作
=>  [bug fix & new feature ]  Grid: fix expandation bug、新增onExpand监听点击展开图标

packages/zent/assets/input.pcss, packages/zent/src/input/demos/event-handler.md
1. 修复 addon 文字没有默认颜色的问题
2. 修复 addon 文字不居中的问题
=> [bug fix] Inout: Fix Input addon style

packages/zent/__tests__/form/CreateForm-FieldArray.js, packages/zent/src/form/FieldArray.js, packages/zent/src/form/README_en-US.md, packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/demos/field-array.md
- support multi ops called synchronously for FieldArray
=> [bug fix] support multi ops called synchronously for FieldArray

packages/zent/src/button/Button.js
Component Button:
"wrapedChildren" -> "wrappedChildren"
=> fix: words spell error in Buttons (wrapedChildren->wrappedChildren)

packages/zent/src/loading/LoadingInstance.js
=> [bug fix] Loading: fix loading cannot be close because ReactDOM.render return null

.stylelintrc, packages/zent/__tests__/popover.js, packages/zent/src/mention/Mention.js, packages/zent/src/mention/constants.js, packages/zent/src/mention/demos/with-input-prefix.md, packages/zent/src/mention/findMentionAtCaretPosition.js, packages/zent/src/mention/position.js, packages/zent/src/mention/utils.js, packages/zent/src/popover/Popover.js, packages/zent/src/popover/README_en-US.md, packages/zent/src/popover/README_zh-CN.md, packages/zent/src/popover/trigger/Trigger.js, packages/zent/typings/libs/Popover.d.ts
1. Refactor Mention
2. Fix incorrect position when input has suffix or prefix
3. Add `getNodeForTriggerRefChange` to `Popover` trigger to allow custom trigger node.
=> [bug fix]Mention: Fix incorrect position when input has suffix or prefix

packages/zent/__tests__/timeline.js, packages/zent/assets/index.pcss, packages/zent/assets/theme/default.pcss, packages/zent/assets/timeline.pcss, packages/zent/jest.config.json, packages/zent/src/index.js, packages/zent/src/timeline/Dot.js, packages/zent/src/timeline/Item.js, packages/zent/src/timeline/README_en-US.md, packages/zent/src/timeline/README_zh-CN.md, packages/zent/src/timeline/Timeline.js, packages/zent/src/timeline/demos/array.md, packages/zent/src/timeline/demos/basic.md, packages/zent/src/timeline/demos/dynamic.md, packages/zent/src/timeline/index.js, packages/zent/src/timeline/validateProps.js, packages/zent/typings/index.d.ts, packages/zent/typings/libs/Timeline.d.ts
=> [new feature] Timeline组件

packages/zent/src/dialog/Dialog.js
=> [bug fix] Dialog: 增加isBrowser判断

packages/zent/src/swiper/Swiper.js
fix the bug remove child when there is only two #813
=> [bug fix] Swiper: fix remove child

packages/zent/src/split-button/README_en-US.md, packages/zent/src/split-button/README_zh-CN.md, packages/zent/src/split-button/SplitButton.js, packages/zent/src/split-button/demos/dropdown-position.md, packages/zent/typings/libs/SplitButton.d.ts
=> [new feature] SplitButton: add dropdown position

packages/zent/package.json, packages/zent/src/utils/component/animatedClosable.js
- 修复关闭动画组件(animatedClosable)卸载时没有清除计时器的问题
=> [bug fix] Dialog: 修复关闭Dialog时Animated组件报错的问题

packages/zent/__tests__/form/CreateForm-FieldArray.js, packages/zent/__tests__/form/Utils.js, packages/zent/__tests__/preview-image.js, packages/zent/src/form/Field.js, packages/zent/src/form/FieldArray.js, packages/zent/src/form/README_en-US.md, packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/constants.js, packages/zent/src/form/createForm.js, packages/zent/src/form/demos/basic.md, packages/zent/src/form/demos/field-array.md, packages/zent/src/form/demos/form-section.md, packages/zent/src/form/utils.js, packages/zent/src/preview-image/Image.js, packages/zent/src/preview-image/previewImage.js
* `initialize({members:[{name: 'foobar']})` now works as expect.
* `FieldArray` accepts a `value` prop now.
#Fixes #835
=> [bug fix] Form: Support setting value on FieldArray

packages/zent/src/datetimepicker/time/TimePanel.js
* [bug fix] Datepicker: 修复 rangepicker 时间禁用逻辑
=> [bug fix] Datepicker: 修复 rangepicker 时间禁用逻辑

packages/zent/src/grid/Grid.js
移除Grid中的cloneDeep, React 16 下 clone jsx 会报错。
=> [bugfix] 移除Grid中的cloneDeep

packages/zent/src/timeline/Item.js, packages/zent/src/timeline/Timeline.js
=> [bug fix] Timeline: 组件修改弹层定位

packages/zent/src/collapse/Collapse.js, packages/zent/src/collapse/README_en-US.md, packages/zent/src/collapse/README_zh-CN.md, packages/zent/typings/libs/Collapse.d.ts
=> [bug fix] Collapse: Fix Collpase activeKey prop type declaration

packages/zent/assets/cascader.pcss, packages/zent/src/cascader/Cascader.js, packages/zent/src/cascader/demos/loading.md
- [bug fix]Cascader: 修复当 value 值不存在时报错的问题
- [bug fix]Cascader: 修复 loading 状态时的样式问题
=> [bug fix]Cascader: 修复当 value 值不存在时报错的问题

packages/zent/__tests__/error-boundary.js, packages/zent/src/error-boundary/README_en-US.md, packages/zent/src/error-boundary/README_zh-CN.md, packages/zent/src/error-boundary/catchError.js, packages/zent/src/error-boundary/demos/hoc.md, packages/zent/src/error-boundary/index.js
1. Update doc to match the code
2. Add `catchError` HOC for use as a decorator.
=> [enhancement] ErrorBoundary: Update ErrorBoundary HOC

packages/zent/README_en-US.md, packages/zent/README_zh-CN.md
=> [bug fix] 修正文档内babel单词拼写错误

packages/zent/assets/select.pcss
=> [bug fix] Select: 修复因为类名变更导致的默认样式丢失问题

packages/zent/CHANGELOG.md, packages/zent/assets/card.pcss
Remove unnecessary `font-weight`
=> [bug fix] Card: remove unnecessary style

packages/zent/typings/index.d.ts, packages/zent/typings/libs/SplitButton.d.ts, packages/zent/typings/libs/Timeline.d.ts
Fix ts definitions:
* SplitButton
* Timeline
=> [bug fix] Fix ts definitions

packages/zent/src/auto-complete/AutoComplete.js
- add a judgment for 'keydown' event
=> [bug fix]AutoComplete: keydown 增加 'tab' 判断

packages/zent/src/grid/Footer.js, packages/zent/src/grid/Grid.js, packages/zent/src/grid/README_en-US.md, packages/zent/src/grid/README_zh-CN.md, packages/zent/src/grid/demos/pagination.md, packages/zent/src/table/README_en-US.md, packages/zent/src/table/README_zh-CN.md, packages/zent/src/table/Table.js, packages/zent/src/table/demos/pager.md, packages/zent/src/table/modules/Foot.js
- Table onChange returns pageSize change.
=> fix: Table onChange returns pageSize change

packages/zent/assets/datetimepicker.pcss, packages/zent/src/datetimepicker/WeekPicker.js, packages/zent/src/datetimepicker/date/DatePanel.js, packages/zent/src/datetimepicker/date/DatePanelBody.js, packages/zent/src/datetimepicker/demos/disabled-date.md
=> [bug fix] WeekPicker: Fix WeekPicker disabled style

packages/zent/typings/libs/Menu.d.ts
=> [bug fix] Menu：修复Menu的ts定义

packages/zent/typings/libs/Select.d.ts
- Select 的 filter 方法, 添加第二个参数的声明
=> [bug fix] Select: add type declaration of Select

packages/zent/src/form/FieldArray.js, packages/zent/src/form/Form.js, packages/zent/src/form/createForm.js, packages/zent/src/form/utils.js
Fixes sub FieldArray changes are not propagated.
Fixes #891
=> [bug fix] Form: Fix FieldArray renders wrong value after mutating field array

packages/zent/src/table/demos/selection.md, packages/zent/src/table/modules/Td.js
支持将 Table 中的 `Checkbox` 以及 `Radio` 展示为 `disabled && selected` 状态。
=> [bug fix] Table: 选择模式支持设置为选中但是不可修改的状态

packages/zent/package.json, packages/zent/src/icon/demos/all.md, packages/zent/yarn.lock
=> [bug fix] Icon: Fix typo

packages/zent/src/datetimepicker/DatePicker.js, packages/zent/src/datetimepicker/MonthPicker.js, packages/zent/src/datetimepicker/QuarterPicker.js, packages/zent/src/datetimepicker/TimePicker.js, packages/zent/src/datetimepicker/WeekPicker.js, packages/zent/src/datetimepicker/YearPicker.js, packages/zent/src/datetimepicker/constants/index.js
=> [bug fix] DatePicker 输入框增加默认属性 autoComplete="off"

packages/zent/src/form/FieldArray.js
Fix use before initialize in FieldArray constructor.
=> [bug fix] Form: Fix form field array initialize bug

packages/zent/src/infinite-scroller/InfiniteScroller.js, packages/zent/src/infinite-scroller/README_en-US.md, packages/zent/src/infinite-scroller/README_zh-CN.md
InfiniteScroller:  loadMore反复触发问题修复，文档错误修复
=> [bug fix] InfiniteScroller:  loadMore反复触发问题修复，文档错误修复

packages/zent/.babelrc, packages/zent/.es-babelrc, packages/zent/.gitignore, packages/zent/package.json, packages/zent/scripts/build.sh, scripts/check-git-hooks.sh
Support es module as an output format.
Fixes #914
=> [new feature] Add es module support

packages/zent/__tests__/form/GetControlGroup-Component_Fields.js, packages/zent/src/form/demos/buildin-field.md, packages/zent/src/form/form-components/SelectField.js
* [bug fix] FormSelectField 支持 tags 多选模式
* [bug fix] demos/builin-field.md 身份证有效期校验纠正
=> [bug fix] FormSelectField: 支持tags模式

packages/zent/assets/select.pcss, packages/zent/src/select/trigger/BaseTrigger.js, packages/zent/src/select/trigger/SimpleTrigger.js, packages/zent/src/select/trigger/TagsTrigger.js
=> fix: 修复select组件placeholder颜色没有置灰的问题

packages/zent/__tests__/tabs.js, packages/zent/assets/tabs.pcss, packages/zent/src/tabs/README_en-US.md, packages/zent/src/tabs/README_zh-CN.md, packages/zent/src/tabs/components/Nav.js, packages/zent/src/tabs/demos/nav-extra-content.md, packages/zent/src/tabs/index.js, packages/zent/typings/libs/Tabs.d.ts
=> Tabs nav extra content

packages/zent/src/select/Select.js, packages/zent/src/tree/new/Tree.js
Replace `Object.assign` with `lodash/assign`
=> [bug fix] Remove Object.assign calls

packages/zent/src/grid/README_en-US.md, packages/zent/src/grid/README_zh-CN.md, packages/zent/typings/libs/CheckBox.d.ts, packages/zent/typings/libs/Form.d.ts, packages/zent/typings/libs/Grid.d.ts, packages/zent/typings/libs/Sweetalert.d.ts, packages/zent/typings/libs/Table.d.ts
- grid ts定义文件拆分重写
- grid 文档参数类型修改
- 其他小的类型修正
=> [bug fix] Grid: typing定义文件

packages/zent/assets/sku.pcss, packages/zent/src/sku/components/SKUContainer.js
=> [bug fix] SKU: Fix incorrect pop z-index

packages/zent/src/datetimepicker/demos/disabled-time.md, packages/zent/src/table/README_en-US.md, packages/zent/src/table/README_zh-CN.md
* 修复 `DatePicker` 一个 demo 的bug
* 更新 `Table` 文档中的 `sortBy` 说明
=> [bug fix] Doc: Update docs and demos

packages/zent/assets/timeline.pcss, packages/zent/src/timeline/Item.js
=> [new theme] update timeline style

packages/zent/assets/table.pcss
[bug fix] Table:fix textAlign right
=> [bug fix] Table:fix textAlign right

packages/zent/assets/split-button.pcss, packages/zent/src/split-button/README_en-US.md, packages/zent/src/split-button/README_zh-CN.md, packages/zent/src/split-button/demos/basic.md
=> [new feature] SplitButton: 更新新版UI

packages/zent/package.json, packages/zent/src/form/Field.js, packages/zent/src/form/FieldArray.js, packages/zent/src/form/FormSection.js, packages/zent/src/utils/prop-types.js, packages/zent/yarn.lock
=> [bug fix] 修复Form对component prop类型的检查

packages/zent/src/select/components/Search.js, packages/zent/src/table/Table.js, packages/zent/src/table/modules/Head.js
Fix corner cases for:
1. Table
2. Select
=> [bug fix]: defensive programming

packages/zent/src/form/README_en-US.md, packages/zent/src/form/README_zh-CN.md
=> [doc]: add more details regarding custom form validation function

packages/zent/src/grid/Grid.js, packages/zent/src/grid/SelectionCheckboxAll.js, packages/zent/src/grid/demos/selection.md
- 对grid组件的selection传入的selectedRowKeys进行deepClone，防止在grid中出现修改上层组件数据的问题
=> fix: 修复了grid selection修改props传入数据的问题

packages/zent/src/grid/Grid.js
=> Grid: 修复极端情况的问题

packages/zent/assets/grid.pcss, packages/zent/src/grid/ColGroup.js, packages/zent/src/grid/Grid.js, packages/zent/src/grid/Header.js, packages/zent/src/grid/README_en-US.md, packages/zent/src/grid/README_zh-CN.md, packages/zent/src/grid/demos/headerGroup.md, packages/zent/src/grid/utils.js, packages/zent/typings/libs/Grid.d.ts
- some change
1. 新增表格bordered属性，控制展示外边框和列边框
2. 新增表头分组功能 
- another change
1. gird英文md，中文替换英文
=> [new feature]Grid: 新增表头分组功能

packages/zent/__tests__/datetimepicker/DatePicker.js, packages/zent/__tests__/datetimepicker/MonthPicker.js, packages/zent/__tests__/datetimepicker/utils.js, packages/zent/__tests__/utils/date.js, packages/zent/jest.config.json, packages/zent/package.json, packages/zent/scripts/test.sh, packages/zent/src/date-range-quick-picker/helper.js, packages/zent/src/datetimepicker/utils/index.js, packages/zent/src/sku/components/SKUContainer.js, packages/zent/src/utils/date/formatDate.js, packages/zent/src/utils/date/helpers.js, packages/zent/src/utils/date/i18n.js, packages/zent/src/utils/date/makeDateStr.js, packages/zent/src/utils/date/makeDateTimeStr.js, packages/zent/src/utils/date/parseDate.js, yarn.lock
=> feat: remove zan-utils

packages/zent/package.json, packages/zent/src/badge/demos/offset.md, packages/zent/src/checkbox/Checkbox.js, packages/zent/src/checkbox/Group.js, packages/zent/src/checkbox/GroupContext.js, packages/zent/src/utils/date/formatDate.js, packages/zent/src/utils/date/parseDate.js, yarn.lock
Use new context API for Checkbox
=> [bug fix] Checkbox: use new context API for Checkbox

packages/zent/assets/steps.scss
- [new feature]Steps: 组件样式根据设计稿进行调整
=> [new feature]Steps: 组件样式根据设计稿进行调整

packages/zent/assets/mixins/_popup.scss, packages/zent/assets/select.scss, packages/zent/src/auto-complete/AutoComplete.js, packages/zent/src/select/Select.js
- 调整 placeholder 的颜色到 stroke-4
- 调整 popover-content 的上下内边距
=> style: 根据设计语言验收 调整 select 的样式

packages/zent/assets/switch/_zent-switch-status.scss
=> Switch：loading 圈样式修改

packages/zent/assets/button/_zent-button-style.scss, packages/zent/assets/button/_zent-button.scss, packages/zent/assets/pagination.scss, packages/zent/assets/split-button.scss, packages/zent/src/button/Button.js, packages/zent/src/button/demos/loading.md, packages/zent/src/button/demos/style.md, packages/zent/src/pagination/components/button/ArrowButton.js, packages/zent/src/pagination/components/button/PageNumberButton.js, packages/zent/src/pop/Pop.js, packages/zent/src/split-button/README_en-US.md, packages/zent/src/split-button/README_zh-CN.md, packages/zent/src/split-button/SplitButton.js, packages/zent/src/split-button/demos/basic.md, packages/zent/src/sweetalert/index.js
Remove `secondary` type from Button
=> Button: remove secondary type from Button

packages/zent/src/portal/LayeredPortal.tsx, packages/zent/src/portal/Portal.tsx, packages/zent/src/portal/PurePortal.tsx, packages/zent/src/portal/context.ts, packages/zent/src/portal/withNonScrollable.tsx
add a method `contains` for Portal to verify if an element is child of a portal
=> add method `contains` for portal

packages/zent/RELEASE_NEXT.md, packages/zent/__tests__/input.js, packages/zent/__tests__/number-input.js, packages/zent/__tests__/slider.js, packages/zent/assets/number-input.scss, packages/zent/package.json, packages/zent/src/input/Input.tsx, packages/zent/src/number-input/NumberInput.tsx, packages/zent/src/number-input/README_en-US.md, packages/zent/src/number-input/README_zh-CN.md, packages/zent/src/number-input/demos/event-handler.md, packages/zent/src/slider/InputField.tsx, packages/zent/src/slider/Slider.tsx, yarn.lock
=> [refactory] number input

packages/zent/src/avatar/Avatar.tsx
replace componentWillReceiveProps with getDerivedStateFromProp in Avatar
=> replace componentWillReceiveProps with getDerivedStateFromProp in Avatar

packages/zent/src/affix/Affix.tsx, packages/zent/src/alert/Alert.tsx, packages/zent/src/badge/Badge.tsx, packages/zent/src/block-header/BlockHeader.tsx, packages/zent/src/breadcrumb/Breadcrumb.tsx, packages/zent/src/button/Button.tsx, packages/zent/src/button/Group.tsx
=> improve types

packages/zent/src/radio/AbstractRadio.ts, packages/zent/src/radio/Group.tsx
=> fix radio types

packages/zent/assets/dialog.scss, packages/zent/assets/grid.scss, packages/zent/assets/pagination.scss, packages/zent/assets/pop.scss, packages/zent/assets/table.scss, packages/zent/src/pagination/layout/lite.ts, packages/zent/src/pagination/layout/mini.ts, packages/zent/src/pagination/layout/normal.ts
- 删除 Pop 组件的 content 最小宽度
- 修复 Pagination 组件的按钮样式选择器权重低导致样式被覆盖的问题
- 修复 Pagination 组件在 total 为 0 时下一页按钮仍可点击的问题
- 修复 Grid 组件排序按钮靠右时无空隙的样式问题
- 修改 Table 组件表格头部和 hover 行的背景色
- 删除 Dialog 组件的 body 最小高度
=> [bug fix] 修复部分新版组件的样式问题

packages/zent/src/grid/README_en-US.md, packages/zent/src/grid/README_zh-CN.md, packages/zent/src/grid/Row.tsx
=> [new feature] Grid: bodyRender 会传入 fixed 参数

packages/zent/__tests__/number-input.js, packages/zent/src/number-input/NumberInput.tsx
1. Fork [the repository](https://github.com/youzan/zent) and create your branch from `master`.
2. Follow the [contributing guide](../CONTRIBUTING.md) to setup your develop environment.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Describe your pull request.
[bug fix / breaking change / new feature] 组件名字：修改内容描述
说明：
* 前面方括号用来区分 Issue / PR 的 类型：bug fix - 改 bug；breaking change: 不兼容的改动；new feature：新功能
* 修改内容尽可能言简意赅，总结 PR 的改动或者描述 Issue
* 描述请用中文
* 组件名字请用英文，首字母大写
示例：
* [bug fix] Button: 修改颜色
* [breaking change] Loading: 删除  `static` 属性
* [new feature] Form: 增加 `FormSelection` 支持
* [new feature] 新增 Abc 组件
* 默认情况下所有加了 bug / enhancement 这两个 …
=> [bugfix] NumberInput

packages/zent/package.json, packages/zent/src/copy-button/index.tsx, packages/zent/src/dialog/DialogEl.tsx, packages/zent/src/portal/Portal.tsx, packages/zent/src/slider/Points.tsx, site/package.json, yarn.lock
=> [bugfix] 连续开关dialog时body滚动问题

.eslintignore, packages/zent/src/pagination/MiniPagination.tsx, packages/zent/src/pagination/components/PageSizeChanger.tsx, packages/zent/src/pagination/components/button/ArrowButton.tsx, packages/zent/src/pagination/components/jumper/BasePageJumper.tsx, packages/zent/src/pagination/components/jumper/MiniPageJumper.tsx, packages/zent/src/pagination/components/jumper/PageJumper.tsx, packages/zent/src/pagination/demos/empty.md, packages/zent/src/pagination/impl/AbstractPagination.tsx, packages/zent/src/pagination/impl/BasePagination.ts, packages/zent/src/pagination/layout/lite.ts, packages/zent/src/pagination/layout/mini.ts, packages/zent/src/pagination/layout/normal.ts
1. 删除 `componentWillReceiveProps`
2. 优化上一个、下一个按钮的禁用逻辑
=> Pagination 优化

packages/zent/src/utils/component/AnimateHeight.tsx
refactor animation height, remove useless features and componentWillReceiveProps
=> refactor animation height

packages/zent/assets/table.scss, packages/zent/src/table/demos/batch.md
=> fix table batch operation styles

packages/zent/RELEASE_NEXT.md, packages/zent/src/pagination/README_en-US.md, packages/zent/src/pagination/README_zh-CN.md, packages/zent/src/pagination/components/PageSizeChanger.tsx, packages/zent/src/pagination/components/button/ArrowButton.tsx, packages/zent/src/pagination/components/button/PageNumberButton.tsx, packages/zent/src/pagination/components/jumper/BasePageJumper.tsx, packages/zent/src/pagination/components/jumper/MiniPageJumper.tsx, packages/zent/src/pagination/components/jumper/PageJumper.tsx, packages/zent/src/pagination/components/list/BasePageList.ts, packages/zent/src/pagination/demos/format.md, packages/zent/src/pagination/impl/AbstractPagination.tsx, packages/zent/src/pagination/impl/BasePagination.ts, packages/zent/src/pagination/layout/getPageRange.ts, packages/zent/tsconfig.json
1. Add `formatTotal` to `Pagination`
2. Update type definitions
=> Add formatTotal to Pagination

packages/zent/assets/dialog.scss, packages/zent/assets/theme/_default.scss
=> Update theme color

packages/zent/src/slider/Points.tsx, packages/zent/src/slider/Slider.tsx, packages/zent/src/upload/components/UploadPopup.tsx
=> [bug fix] Slider: slider和upload去除componentWillReceiveProps

packages/zent/package.json, packages/zent/scripts/cruiser/analyzer.ts, packages/zent/scripts/cruiser/registry.ts, packages/zent/src/portal/Portal.tsx, site/package.json, yarn.lock
=> upgrade to typescript3.5

packages/zent/src/grid/Grid.tsx, packages/zent/src/table/README_en-US.md, packages/zent/src/table/README_zh-CN.md, packages/zent/src/table/Table.tsx, packages/zent/src/table/modules/Foot.tsx
Add `formatTotal` to `Table` and `Grid`
=> Add formatTotal to Table and Grid

packages/zent/RELEASE_NEXT.md, packages/zent/assets/pagination.scss
=> Align pagination to right

packages/zent/package.json, site/package.json, yarn.lock
https://github.com/microsoft/TypeScript/issues/32057
=> revert ts to 3.4.5. 3.5 has serious bugs

packages/zent/assets/layout.scss, packages/zent/assets/pagination.scss, packages/zent/assets/table.scss
Prefer `flex-start` and `flex-end`
=> use flex-*

packages/zent/src/popover/Popover.tsx, packages/zent/src/popover/demos/nested.md, packages/zent/src/portal/MountElement.ts, packages/zent/src/portal/Portal.tsx, packages/zent/src/portal/util.ts
=> fix portal

packages/zent/RELEASE_NEXT.md, packages/zent/src/popover/Content.tsx, packages/zent/src/popover/README_en-US.md, packages/zent/src/popover/README_zh-CN.md
Ensure content is within viewport when `onPositionReady` is called
=> Popover ready fix

packages/zent/src/portal/MountElement.ts, packages/zent/src/portal/Portal.tsx
=> fix edge case for portal

packages/zent/src/number-input/NumberInput.tsx
prevent number input from unnecessary change event
=> prevent number input from unnecessary change event

packages/zent/src/input/types.ts, packages/zent/src/number-input/NumberInput.tsx, packages/zent/src/pagination/components/jumper/BasePageJumper.tsx, packages/zent/src/pagination/components/jumper/MiniPageJumper.tsx, packages/zent/src/pagination/components/jumper/PageJumper.tsx, packages/zent/src/popover/withPopover.tsx
=> fix pagination input triggers form submit

site/src/components/page-footer/index.js
更新页面底部的 微信小程序组件库 链接为 vant-weapp
=> update weapp url in site

packages/zent/assets/alert.scss, packages/zent/assets/input.scss
- 修改 Alert 组件 info 模式下的背景色和边框色
- 修复 Input 组件 icon 部分没有白色背景的样式错误
=> [bugfix] Input、Alert: 样式修改

packages/zent/assets/alert.scss, packages/zent/assets/input.scss
=> Revert "[bugfix] Input、Alert: 样式修改"

packages/zent/src/grid/Body.tsx, packages/zent/src/grid/Cell.tsx, packages/zent/src/grid/ColGroup.tsx, packages/zent/src/grid/Footer.tsx, packages/zent/src/grid/Grid.tsx, packages/zent/src/grid/Header.tsx, packages/zent/src/grid/README_en-US.md, packages/zent/src/grid/README_zh-CN.md, packages/zent/src/grid/Row.tsx, packages/zent/src/grid/SelectionCheckbox.tsx, packages/zent/src/grid/SelectionCheckboxAll.tsx, packages/zent/src/grid/Store.ts, packages/zent/src/grid/types.ts, packages/zent/src/grid/utils.ts
=> [bug fix] Grid: 组件类型补完

README-zh_CN.md, README.md, packages/zent/src/form/utils.ts, packages/zent/src/grid/Grid.tsx, packages/zent/src/grid/Header.tsx, packages/zent/src/grid/SelectionCheckbox.tsx, packages/zent/src/grid/SelectionCheckboxAll.tsx, packages/zent/src/swiper/Swiper.tsx, packages/zent/src/swiper/SwiperDots.tsx, packages/zent/src/utils/component/LazyMount.tsx
* Remove `componentWilReceiveProps` in `Swiper` and `LazyMount`
* Fix typings in `Grid`
* Improve `isFunctional` checking. Fixes #1125
=> Remove legacy lifetime hooks in Swiper and LazyMount

packages/zent/__tests__/radio.js, packages/zent/src/radio/AbstractRadio.tsx, packages/zent/src/radio/Group.tsx, packages/zent/src/radio/GroupContext.tsx, packages/zent/src/radio/Radio.tsx, packages/zent/src/radio/RadioButton.tsx
=> [refactor] radio

packages/zent/RELEASE_NEXT.md
=> [docs] next radio

packages/zent/src/radio/Radio.tsx
=> [radio] fix types

packages/zent/RELEASE_NEXT.md, packages/zent/__tests__/checkbox-group.js, packages/zent/__tests__/checkbox.js, packages/zent/assets/checkbox.scss, packages/zent/src/checkbox/Checkbox.tsx, packages/zent/src/checkbox/Group.tsx
Checkbox `disable` will always has higher priority than parent CheckboxGroup
=> [refactor] Checkbox

packages/zent/__tests__/input.js, packages/zent/__tests__/tag.js, packages/zent/src/icon/Icon.tsx
refactor icon to function component
this improves performance
=> [Refactor] Icon

packages/zent/src/popover/trigger/Trigger.tsx, packages/zent/src/utils/component/DOMRef.tsx
fix ref for function component trigger
=> [popover] fix ref for function component trigger

packages/zent/src/datetimepicker/quarter/QuarterPanelBody.tsx
- [bug fix] QuarterPicker: 修复选择某年季度后，任何年该季度都展示选中
=> [bug fix] QuarterPicker: 修复选择某年季度后，任何年该季度都展示选中

packages/zent/assets/input.scss, packages/zent/src/input/Input.tsx
move display from inlined style to css
=> [input] move display from inlined style to css

packages/zent/assets/input.scss, packages/zent/src/input/InputCore.tsx, packages/zent/src/input/demos/show-clear.md, packages/zent/src/input/types.ts
=> [input] place icon at right side

packages/zent/assets/notify.scss, packages/zent/src/notify/Notify.tsx, packages/zent/src/notify/NotifyContent.tsx, packages/zent/src/notify/README_en-US.md, packages/zent/src/notify/README_zh-CN.md, packages/zent/src/notify/demos/basic.md, packages/zent/src/notify/demos/global-duration.md, packages/zent/src/notify/index.ts
- 组件展示样式根据最新设计标准更新
- 动画效果更新（默认停留延迟时间/运动函数等， 替换为transition实现）
=> [bug fix] Notify: update style

packages/zent/__tests__/color-picker.js, packages/zent/src/colorpicker/SketchFields.tsx, packages/zent/src/colorpicker/common/ColorWrap.tsx, packages/zent/src/colorpicker/common/EditableInput.tsx
删除 ColorPicker 组件里面 componentWillReceiveProps 等 unsafe 的 生命周期
=> ColorPicker 删除 componentWillReceiveProps

packages/zent/assets/upload.scss
修改了upload的颜色过浅，+改为原主题色的stroke-2，边框改为原主题色的stroke-5
=> hotfix:change upload color

packages/zent/src/table/Table.tsx
=> [table] fix ITableColumn types

packages/zent/src/loading/hooks/useDelayed.ts
Set delay correctly on initial render
=> fix loading delay default value

packages/zent/assets/alert.scss
- 修改 Alert 组件 warning type 下的颜色
=> [bug fix] Alert: warning 模式颜色修改

packages/zent/src/pagination/demos/basic.md, packages/zent/src/pagination/layout/normal.ts
Fix these two cases:
* 1 ... 3
* 1 ... 2
=> fix edge case for pagination normal layout

packages/zent/src/select/trigger/TagsTrigger.tsx
[Select] prevent delete tags when disabled
=> [Select] prevent delete tags when disabled

packages/zent/src/datetimepicker/TimePicker.tsx
=> [bug fix] TimePicker: 修复 resetTime 的问题

packages/zent/src/datetimepicker/DatePicker.tsx, packages/zent/src/datetimepicker/TimePicker.tsx
=> Fix timepicker warning when value is missing

packages/zent/package.json, yarn.lock
=> upgrade to typescript 3.6

packages/zent/assets/input.scss, packages/zent/src/input/demos/disabled.md
=> [Input] fix background when disabled

packages/zent/src/notice/Container.tsx, packages/zent/src/notice/Wrap.tsx
=> [Notice] fix Notice.close not working

packages/babel-plugin-zent/README_en-US.md, packages/babel-plugin-zent/README_zh-CN.md, packages/babel-plugin-zent/__tests__/index.js, packages/babel-plugin-zent/src/index.js
=> Add libraryName option

packages/zent/src/form/shared.tsx
built-in form component defaultValue should be optional
=> built-in form component defaultValue should be optional [ci skip]

packages/zent/__tests__/notify.js, packages/zent/assets/notify.scss, packages/zent/src/notify/Notify.tsx, packages/zent/src/notify/NotifyContent.tsx, packages/zent/src/notify/README_en-US.md, packages/zent/src/notify/README_zh-CN.md, packages/zent/src/notify/demos/basic.md, packages/zent/src/notify/demos/global-duration.md, packages/zent/src/notify/index.ts
=> [new feature] Notify: 增加`info`(常规提示)支持

packages/zent/__tests__/progress.js, packages/zent/assets/progress.scss, packages/zent/src/progress/components/AnimatedArc.tsx, packages/zent/src/progress/components/CircleProgress.tsx
=> Fix progress in safari

packages/zent/__tests__/table/combine.js, packages/zent/assets/pagination.scss, packages/zent/src/cascader/Cascader.tsx, packages/zent/src/cascader/components/TabsContent.tsx, packages/zent/src/copy-button/index.tsx, packages/zent/src/datetimepicker/QuarterPicker.tsx, packages/zent/src/grid/Grid.tsx, packages/zent/src/i18n/I18nReceiver.ts, packages/zent/src/i18n/en-US.tsx, packages/zent/src/i18n/locale.ts, packages/zent/src/i18n/zh-CN.tsx, packages/zent/src/mention/Mention.tsx, packages/zent/src/pagination/components/PageSizeChanger.tsx, packages/zent/src/pagination/components/jumper/PageJumper.tsx, packages/zent/src/pop/Pop.tsx, packages/zent/src/preview-image/Image.tsx, packages/zent/src/select/Popup.tsx, packages/zent/src/select/trigger/BaseTrigger.tsx, packages/zent/src/select/trigger/InputTrigger.tsx, packages/zent/src/select/trigger/SimpleTrigger.tsx, packages/zent/src/select/trigger/TagsTrigger.tsx, packages/zent/src/sweetalert/ActionButton.tsx, packages/zent/src/sweetalert/index.tsx, packages/zent/src/table/Table.tsx, packages/zent/src/upload/components/FileInput.tsx
- Add type to i18n usages
- Use function for complex string templates
=> Update i18n usage

packages/zent/__tests__/utils/fecha.js, packages/zent/jest.config.json, packages/zent/package.json, packages/zent/src/i18n/time-locale.ts, packages/zent/src/utils/date/fecha.ts, packages/zent/src/utils/date/formatDate.ts, packages/zent/src/utils/date/parseDate.ts, yarn.lock
Fork https://github.com/taylorhakes/fecha/, and rewrite using TypeScript.
__Why?__
I'm tired of the broken TypeScript definition.
=> fork fecha

packages/zent/package.json, packages/zent/scripts/build.sh, packages/zent/src/datetimepicker/QuarterPicker.tsx, packages/zent/src/datetimepicker/WeekPicker.tsx, packages/zent/src/datetimepicker/date/DatePanelBody.tsx, packages/zent/src/datetimepicker/quarter/QuarterPanelBody.tsx, packages/zent/src/datetimepicker/utils/index.ts, packages/zent/src/number-input/integer.ts, packages/zent/tslint.json, yarn.lock
=> Upgrade to date-fns@2

packages/zent/src/form/shared.tsx
optimize defaultRenderError user experience
=> [Form] optimize defaultRenderError user experience [ci skip]

packages/zent/assets/block-header.scss, packages/zent/src/block-header/BlockHeader.tsx
- 设置 BlockHeader 组件内的 Icon 大小为 16px
=> [bugfix] BlockHeader: 调整组件 icon 的大小

packages/zent/assets/grid.scss, packages/zent/src/grid/BatchComponents.tsx, packages/zent/src/grid/Grid.tsx, packages/zent/src/grid/demos/batch.md
=>  [bug fix]grid: 修复grid滚动模式下批量操作导致grid展示异常

packages/zent/src/form/form-components/RadioGroupField.tsx
+ 当前版本defaultValue为falsy值时会被替换为null，例如0、false；
=> [bug fix] FormRadioGroupField: 修改defaultValue判断方式

.sass-lint.yml, packages/zent/assets/checkbox.scss, packages/zent/assets/datetimepicker.scss, packages/zent/assets/pagination.scss, packages/zent/assets/tree.scss, packages/zent/plugins/postcss-plugin-version-attribute.js, packages/zent/src/tabs/components/tabs-nav/CommonTabsNav.tsx
=> fix bugs in style isolation

packages/zent/assets/button.scss, packages/zent/src/button/Link.tsx, packages/zent/src/button/demos/link.md, packages/zent/src/button/index.ts
=> Add Link component

packages/zent/src/upload/components/UploadPopup.tsx, packages/zent/src/upload/demos/basic.md
[bug fix] Upload: 修复上传时删除预览小图报错
- 通过匹配 localFile 的 __uid 和上传索引添加 progress
- simpleUploadDemo 上传后获取数据的位置
=> fix: set progress in local file

packages/zent/src/select/Popup.tsx
=> Fix missing selected item after filter applied

packages/zent/__tests__/utils/enquire/LICENSE, packages/zent/__tests__/utils/enquire/MediaQuery.js, packages/zent/__tests__/utils/enquire/MediaQueryDispatch.js, packages/zent/__tests__/utils/enquire/QueryHandler.js, packages/zent/src/layout/components/BreakPointHub.tsx, packages/zent/src/utils/enquire/LICENSE, packages/zent/src/utils/enquire/MediaQuery.ts, packages/zent/src/utils/enquire/MediaQueryDispatch.ts, packages/zent/src/utils/enquire/QueryHandler.ts, packages/zent/src/utils/enquire/index.ts, packages/zent/src/utils/enquire/types.ts, scripts/test-component.sh
=> fork enquire for SSR

packages/zent/assets/datetimepicker.scss, packages/zent/src/datetimepicker/DatePicker.tsx, packages/zent/src/datetimepicker/MonthPicker.tsx, packages/zent/src/datetimepicker/QuarterPicker.tsx, packages/zent/src/datetimepicker/TimePicker.tsx, packages/zent/src/datetimepicker/WeekPicker.tsx, packages/zent/src/datetimepicker/YearPicker.tsx
=> [bugfix] DatePicker: 组件右侧图标尺寸调整

packages/zent/src/block-header/BlockHeader.tsx, packages/zent/src/block-header/README_en-US.md, packages/zent/src/block-header/README_zh-CN.md
- `BlockHeader` 组件 `title` 属性类型改为 `ReactNode`
=> [Feature] BlockHeader: titile 类型支持 ReactNode

packages/zent/assets/form.scss, packages/zent/src/form/Error.tsx, packages/zent/src/form/demos/2.builtin-field.md, packages/zent/src/form/form-components/NumberInputField.tsx, packages/zent/src/form/form-components/SelectField.tsx
1. Move all inner component props to `props.props`
2. Update form label error style
=> Form field props

packages/zent/src/copy-button/index.tsx, packages/zent/src/form/form-components/SelectField.tsx, packages/zent/src/form/index.ts
1. 修复 CopyButton onCopySuccess/onCopyError 定义
2. Form 导出 FormDescription 组件
3. SelectFormField 透传 withoutLabel 属性
=> fix: 修复 TS 定义

packages/zent/__tests__/cascader.js, packages/zent/assets/cascader.scss, packages/zent/src/cascader/Cascader.tsx, packages/zent/src/cascader/README_en-US.md, packages/zent/src/cascader/README_zh-CN.md, packages/zent/src/cascader/demos/disabled.md, packages/zent/src/disabled/demos/1.basic.md
=> cascader 新增disabled 属性

README-zh_CN.md, README.md, packages/zent/__tests__/cascader.js, packages/zent/assets/cascader.scss, packages/zent/src/cascader/Cascader.tsx, packages/zent/src/cascader/README_en-US.md, packages/zent/src/cascader/README_zh-CN.md, packages/zent/src/cascader/components/MenuContent.tsx, packages/zent/src/cascader/components/TabsContent.tsx
1. Update placeholder text color
2. Remove `prefix`
3. Update README
=> update cascader style and remove prefix

packages/zent/assets/pagination.scss, packages/zent/src/pagination/demos/02-dynamic-page-size.md
Add default font-size and color
=> fix pagination default color and font size

packages/zent/assets/upload.scss, packages/zent/src/upload/Upload.tsx, packages/zent/src/upload/components/FileInput.tsx, packages/zent/src/upload/components/normal/Item.tsx, packages/zent/src/upload/components/normal/List.tsx, packages/zent/src/upload/components/normal/Trigger.tsx
- 修改普通 Upload 组件的 className 前缀，防止与 `@zent/compat` 包发生冲突
- 修复在删除上传项时页数计算错误的 bug
=> [Bugfix] Upload: 修复class冲突和翻页错误

packages/zent/__tests__/color-picker.js, packages/zent/assets/colorpicker.scss, packages/zent/assets/form.scss, packages/zent/src/colorpicker/common/Hue.tsx, packages/zent/src/colorpicker/common/Saturation.tsx, packages/zent/src/colorpicker/index.tsx, packages/zent/src/form/form-components/CheckboxField.tsx, packages/zent/src/form/form-components/CheckboxGroupField.tsx, packages/zent/src/form/form-components/RadioGroupField.tsx, packages/zent/src/form/form-components/SwitchField.tsx
1. Fix `ColorPicker` dnd performance, much smoother
2. Apply different `line-height` to non-input form controls
=> fix colorpicker dragging issue and form styles

packages/zent/__tests__/block-header.js, packages/zent/assets/block-header.scss, packages/zent/src/block-header/BlockHeader.tsx, packages/zent/src/block-header/README_en-US.md, packages/zent/src/block-header/README_zh-CN.md, packages/zent/src/block-header/demos/type.md
- 按设计稿样式调整标题文字样式
- 增加可选type属性和对应的通用样式类型
=> [bug fix]: BlockHeader 按最新样式调整/增加通用样式类型

packages/zent/src/progress/Progress.tsx
=> [bug fix]: 进度条传入的百分比值增加对<0和>100情况的处理

packages/zent/assets/form.scss
- Label与Content之间边距修改为8px
- 错误提示添加8px的上边距
- 必填' * '颜色修改为`#D40000`
=> [style] Form: 输入框边距样式优化、'*' 颜色修改

packages/zent/src/grid/Grid.tsx, packages/zent/src/grid/README_en-US.md, packages/zent/src/grid/README_zh-CN.md, packages/zent/src/grid/demos/autoStick.md
=> [new feature] Grid: 表头吸顶支持自定义offset

packages/zent/assets/form.scss
=> [style] Form: 描述文字上边距改为8px

packages/zent/src/form/FieldSet.tsx
=> Revert "[bug fix] FieldSet: prop类型修复"

packages/zent/assets/grid.scss, packages/zent/src/grid/Body.tsx, packages/zent/src/grid/Grid.tsx, packages/zent/src/grid/README_en-US.md, packages/zent/src/grid/README_zh-CN.md, packages/zent/src/grid/Row.tsx, packages/zent/src/grid/demos/disable-hover-highlight.md, packages/zent/src/grid/demos/simple.md
=> [new feature]Grid: 支持是否禁用鼠标高亮效果

packages/zent/package.json, packages/zent/plugins/tsconfig.json, packages/zent/tsconfig.plugins.json, site/package.json, yarn.lock
fibers v3 not working for windows
tsc plugins/*.ts not working for windows
=> fix windows development

packages/zent/__tests__/tabs.js, packages/zent/assets/tabs.scss, packages/zent/src/tabs/components/tab/ButtonTab.tsx, packages/zent/src/tabs/components/tabs-nav/ButtonTabsNav.tsx
+ 删除icon改为上下居中，大小14px，颜色#969799，右边距10px
+ 按钮类型样式修改，具体样式参照ButtonRadio
=> [style] Tabs:  删除icon居中 button类型样式优化

packages/zent/src/grid/Grid.tsx
=> [bug fix] Grid: 修复scroll.x变化时fixed列阴影展示问题

packages/zent/src/button/Directive.tsx, packages/zent/src/form/Form.tsx, packages/zent/src/form/form-components/InputField.tsx, packages/zent/src/select/Select.tsx, packages/zent/src/select/components/Option.tsx
1. FormInputField: 修复类型定义
2. Select：data改为可选属性
3. Option：text、onClick改为可选属性
=> [bug fix] Form: 修复Select、Option、FormInputField的props类型

packages/zent/package.json, packages/zent/src/collapse/README_en-US.md, packages/zent/src/collapse/README_zh-CN.md, packages/zent/src/form/README_en-US.md, packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/ZentForm.tsx, packages/zent/src/form/demos/10.combine-errors.md, packages/zent/src/form/demos/11.normalizer.md, packages/zent/src/form/demos/12.preview.md, packages/zent/src/form/demos/13.interact.md, packages/zent/src/form/demos/14.interact.2.md, packages/zent/src/form/demos/15.submit.md, packages/zent/src/form/demos/3.multi-value.md, packages/zent/src/form/demos/6.validator-middleware.md, packages/zent/src/form/demos/7.layout.md, packages/zent/src/form/demos/8.field-array.md, packages/zent/src/form/demos/9.model-first.md, packages/zent/src/form/index.ts, yarn.lock
=> [new feature] Form: 导出ValidatorMiddlewares

packages/zent/src/alert/ScrollAlert.tsx
- change default transitionDuration from 600 to 0
=> fix: default transitionDuration

packages/zent/__tests__/alert.js, packages/zent/src/alert/ScrollAlert.tsx
- activeIndex into state
- componentDidUpdate handle children update
=> scroll-alert props's children update handler

packages/zent/package.json, packages/zent/src/pagination/components/jumper/BasePageJumper.tsx
Correctly handle normalized page number when press Enter
=> Fix Pagination jump edge case

packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/demos/16.validate-option.md
=> docs: Form文档补充

packages/zent/src/form/form-components/SelectField.tsx, packages/zent/src/select/Select.tsx, packages/zent/src/utils/isString.ts
=> [bug fix] FormSelectField: 增加onDelete处理

packages/zent/__tests__/swiper.js, packages/zent/src/swiper/Swiper.tsx
- 内部`autoplay`由`setInterval`改为`setTimeout`
- 当`swipeTo`的index与组件当前currentIndex相同时，直接return
=> [bug fix] Swiper:  优化了Swiper的内部逻辑

packages/zent/package.json, packages/zent/src/icon/Icon.tsx, packages/zent/src/icon/demos/all.md, yarn.lock
=> Update zenticons to 3.6.0

packages/zent/src/form/Form.tsx, packages/zent/src/form/context.tsx
`Form`的`disabled`属性一直没有作用，需要加上`Disabled`组件，透传`disabled`
=> [bug fix]: support form disabled prop

packages/zent/package.json, yarn.lock
fix wrong icon font url in css
=> Upgrade zenticons to 3.6.1

packages/zent/src/form/Form.tsx, packages/zent/src/form/Label.tsx, packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/context.tsx, packages/zent/src/form/demos/1.basic.md, packages/zent/src/form/demos/17.form-context.md, packages/zent/src/form/index.ts
1. `labelWidth`、`labelPosition`合并到`labelStyle`，由用户自己设置label的样式
2. 导出`FormContext`
=> [new feature] Form: expose FormContext

packages/zent/package.json, packages/zent/src/number-input/NumberInput.tsx, site/package.json, yarn.lock
1. `typescript@3.9.7`
2. `tslib@2.0.0`
=> Update TypeScript and tslib

site/package.json, yarn.lock
=> fix code highlight in docs

packages/zent/assets/loading.scss, packages/zent/src/loading/BlockLoading.tsx, packages/zent/src/loading/FullScreenLoading.tsx, packages/zent/src/loading/InlineLoading.tsx, packages/zent/src/loading/README_en-US.md, packages/zent/src/loading/README_zh-CN.md, packages/zent/src/loading/components/icons/Circle.tsx, packages/zent/src/loading/components/icons/IconProps.ts, packages/zent/src/loading/components/icons/Youzan.tsx, packages/zent/src/loading/demos/preset.md, packages/zent/src/loading/props.ts
Add colorPreset support to loading
=> Add colorPreset support to loading

packages/zent/package.json, yarn.lock
=> Update zenticons to v3.6.2

packages/zent/assets/checkbox.scss
=> fix Checkbox margin

packages/zent/assets/progress.scss, packages/zent/src/progress/components/CircleProgress.tsx, packages/zent/src/progress/demos/format.md
组件progress 的circle类型
- 修改组件的format样式居中实现
- 修复自定义颜色color和宽度strokeWidth属性不生效问题
=> [Fix] 修复progress circle类型组件的format、color、strokeWidth问题

packages/zent/src/transfer/types.ts
- pagination、disabled 类型定义改为可选
=> fix(transfer): type bug

packages/zent/assets/button.scss, packages/zent/assets/dialog.scss, packages/zent/assets/pop.scss
=> 调整buttons间隔

packages/zent/__tests__/disabled.js, packages/zent/__tests__/select.js, packages/zent/assets/auto-complete.scss, packages/zent/assets/pagination.scss, packages/zent/assets/select.scss, packages/zent/src/select/Option.tsx, packages/zent/src/select/Search.tsx, packages/zent/src/select/Select.tsx, packages/zent/src/select/Tag.tsx
=> rename zent-select => zent-select-v2

packages/zent/src/constants.ts
- `__ARROW_OFFSET_HORIZONTAL__`
- `__ARROW_OFFSET_VERTICAL__`
=> export compiler constants

packages/zent/src/cascader/MenuCascader.tsx
- Fix `MenuCascader` multiple mode typing bug
=> fix Cascader typing bug

packages/zent/package.json, packages/zent/src/input/TextArea.tsx, packages/zent/src/utils/dom/autosize.ts, yarn.lock
=> fork autosize

packages/zent/assets/date-picker.scss, packages/zent/src/date-picker/CombinedDateRangePicker.tsx, packages/zent/src/date-picker/DatePicker.tsx, packages/zent/src/date-picker/DateRangePicker.tsx, packages/zent/src/date-picker/MonthPicker.tsx, packages/zent/src/date-picker/QuarterPicker.tsx, packages/zent/src/date-picker/README_en-US.md, packages/zent/src/date-picker/README_zh-CN.md, packages/zent/src/date-picker/WeekPicker.tsx, packages/zent/src/date-picker/YearPicker.tsx, packages/zent/src/date-picker/components/PanelCell.tsx, packages/zent/src/date-picker/types.ts
- Fix `CombinedDateRangePicker`'s style
- Fix type definition of `valueType`、`onChange`
- Fix file format of ReadMe
=> [bug fix]:  Fix DatePicker's broken style, and fix type definition of `valueType`、`onChange`

packages/zent/src/select/Select.tsx, site/src/components/page-header/index.js, site/src/components/page-header/style.scss
- Add missing `className` support in `Select`
- Add documentation link for v7 and v6
=> Add documentation link for v7 and v6

packages/zent/src/pop/Pop.tsx
Fix optional properties in props
=> fix Pop props optional type

packages/zent/src/input/InputCore.tsx, packages/zent/src/input/demos/disabled.md
=> Hide Input clear button if it's readonly or disabled

packages/zent/src/date-picker/hooks/useConfirmStatus.ts, packages/zent/src/date-picker/panels/date-panel/DateFooter.tsx
TimePicker
- 增加空值禁用
- 上层组件使用TimePicker 空值回调不处理
=> bugfix: 修复timepicker空值未禁用问题

packages/zent/src/date-picker/README_en-US.md, packages/zent/src/date-picker/README_zh-CN.md, packages/zent/src/date-picker/components/CombinedPickerBase.tsx, packages/zent/src/date-picker/components/RangePickerBase.tsx, packages/zent/src/date-picker/demos/basic.md, packages/zent/src/date-picker/hooks/useRangeDisabledDate.ts, packages/zent/src/date-picker/types.ts
DatePicker
- 新增 `dateSpan` 属性，仅 `DateRangePicker` 和 `CombinedDateRangePicker` 组件可用
=> feature: 日期范围选择组件增加属性，快捷限制可选范围

packages/zent/src/date-picker/components/PanelCell.tsx, packages/zent/src/date-picker/panels/date-panel/DateBody.tsx, packages/zent/src/date-picker/utils/getPanelCellsData.ts
=> bugfix: 修复周选择hover范围样式

packages/zent/src/upload/components/AbstractTrigger.tsx, packages/zent/src/upload/components/AbstractUpload.tsx, packages/zent/src/upload/types.ts, packages/zent/src/utils/promise-queue.ts
=> [bugfix] Upload: 修复上传文件时文件顺序变化的 bug

packages/zent/assets/radio.scss
=> update radio right margin to 24px

packages/zent/src/form/Field.tsx, packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/demos/8.field-array.md, packages/zent/src/form/demos/9.model-first.md, packages/zent/src/form/formulr/builders/field.ts, packages/zent/src/form/shared.tsx
1. Add `normalizeBeforeSubmit` in view mode
2. Fix runtime error when using `normalizeBeforeSubmit` in model builder
=> support normalizeBeforeSubmit in view mode

packages/zent/src/form/form-components/NumberInputField.tsx
=> bugfix: FormNumberInputField类型修改

packages/zent/assets/pop.scss, packages/zent/src/pop/Action.tsx, packages/zent/src/pop/Pop.tsx
Pop
- `IPopActionCallback` 定义修改
- `confirm` 形式按钮样式调整为块级显示
=> bugfix: Pop组件IPopActionCallback类型定义修改，按钮样式优化

packages/zent/assets/date-picker.scss, packages/zent/src/date-picker/index.ts, packages/zent/src/date-picker/panels/combined-date-range-panel/index.tsx, packages/zent/src/date-picker/panels/date-panel/DateBody.tsx, packages/zent/src/date-picker/panels/date-panel/index.tsx, packages/zent/src/date-picker/types.ts, packages/zent/src/date-picker/utils/getPanelCellsData.ts
DatePicker
- 修复范围组件hover和selected样式
- 导出类型 `IValueTypeRangeMap`
=> DatePicker 样式修改 && 增加类型导出

packages/zent/src/form/formulr/value-listener.tsx
FieldSetValue
- FieldSetValue 中增加传入model属性.因为 FieldSet当中允许传入name 和 model 会导致 FieldSetValue无法从model获取值
=> fix:  fieldSetValue支持传入model

packages/zent/assets/date-picker.scss, packages/zent/src/date-picker/components/CombinedPickerBase.tsx, packages/zent/src/date-picker/constants/index.ts
DatePicker
- 修复当修改 `CombinedDateRangePicker` 的 `disabled` 属性后，样式没有更新的问题
- 修复 `DatePicker` 没有设置背景色的问题
=> [Bug Fix] DatePicker: 添加背景色 & 修复日期范围选择组件更新 disabled 参数，样式未更新

packages/zent/assets/radio.scss
=> [bug fix]: RadioButton 文字居中

packages/zent/assets/date-picker.scss, packages/zent/src/date-picker/components/PickerPopover.tsx
=> fix: datePicker-popup层级修改

packages/zent/src/dialog/Dialog.tsx
- fix Dialog animation issue using react17
=> fix Dialog animation issue using react17

packages/zent/assets/date-picker.scss
=> [BugFix]: DatePicker 仅输入框添加背景色

packages/zent/assets/date-picker.scss, packages/zent/src/date-picker/components/CombinedPickerBase.tsx, packages/zent/src/date-picker/components/CombinedTimePicker.tsx, packages/zent/src/date-picker/components/PickerTrigger.tsx, packages/zent/src/date-picker/components/SinglePickerBase.tsx, packages/zent/src/date-picker/components/TimePickerBase.tsx
DatePicker
- `disabled` 样式失效修复
=> [bugfix]: DatePicker disabled失效

packages/zent/src/date-picker/index.ts, packages/zent/src/form/form-components/CombinedDateRangePickerField.tsx, packages/zent/src/form/form-components/CombinedTimeRangePickerField.tsx, packages/zent/src/form/form-components/DatePickerField.tsx, packages/zent/src/form/form-components/DateRangePickerField.tsx, packages/zent/src/form/form-components/DateRangeQuickPickerField.tsx, packages/zent/src/form/form-components/MonthPickerField.tsx, packages/zent/src/form/form-components/QuarterPickerField.tsx, packages/zent/src/form/form-components/TimePickerField.tsx, packages/zent/src/form/form-components/TimeRangePickerField.tsx, packages/zent/src/form/form-components/WeekPickerField.tsx, packages/zent/src/form/form-components/YearPickerField.tsx
FormDatePickerField
-  `defaultValue` 取值逻辑修改
-  `props` 类型修改
=> [bugfix]: 修复FormDatePickerField 属性`defaultValue`不生效、修复类型校验异常

packages/zent/src/tabs/README_en-US.md, packages/zent/src/tabs/README_zh-CN.md, packages/zent/src/tabs/Tabs.tsx, packages/zent/src/tabs/types.ts
Tabs
- 增加 `disabledLazyMount` 属性，用于禁用`tabPanel` lazyMount行为
=> [feature]: tabs组件 禁用`tabPanel` lazyMount

packages/zent/src/form/formulr/value-listener.tsx
=> fix a typo in form value-listener

packages/zent/assets/loading.scss, packages/zent/src/alert/demos/loading.md
=> fix alert loading style in nested loading

packages/zent/src/select/Select.tsx
Select bugfix:
- 修复select搜索场景使用键盘翻页定位异常问题
=> bugfix: 修复select搜索场景使用键盘翻页定位异常问题

packages/zent/__tests__/cascader.js, packages/zent/__tests__/clamp-lines.js, packages/zent/src/affix/Affix.tsx, packages/zent/src/clamp-lines/ClampLines.tsx, packages/zent/src/clamp-lines/README_en-US.md, packages/zent/src/clamp-lines/README_zh-CN.md, packages/zent/src/clamp-lines/demos/extra.md, packages/zent/src/clamp-lines/demos/resizable.md, packages/zent/src/clamp-lines/demos/update-text.md, packages/zent/src/utils/hooks/use-resize-observer.ts
Use `ResizeObserver` if available and fallback to `resize` event on `Window`.
=> [ClampLines] react to container resize

packages/zent/assets/cascader.scss, packages/zent/assets/select.scss, packages/zent/src/select/Select.tsx
Fixes #1509 
- 修改 `Select` caret-down 样式
- 修改 `Cascader` caret-down 样式
=> Cascader组件与Select组建下拉三角形不一样大小 #1590

packages/zent/assets/dialog.scss, packages/zent/src/dialog/Dialog.tsx, packages/zent/src/dialog/DialogEl.tsx, packages/zent/src/dialog/demos/content-only.md, packages/zent/src/dialog/demos/context.md, packages/zent/src/dialog/demos/no-header.md, packages/zent/src/dialog/demos/open.md, packages/zent/src/utils/nextFrame.ts
- Auto fit content size with min and max height/width
- Scroll content if exceeds max height
=> Update Dialog style 

packages/zent/__tests__/steps.js, packages/zent/assets/steps.scss, packages/zent/src/steps/components/BreadcrumbSteps.tsx, packages/zent/src/steps/components/Step.tsx
1. Prefix css class name with zent-steps
2. Update colors
=> Update steps styles

packages/zent/src/select/README_en-US.md, packages/zent/src/select/README_zh-CN.md, packages/zent/src/select/Select.tsx
Select new feature:
- 增加 `disableSearch` 属性，禁用默认搜索功能
=> feat: Select增加disableSearch属性 禁用搜索

packages/zent/src/tabs/components/tabs-nav/OperationTabs.tsx
Tabs:
- `Tabs` 开启 `overflowMode` 但 `tabs`数量少时，隐藏操作区域
- 调整内部开始/结束节点的计算逻辑
=> bugifx: 修复Tabs `overflow类型的操作不正常显示问题，调整内部节点的计算逻辑

packages/zent/src/pagination/components/PageSizeChanger.tsx
- pagination 分页select添加 `条` 文案
=> fix: pagination 分页select添加 条 文案

packages/zent/RELEASE_v9.md, packages/zent/package.json
=> release v9.0.0-beta.25

packages/zent/src/select/README_en-US.md, packages/zent/src/select/README_zh-CN.md, packages/zent/src/select/Select.tsx
- select组件添加 hideCollapsePop 字段隐藏折叠数据气泡
=> feat: 添加hideCollapsePop

packages/zent/src/select/README_en-US.md, packages/zent/src/select/README_zh-CN.md, packages/zent/src/select/Select.tsx, packages/zent/src/select/index.ts
=> Support custom tag list render in multiple mode

packages/zent/src/grid/Grid.tsx
=> fix: 修复表头分组场景下浮动列表头高度问题 v8

packages/zent/src/grid/Grid.tsx
=> fix: 修复表头分组场景下浮动列表头高度问题 master

packages/zent/src/form/form-components/SelectField.tsx, packages/zent/src/select/Option.tsx, packages/zent/src/select/Select.tsx, packages/zent/src/select/Tag.tsx, packages/zent/src/select/TagList.tsx, packages/zent/src/select/reviver.ts
=> [bugfix]: Select 组件泛型类型修改

packages/zent/src/form/Form.tsx
Use `willScrollToError` to set custom scroll offset.
=> support custom scroll offset in Form

packages/zent/src/grid/Grid.tsx
- getColumns时，使用nextProps.selection计算checkbox相关
=> [bugfix]: Grid 纠正selection.getCheckboxProps处理逻辑

packages/zent/src/date-range-quick-picker/DateRangeQuickPicker.tsx
- 修复DateRangeQuickPicker min、max不生效问题
=> [bugfix] 修复DateRangeQuickPicker min、max不生效问题

packages/zent/__tests__/cascader.js, packages/zent/src/cascader/MenuCascader.tsx, packages/zent/src/cascader/README_en-US.md, packages/zent/src/cascader/README_zh-CN.md, packages/zent/src/cascader/TabsCascader.tsx, packages/zent/src/cascader/components/MenuContent.tsx, packages/zent/src/cascader/components/SearchContent.tsx, packages/zent/src/cascader/demos/14.simplify.md, packages/zent/src/cascader/simplify.ts, packages/zent/src/cascader/trigger/Tags.tsx, packages/zent/src/cascader/trigger/TagsTrigger.tsx, packages/zent/src/cascader/types.ts
1. Add `simplifySelection` in `MenuCascader`
2. Remove `changeOnSelect` from `MenuCascader` props interface
=> support selection simplify in MenuCascader

packages/zent/src/form/demos/1.basic.md, packages/zent/src/form/formulr/models/array.ts, packages/zent/src/form/formulr/models/base.ts, packages/zent/src/form/formulr/models/basic.ts, packages/zent/src/form/formulr/models/field.ts, packages/zent/src/form/formulr/models/ref.ts, packages/zent/src/form/formulr/models/set.ts
=> [new feature] Form: 增加clearError

packages/zent/src/select/Search.tsx
=> extract select search input keyboard handler

packages/zent/src/select/README_en-US.md, packages/zent/src/select/README_zh-CN.md, packages/zent/src/select/Select.tsx
Add `meta` to `Select`'s `onKeywordChange`
=> Select keyword change meta

packages/zent/assets/button.scss, packages/zent/src/button/Button.tsx, packages/zent/src/pop/demos/disabled.md
Button :
- remove surplus disable button's wrapper
=> Remove surplus disable button's wrapper

packages/zent/src/button/Directive.tsx, packages/zent/src/button/utils.tsx, packages/zent/src/pop/Pop.tsx, packages/zent/src/pop/README_en-US.md, packages/zent/src/pop/README_zh-CN.md, packages/zent/src/pop/demos/disabled.md, packages/zent/src/popover/README_en-US.md, packages/zent/src/popover/README_zh-CN.md, packages/zent/src/popover/trigger/HoverTrigger.tsx, packages/zent/src/tooltip/README_en-US.md, packages/zent/src/tooltip/README_zh-CN.md, packages/zent/src/tooltip/Tooltip.tsx, packages/zent/src/tooltip/demos/disabled.md
`fixTooltipOnDisabledChildren ` => `fixMouseEventsOnDisabledChildren `
=> rename to fixMouseEventsOnDisabledChildren

packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/index.ts, packages/zent/src/form/shared.tsx
=> export useFormChild

packages/zent/src/cascader/MenuCascader.tsx, packages/zent/src/cascader/demos/15.async-options.md
=> fix async options loading in cascader

packages/zent/src/upload/README_en-US.md, packages/zent/src/upload/README_zh-CN.md, packages/zent/src/upload/SingleUpload.tsx, packages/zent/src/upload/components/AbstractMultiUpload.tsx, packages/zent/src/upload/components/AbstractUpload.tsx, packages/zent/src/upload/components/normal/List.tsx, packages/zent/src/upload/demos/pagination.md, packages/zent/src/upload/types.ts, packages/zent/src/upload/utils/default-image-props.ts
- 修改 getUploadSuccessOverrideProps 实现，默认直接返回入参而不是返回一个空对象
- 修复一些代码和文档中的拼写问题
=> [Upload] bugfix: 修复 onUpload 返回值不会覆盖到 item 上的问题

packages/zent/src/upload/components/AbstractUpload.tsx
- 修改 getUploadSuccessOverrideProps 默认实现
=> bugfix: [Upload] 修复 onUpload 返回的 Promise resolve 属性不覆盖的问题

packages/zent/package.json, packages/zent/src/form/README_zh-CN.md, yarn.lock
1. Update @wojtekmaj/enzyme-adapter-react-17 to 0.5.0
2. Add form field `props` doc
=> update @wojtekmaj/enzyme-adapter-react-17 to 0.5.0

packages/zent/src/form/demos/9.model-first.md, packages/zent/src/form/form-components/ImageUploadField.tsx, packages/zent/src/form/form-components/InputField.tsx, packages/zent/src/form/form-components/UploadField.tsx, packages/zent/src/form/formulr/models/array.ts, packages/zent/src/form/formulr/models/set.ts, packages/zent/src/form/formulr/utils.ts, packages/zent/src/form/formulr/warnings.ts, packages/zent/src/form/utils.ts, packages/zent/src/number-input/integer.ts, packages/zent/src/upload/components/AbstractMultiUpload.tsx, packages/zent/src/utils/style/warnValidStyle.ts, packages/zent/src/utils/warning.ts, packages/zent/src/utils/warningOnce.ts
- Refactor `warning` related code
- Fix crash in form field default value warnings
- Fix bugs in form model first demo
=> fix form field warnings

packages/zent/src/form/FieldSet.tsx, packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/ZentForm.tsx, packages/zent/src/form/formulr/validate.ts
=> update form API doc

packages/zent/src/infinite-scroller/InfiniteScroller.tsx
Some scenes would get scroller wrapper ref, eg: we need get scroller wrapper ref to compute element height and add scroll event listener when InfiniteScroller and VirtualList are used in combination.
=> fix(InfiniteScroller): support ref

packages/zent/src/button/Directive.tsx, packages/zent/src/popover/trigger/ClickTrigger.tsx, packages/zent/src/popover/trigger/FocusTrigger.tsx, packages/zent/src/popover/trigger/HoverTrigger.tsx
=> add fragment check in ButtonDirective and Popover triggers

packages/zent/src/grid/README_en-US.md, packages/zent/src/grid/README_zh-CN.md
=> update Grid doc

packages/zent/src/menu/Menu.tsx, packages/zent/src/menu/README_en-US.md, packages/zent/src/menu/README_zh-CN.md, packages/zent/src/menu/SubMenu.tsx, packages/zent/src/menu/demos/inline-selected.md
=> add controlled mode for inline menu

packages/zent/src/upload/ImageUpload.tsx, packages/zent/src/upload/SingleUpload.tsx, packages/zent/src/upload/Upload.tsx, packages/zent/src/upload/components/AbstractList.tsx, packages/zent/src/upload/components/AbstractMultiUpload.tsx, packages/zent/src/upload/components/AbstractUpload.tsx, packages/zent/src/upload/components/image/Item.tsx, packages/zent/src/upload/components/image/List.tsx, packages/zent/src/upload/components/normal/Item.tsx, packages/zent/src/upload/components/normal/List.tsx, packages/zent/src/upload/components/single/Item.tsx, packages/zent/src/upload/demos/manual.md, packages/zent/src/upload/types.ts, packages/zent/src/upload/utils/create-new-upload-file-item.ts, packages/zent/src/upload/utils/id.ts
- 公开 Upload 组件文件项的 id 和 file 属性，使非回调函数中的数据也可以访问到文件信息
=> feat: 公开 Upload 组件文件项的 id 和 file 属性

packages/zent/src/grid/Grid.tsx, packages/zent/src/grid/demos/selection.md
fix: 修复Grid组件切换selection传值显示bug
- 对原功能无影响，传入selection对象则展示复选框
- 如果selection属性从对象变为undefined，则取消掉复选框
=> fix: 修复Grid组件切换selection传值显示bug

packages/zent/src/number-input/demos/5.event-handler.md
=> fix NumberInput demo

packages/zent/src/dialog/README_en-US.md, packages/zent/src/dialog/README_zh-CN.md, packages/zent/src/dialog/demos/open.md
=> add close dialog demo using return value of openDialog

packages/zent/src/form/Form.tsx, packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/demos/12.preview.md, packages/zent/src/form/formulr/listeners/array.ts
=> rename useFieldArrayValue to useFieldArrayChildModels

packages/zent/package.json
=> remove postcss-plugin-constants from npm package

packages/zent/src/form/formulr/models/array.ts
- 修复 fieldArrayModel splice 无法插入数据问题
=> fix: 修复 fieldArrayModel splice 无法插入数据问题

packages/zent/assets/form.scss, packages/zent/package.json, packages/zent/scripts/check-deadlink.js, packages/zent/src/form/Field.tsx, packages/zent/src/form/Form.tsx, packages/zent/src/form/README_en-US.md, packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/ZentForm.tsx, packages/zent/src/form/demos/13.interact.md, packages/zent/src/form/demos/15.submit.md, packages/zent/src/form/demos/3.multi-value.md, packages/zent/src/form/demos/7.layout.md, packages/zent/src/form/formulr/error.ts, packages/zent/src/form/formulr/field-utils.ts, packages/zent/src/form/formulr/models/array.ts, packages/zent/src/form/formulr/models/field.ts, packages/zent/src/form/formulr/validate.ts, packages/zent/src/form/index.ts, yarn.lock
1. Add form control layout direction support
2. Fix broken API doc links
3. Rename `makeChangeHandler` to `useChangeHandler` because it's actually a React hook
4. Improve validator runtime error
Fixes #1760 
Fixes #1757 
Fixes #1756
=> Form bug fixes

packages/zent/src/form/Control.tsx, packages/zent/src/form/README_zh-CN.md, packages/zent/src/form/context.tsx, packages/zent/src/form/demos/7.layout.md
1. Add `controlStyle` support in `FormContext`
=> support control style in FormContext

.github/workflows/check-deadlink.yml, packages/zent/package.json, packages/zent/scripts/check-deadlink.js, yarn.lock
=> Automated deadlink check

packages/zent/src/pagination/components/button/ArrowButton.tsx, packages/zent/src/pagination/components/jumper/MiniPageJumper.tsx, packages/zent/src/pagination/components/jumper/PageJumper.tsx, site/webpack/webpack.dev.config.js
1. Fix `MiniPagination` not reacting to `props.current` change
2. Fix `lastPageHelp` not working
=> fix MiniPagination and lastPageHelp bugs

package.json, packages/zent/jest.config.json, packages/zent/package.json, packages/zent/scripts/build-ts.sh, packages/zent/tsconfig.webpack.json, site/webpack/webpack.config.js, yarn.lock
Switching to [`ts-patch`](https://github.com/nonara/ts-patch) since `ttypescript` is not actively maintained.
=> replace ttypescript with ts-patch

.github/workflows/update-caniuse-db.yml, packages/zent/tsconfig.base.json, packages/zent/tsconfig.json, packages/zent/tsconfig.webpack.json
- Cleanup `tsconfig.json` files
- Uninstall husky hooks in `caniuse-lite` github action
=> update configs for github actions

packages/zent/assets/cascader.scss, packages/zent/assets/select.scss, packages/zent/src/cascader/trigger/BaseTrigger.tsx, packages/zent/src/select/Select.tsx
=> replace caret-down with down in Select and Cascader

packages/zent/src/grid/BatchComponents.tsx, packages/zent/src/grid/Grid.tsx, packages/zent/src/grid/SelectionCheckboxAll.tsx, packages/zent/src/grid/types.ts, packages/zent/src/grid/utils.ts
Fix wrong state in select all checkbox when all rows are disabled.
Fixes #1797
=> fix select all checkbox state in Grid

packages/zent/src/grid/Body.tsx, packages/zent/src/grid/Grid.tsx, packages/zent/src/grid/Header.tsx, packages/zent/src/grid/Row.tsx, packages/zent/src/grid/Store.ts
=> fix fixed grid row highlight without scroll

packages/zent/src/notify/Notify.tsx
=> fix: notify相关类型完善

.github/workflows/release.yml
=> remove wechat bot

packages/zent/__tests__/progress.spec.jsx, packages/zent/assets/progress.scss, packages/zent/src/progress/Progress.tsx, packages/zent/src/progress/README_en-US.md, packages/zent/src/progress/README_zh-CN.md, packages/zent/src/progress/components/CircleProgress.tsx, packages/zent/src/progress/components/LineProgress.tsx, packages/zent/src/progress/components/ProgressInfo.tsx, packages/zent/src/progress/demos/circle.md, packages/zent/src/progress/demos/custom-color.md, packages/zent/src/progress/demos/dynamic.md, packages/zent/src/progress/demos/format.md, packages/zent/src/progress/demos/info.md, packages/zent/src/progress/demos/line-cap.md, packages/zent/src/progress/demos/size.md, packages/zent/src/progress/demos/status.md, packages/zent/src/progress/types.ts
- ✨ 进度条边缘样式支持配置为 `round`、`square`，默认为`round`
- 🦀️ 默认宽度及 Icon 尺寸调整
- 📚 环形进度条代码演示移入废弃区，新版设计语言已不再使用
=> V10 progress

packages/zent/assets/collapse.scss, packages/zent/assets/theme/_timing-functions.scss, packages/zent/src/collapse/Collapse.tsx, packages/zent/src/collapse/Panel.tsx, packages/zent/src/collapse/README_en-US.md, packages/zent/src/collapse/README_zh-CN.md, packages/zent/src/collapse/demos/accordion.md, packages/zent/src/collapse/demos/basic.md, packages/zent/src/collapse/demos/no-border.md, packages/zent/src/collapse/demos/show-content-bg.md, packages/zent/src/utils/component/AnimateHeight.tsx, packages/zent/src/utils/timingFunctions.ts
- ✨  支持标题自定义内容
- 🦀️  折叠箭头 Icon 调整为 ZentIcon
- 🦀️  标题间距、颜色调整
- 🦀️  分割线颜色调整，展开/收起时边框调整
- 📚 有边框及无箭头样式演示移入废弃区，新版设计语言已不再使用
=> V10 collapse

packages/zent/assets/slider.scss, packages/zent/src/slider/README_en-US.md, packages/zent/src/slider/README_zh-CN.md, packages/zent/src/slider/Slider.tsx, packages/zent/src/slider/demos/disable.md, packages/zent/src/slider/demos/single-label.md
- 🦀️  样式修改，修改 hover 和 active 时滚动点的边框大小
- 📚  双滑块的 demo 移入废弃区，新版设计语言已不再使用
=> V10 slider

packages/zent/src/select/Select.tsx, packages/zent/src/select/demos/10.creatable.md, packages/zent/src/select/demos/4.multiple.md
- ✨ 内部实现创建条目方法，原来是通过传入的`onCreate`修改`options`实现，现在是内部处理新增`options`的逻辑
=> V10 Multi Select

packages/zent/assets/error-boundary.scss, packages/zent/assets/sweetalert.scss, packages/zent/package.json, packages/zent/scripts/generate-icon-grid.js, packages/zent/src/error-boundary/Fallback.tsx, packages/zent/src/icon/demos/all.md, packages/zent/src/notice/Notice.tsx, packages/zent/src/notify/NotifyContent.tsx, packages/zent/src/sweetalert/constants.ts, yarn.lock
=> fix: [Icon]更新 warning icon

packages/zent/src/select/Select.tsx
- `Select`
- 🦀️ 修复 getExtraOption 函数中取值时可能报错的问题
- 🦀️ 修复创建条目时，没有显示 option 的问题
=> fix: [Select]修复代码可能报错的问题，优化部分逻辑

packages/zent/src/input/Input.tsx, packages/zent/src/input/README_en-US.md, packages/zent/src/input/README_zh-CN.md
=> fix: [input]去掉widthSize默认值

packages/zent/__tests__/disabled.spec.jsx, packages/zent/assets/button.scss, packages/zent/src/button/Directive.tsx, packages/zent/src/button/utils.tsx
- `Button`
- 🦀 不改变 dom 结构情况下支持 button disabled 情况下显示 cursor
=> fix: 不改变dom结构情况下支持button disabled情况下显示cursor

packages/zent/assets/number-input.scss, packages/zent/src/select/README_en-US.md, packages/zent/src/select/README_zh-CN.md, packages/zent/src/select/Select.tsx
=> fix: [select]去掉size默认值

packages/zent/src/select/README_en-US.md, packages/zent/src/select/README_zh-CN.md, packages/zent/src/select/Select.tsx
- `Select`
- 🦀 保持 `size` 宽度默认值 240px 
revert #1926
=> fix: select保持默认值240px

packages/zent/src/grid/Grid.tsx, packages/zent/src/grid/README_en-US.md, packages/zent/src/grid/README_zh-CN.md, packages/zent/src/grid/demos/expand.md, packages/zent/src/grid/types.ts
- `Grid`
-  ✨ `expandation` 中新增 `isExpandable` API，支持配置可展开图标显示 #1895
=> feat(Grid): 支持是否显示可展开图标

packages/zent/src/input/InputCore.tsx
- `input`
- ✨ 增加`iconPosition`来确定`icon`的位置
- ✨ 有交互的`icon`点击和hover有背景色
=> fix(input): 修复合并时丢失的代码

packages/zent/src/cascader/trigger/BaseTrigger.tsx
Feature v9.12.8
- Cascader
- ✨ 当配置了 searchable 时，也支持了placeholder
=> feat(Cascader) ：当配置了 searchable 时，也支持了placeholder

packages/zent/__tests__/dialog/Dialog.spec.jsx, packages/zent/src/dialog/Dialog.tsx, packages/zent/src/dialog/DialogEl.tsx, packages/zent/src/dialog/README_en-US.md, packages/zent/src/dialog/README_zh-CN.md, packages/zent/src/dialog/position.ts
- [FIX]：修复弹窗自动打开与关闭位置不一致问题
- [FEATURE]：Dialog组件支持通过 `position ` 指定弹窗打开位置
- 默认 `auto` 自动选择打开位置
- 可选值 `center` 从屏幕中心打开
=> feature(dialog)：add position prop support

packages/zent/src/indicator/Indicator.tsx
- IIndicatorProps引用从IStepProps修改为IStepsProps
=> hotfix(indicator): fix props type import from steps

packages/zent/__tests__/notify.spec.jsx, packages/zent/assets/notify.scss, packages/zent/src/notify/Notify.tsx, packages/zent/src/notify/README_en-US.md, packages/zent/src/notify/README_zh-CN.md, packages/zent/src/notify/demos/custom-container-selector.md, packages/zent/src/notify/demos/global-container-selector.md
- Notify调用方法新增containerSelector入参修改组件挂载节点
- Notify调用方法新增className入参自定义组件顶层节点类名
- Notify的config支持全局containerSelector配置
=> feat(notify)：add containerSelector and className prop support

packages/zent/src/grid/Grid.tsx
- 修复Grid组件在渲染Selection和Expand时可能会出现的重复项问题
=> fix(grid): duplicate columns render limited

packages/zent/assets/form.scss
=> fix(form): required style of form item was invalid

packages/zent/src/grid/Row.tsx
- change the key of cell in gird component with column name and index
=> fix(grid): fix the key of cell in grid component to rerender correctly

packages/zent/src/cascader/components/MenuContent.tsx
=> fix(Cascader): 兼容不存在option导致的组件报错

packages/zent/package.json, packages/zent/src/icon/demos/all.md, yarn.lock
增加的 icon 列表
- xiaohongshu
- xiaohongshu-fill
=> feat(Icons): update icons
