- packages/zent-form/examples/async_validation.js
- packages/zent-form/examples/fieldset.js
- packages/zent-form/examples/form_fields.js
- packages/zent-form/examples/form_level_validation_rules.js
- packages/zent-form/examples/format_and_normalize.js
- packages/zent-form/examples/input_file.js
- packages/zent-form/examples/overview.js
- packages/zent-form/examples/submit_validation.js
- packages/zent-form/src/index.js
以后可以写成
import { Form } from 'zent';
const { Field, createForm } = Form;
然后直接在render中使用Form组件即可
不需要再写成
import { Form } from 'zent';
const { Form as ZentForm, Field, createForm } = Form;
> 修改form导出方式

- packages/zent-form/CHANGELOG.md
- packages/zent-form/README.md
- packages/zent-form/__tests__/GetControlGroup-Component_Fields.js
- packages/zent-form/assets/index.scss
- packages/zent-form/src/Field.js
- packages/zent-form/src/getControlGroup.js
* Field 中增加 onFocus 回调，并添加 focus 时的 active state
* getControlGroup 改为返回一个 class 类型的 React Component, 增加 field active 时对应的类 `zent-form__control-group--active`，增加 `getControlInstance` 方法。
> add onFocus callback & add field active state & update control group

- packages/zent-sweetalert/__tests__/spec.js
- packages/zent-sweetalert/examples/01-simple.js
- packages/zent-sweetalert/src/index.js
Sweetalert 按钮在回调函数返回Promise，并且Promise被reject的时候停止loading
> Sweetalert stop button loading on promise rejection

- packages/zent-dialog/assets/zent-dialog.scss
现在居中是用 `vertical-align` 做的，在 `Dialog` 宽度大于屏幕宽度时行内元素会换行，导致下移。
> 修复 Dialog 宽度大于屏幕宽度时移位的问题。

- packages/zent-steps/examples/number.js
- packages/zent-steps/src/components/Step.js
- 修复步骤条展示问题 ，现在的问题是所有的项都是成功的图标，修改后前几项以数字标识
> 修复 steps 组件状态为成功时，前面的子项以数字显示

- packages/zent-popover/__tests__/index.js
- packages/zent-popover/src/trigger/HoverTrigger.js
React's `onBlur` bubbles while native event doesn't. This causes popover to close unexpectedly in some circumstances.
Related React issue: https://github.com/facebook/react/issues/6410
> Popover: ensure window.onblur's target is window in Popover hover trigger

- packages/babel-plugin-zent/package.json
- packages/babel-plugin-zent/src/index.js
- packages/babel-plugin-zent/yarn.lock
slove [issue200](https://github.com/youzan/zent/issues/200), add below features
-  Transform import { Button } from 'zent' to import Button from 'zent/lib/button'. 
-  Error on import Button from 'zent-button'
-  Error on import Button from 'zent/button'
-  Error on import * as Zent from 'zent'
-  Error on const Zent = require('zent')
-  Error on const Alert = require('zent/alert')
> add babel plugin to transform zent import

- packages/zent/__tests__/loading.js
- packages/zent/src/loading/Loading.js
- packages/zent/src/loading/LoadingInstance.js
- packages/zent/src/loading/README.md
- site/src/components/PageHeader/style.pcss
1. Deprecate `static` in `Loading`, use `float`.
2. Fix style in doc page header.
> loading: change static to float

- packages/zent/src/tree/index.js
Fixes #323 
- tree组件dataType="plain"时，节点顺序与data数据不一致
> tree: fix dataType=plain data order unstable #323

- packages/zent/__tests__/colorpicker.js
- packages/zent/assets/colorpicker.pcss
- packages/zent/src/colorpicker/ColorBoard.js
- packages/zent/src/colorpicker/README.md
- packages/zent/src/colorpicker/SketchPresetColors.js
- packages/zent/src/colorpicker/index.js
1、修改color-picker样式
2、color-picker增加一个prop：type ，可选值为 'default' 和 'simple'，用于输出简化版颜色选择器。
> fix: colorpicker css fix & add props type

- packages/zent/src/pop/Pop.js
- packages/zent/src/pop/README.md
- packages/zent/src/popover/README.md
- packages/zent/src/popover/trigger/HoverTrigger.js
- Add a `quirk` mode to allow some pop interactions.
- `Pop` now uses `quirk` mode in its hover mode.
Fixes #340 
Related #142
> popover: Add quirk mode for popover

- packages/zent/src/portal/withNonScrollable.js
确保多个对话框非顺序关闭时body的overflow可以被正确设置回原来的值。
> portal: Add a count to support non sequential dialog closes

- packages/zent/assets/table.pcss
- packages/zent/src/table/modules/Foot.js
- fix table foot batch component border style
> table: only show boder when children rendered

- packages/zent/__tests__/loading.js
- packages/zent/src/loading/LoadingInstance.js
> loading: Fix bug in floating Loading without children

- packages/zent/src/form/Field.js
- packages/zent/src/form/README.md
- packages/zent/src/form/utils.js
Fixes #375 .
- form: use assign in onChange function of filed to avoid object being overlapping.
> fix: form自定义Field里调用this.props.onChange会将整个对象覆盖掉

- packages/zent/src/slider/inputField.js
`Slider` 给 `NumberInput` 多传了一个 `marks` 的 `props`，导致 `waring`。
> Slider: 修复Unknown prop `marks` on <input> tag waring

- packages/zent/__tests__/loading.js
- packages/zent/src/loading/Loading.js
- packages/zent/src/loading/LoadingInstance.js
Calling `Loading.off` immediately after `Loading.on` fails.
> Loading: Fix Loading.on/off not working

- packages/zent/src/form/createForm.js
- packages/zent/src/form/getControlGroup.js
当校验失败，同时校验规则没有对应的错误提示以及validationError为`""`时，getControllGroup 中 showError 开关表现为 false. 
通过改变showError的逻辑修复之.
Before this pr
```jsx
validations={{ required: true }}
validationErrors={{ required: '值不能为空' }}
```
```jsx
validations={{ required: true }}
validationErrors={{}}
```
After
```jsx
validations={{ required: true }}
validationErrors={{}}
```
> Field in Form: validationErrors与validationError置空时，校验出错误时的显示策略调整

- packages/zent/src/date-range-quick-picker/constants.js
- packages/zent/src/date-range-quick-picker/helper.js
DateRangeQuickPicker ： 快速筛选最近7天，end_time 值为当前时间，而不是前一天晚上11:59:59.
> [bug fix] DateRangeQuickPicker: 调整最近7天，使end_time包含到当前时间

- packages/zent/src/design/Design.js
`uninstallBeforeUnloadHook`函数内部，`addEventLisner` 修改成 `removeEventListener`
> [bug fix] Design: 在componentWillUnmount时，移除监听的beforeunload事件

- packages/zent/src/swiper/Swiper.js
> [bug fix] Swiper: 修复当只有一个子元素时的显示错误问题

- packages/zent/src/popover/Content.js
有时候 Trigger 的定位是 fixed 之类的，需要在滚动之后重新计算 Content 位置。
> [bug fix] Popover: 滚动的时候自动重新计算位置

- packages/zent/src/select/README.md
- packages/zent/src/select/Select.js
通过受控逻辑将Select的data置为空数组时，原本的selectedItem内部state不会被充值。
> [bug fix]Select：修复select在选项数组置空后选中项不会重置的bug

- packages/babel-plugin-zent/README.md
- packages/babel-plugin-zent/src/index.js
> [bug fix] babel-plugin-zent: 增加老版本 zent 的警告

- packages/zent/src/select/README.md
- packages/zent/src/select/Select.js
原本Select序列化输入数据的过程中，如果`data` prop类型为对象数组  会对其中的对象进行直接改写。
同时`optionValue`与`optionText`同时存在时, `optionText`值不起作用。
使用`lodash/cloneDeep`做数据拷贝修正了上述问题。
> [bug fix] Select: 修正select在格式化数据时会对data数组中对象进行操作的bug. 

- packages/zent/src/design/utils/component-group.js
> [bug fix] Design: 修复变量名

- packages/zent/__tests__/cascader.js
- packages/zent/src/cascader/Cascader.js
- packages/zent/src/cascader/README_en-US.md
- packages/zent/src/cascader/README_zh-CN.md
Fixes #546 
- [bug fix] Cascader: 参数 `value`、`options`、`title`不为数组时的兼容处理
- [breaking change] Cascader: 参数 `title` 默认值改为空数组，此时每一项tab显示 `标题` 两字
> [bug fix] Cascader: 参数 `value`、`options`、`title`不为数组时的兼容处理

- package.json
- packages/zent/.babelrc
- packages/zent/src/design/preview/DesignPreviewController.js
- yarn.lock
* Remove `babel-plugin-transform-react-constant-elements`, buggy as always.
* Prevent component select when click on delete button
> [bug fix] Design: Prevent component select when click on delete button

- packages/zent/__tests__/select.js
- packages/zent/src/number-input/README_zh-CN.md
- packages/zent/src/select/README_en-US.md
- packages/zent/src/select/README_zh-CN.md
- packages/zent/src/select/Select.js
- packages/zent/src/select/demos/array.md
- packages/zent/src/select/demos/callback.md
- packages/zent/src/select/demos/controlled.md
- packages/zent/src/select/demos/dynamic.md
- packages/zent/src/select/demos/tag.md
> [new feature] Select: 增加重置选项开关和重置选项文本设置选项。

- packages/zent/src/form/utils.js
由于当 `Field` 的 `component` 是 `stateless function` 时，无法获取到它的 `ref`，所以增加了这个判断逻辑。
> [bug fix] Form: scrollToError增加对Field的判断

- packages/zent/assets/loading.pcss
- packages/zent/src/loading/Loading.js
- packages/zent/src/loading/demos/wrapper-mode.md
- site/src/components/Loadable.js
Remove loading background when no children is supplied
Fixes #645
> [new feature] Loading: Remove loading background when no children is supplied

- site/react-template.jstpl
猜测 bug 是因为文档网站启用代码分割后, react-router 与 markdown 内容分开加载导致的.
通过在 ZentDocContainer 模板中增加了两个工具函数, 使用 React 的 ComponentDidMount 生命周期函数比较糙的 fix了这个问题.
#640 , fixed
> [bugfix]Doc-site: 修复文档网站带 hash 地址 anchor 滚动不正确的 bug.

- packages/zent/assets/select.pcss
- packages/zent/src/pop/Pop.js
- packages/zent/src/pop/README_en-US.md
- packages/zent/src/pop/README_zh-CN.md
- packages/zent/src/popover/Content.js
- packages/zent/src/popover/Popover.js
- packages/zent/src/popover/README_en-US.md
- packages/zent/src/popover/README_zh-CN.md
- packages/zent/src/select/Popup.js
- packages/zent/src/select/Select.js
- packages/zent/src/select/components/Search.js
> [bugfix]Select: 修复win7下部分浏览器的兼容性 bug, 使用 popover 的 autoPosition 模式

- packages/zent/src/select/Select.js
遗漏了一个 commit 在重构分支.. 
Popover 的 `onPositionReady` 属性现在只能挂载在 Popover 上.
> [bugfix]Select: 修复在修改 focus 逻辑后导致键盘事件失效的 bug.

- packages/zent/assets/design/components/image-ad/editor.pcss
- packages/zent/assets/notify.pcss
- packages/zent/src/notify/NotifyContent.js
- 更改Notify结构，增加了一层div，外层用于控制动画，内层用于显示内容
- 修改Notify消失时的动画，增加了max-height: 0，用于让下层消息平滑上移
> [bug fix] Notify：多个Notify消失时动画不平滑问题

- packages/zent/__tests__/loading.js
- packages/zent/src/loading/LoadingInstance.js
`on`, `off` and `newInstance` are no longer available on `Loading`. These methods are considered anti-patterns.
> [breaking change] Loading: Remove deprecated methods on/off/newInstance

- packages/zent/__tests__/form/CreateForm-Field.js
- packages/zent/__tests__/form/Utils.js
- packages/zent/src/form/Field.js
- packages/zent/src/form/utils.js
`onChange(event, {value: 'xxx'})` will use value instead of `event.target.value`. This is useful with custom components.
> [new fature] Form: Allow non stardard value in Field onChange and onBlur

- packages/zent/assets/datetimepicker.pcss
- packages/zent/src/datetimepicker/DatePicker.js
- packages/zent/src/datetimepicker/MonthPicker.js
- packages/zent/src/datetimepicker/QuarterPicker.js
- packages/zent/src/datetimepicker/TimePicker.js
- packages/zent/src/datetimepicker/WeekPicker.js
- packages/zent/src/datetimepicker/YearPicker.js
- packages/zent/src/datetimepicker/constants/index.js
1. Remove `onBlur` and `onFocus` from all date pickers
2. Handle `placeholder` correctly
> [bug fix] DatePicker: Remove onBlur and onFocus callback from date pickers

- packages/zent/src/number-input/NumberInput.js
修复光标定位删除到类似“.00”，对value的正则匹配，准许通过校验。
> 添加对value值“.XX”形式的正则校验

- packages/zent/__tests__/menu.js
- packages/zent/src/menu/Menu.js
- packages/zent/src/menu/README_en-US.md
- packages/zent/src/menu/README_zh-CN.md
- packages/zent/src/menu/SubMenu.js
- packages/zent/src/menu/SubPopupMenu.js
- packages/zent/typings/libs/Menu.d.ts
- packages/zent/typings/libs/Select.d.ts
menu 组件添加2个 optional 的事件回调:
1. SubMenu 展开/折叠回调 `onExpandChange(expandedIds: string[]) => void`
2. SubMenu 被点击时回调 `onSubMenuClick(subMenuId: string) => void`
> [new feature] menu 组件添加两个事件回调

- packages/zent/assets/datetimepicker.pcss
- packages/zent/src/datetimepicker/DatePicker.js
- packages/zent/src/datetimepicker/DateRangePicker.js
- packages/zent/src/datetimepicker/MonthPicker.js
- packages/zent/src/datetimepicker/QuarterPicker.js
- packages/zent/src/datetimepicker/README_en-US.md
- packages/zent/src/datetimepicker/TimePicker.js
- packages/zent/src/datetimepicker/TimeRangePicker.js
- packages/zent/src/datetimepicker/WeekPicker.js
- packages/zent/src/datetimepicker/YearPicker.js
- packages/zent/src/datetimepicker/demos/basic.md
- packages/zent/src/datetimepicker/demos/disabled-time.md
- packages/zent/src/datetimepicker/time/TimeCell.js
- packages/zent/typings/libs/DateTimePicker.d.ts
feat:
时间选择器支持disable函数来禁用特定时间的选择 #920 
bugfix:
1、DatePicker canClear 为 `false` 时，hover上去 icon 的显示问题 
2、DateRangePicker disabledTime函数传入"start"/"end"参数
> [new feature] 时间选择器支持disable函数来禁用特定时间的选择

- packages/zent/src/datetimepicker/time/TimePanel.js
Fixes #926, 在设定最大值（max）之后，修复分秒disable显示不正确的问题。
> [bug fix] DateTimePicker：在设定最大值（max）之后，修复分秒disable显示不正确的问题。

- packages/babel-plugin-zent/README_en-US.md
- packages/babel-plugin-zent/README_zh-CN.md
- packages/babel-plugin-zent/__tests__/index.js
- packages/babel-plugin-zent/src/index.js
- packages/zent/package.json
- packages/zent/scripts/build.sh
- packages/zent/src/copy-button/CopyToClipboard.js
- packages/zent/src/upload/utils/file-type/index.js
Add `noModuleRewrite` option to work with es modules.
Tree shaking automatically removes unused components so we don't have to rewrite module imports.
> Support tree shaking in babel-plugin-zent

- packages/zent/assets/upload.pcss
> [bug fix] Upload：修复音频多个时样式错误

- packages/zent/src/form/README_en-US.md
- packages/zent/src/form/README_zh-CN.md
- packages/zent/src/form/SubmissionError.js
- packages/zent/src/form/handleSubmit.js
修复 `handleSubmit` 会吞掉非 `SubmissionError` 类型的错误的问题。
Fixes #939
> [bug fix] Form: throw errors in form submit

- packages/zent/src/dialog/demos/basic.md
[bug fix] Dialog：修改Dialog组件demo/basic.md中js demo的缩进问题
- packages/zent/src/dialog/demos/basic.md
> fix js indentation of packages/zent/src/dialog/demos/basic.md

- packages/zent/src/table/README_en-US.md
- packages/zent/src/table/README_zh-CN.md
- packages/zent/src/table/Table.js
- packages/zent/src/table/demos/indeterminate.md
- packages/zent/src/table/demos/selection.md
- packages/zent/src/table/modules/Body.js
- packages/zent/src/table/modules/Td.js
- packages/zent/typings/libs/Table.d.ts
- support render indeterminate status in Table's checkbox via pass `indeterminatedRowKeys` which should be maintained by users
- add related demo
> [new feature] Table: support render indeterminate status in checkbox

- packages/zent/src/form/createForm.js
[bug fix] Form: 修复 asyncValidation 结果处理对后续校验的影响
- asyncValidation 的结果处理中，_externalError 的设置基于 Promise 是否被 rejected 来决定
> [bug fix] Form: 修复 asyncValidation 结果处理对后续校验的影响

- packages/zent/src/grid/Footer.tsx
- packages/zent/src/grid/Grid.tsx
- packages/zent/src/grid/README_en-US.md
- packages/zent/src/grid/README_zh-CN.md
- packages/zent/src/grid/demos/selection.md
- packages/zent/src/table/Table.tsx
- packages/zent/src/table/demos/batch.md
- packages/zent/src/table/demos/indeterminate.md
- packages/zent/src/table/demos/selection.md
- packages/zent/src/table/modules/Foot.tsx
Add `paginationType` to `Table` and `Grid`
> feat: support pagination type in Table and Grid

- .lintstagedrc
- packages/zent/src/auto-complete/AutoComplete.tsx
- packages/zent/src/select-menu/MenuList.tsx
- packages/zent/src/select-menu/MenuListItem.tsx
- packages/zent/src/select-menu/SelectMenu.tsx
More typings and code clean up, no functionality changes.
> refactor: clean up SelectMenu

- packages/zent/src/grid/README_en-US.md
- packages/zent/src/grid/README_zh-CN.md
- packages/zent/src/grid/Row.js
- packages/zent/typings/libs/Grid.d.ts
报表中第一行为“合计”行时，需要替换第一行内第一单元格的文案。
但当同时存在右侧固定列时，会造成右侧固定列中第一行第一单元格也被替换。
因此需要识别当前调用 bodyRender 的列是否为右侧固定。
> [new feature] Grid: bodyRender 可获取到当前所在列的固定状态。

- packages/zent/src/date-range-quick-picker/DateRangeQuickPicker.js
- packages/zent/src/date-range-quick-picker/README_en-US.md
- packages/zent/src/date-range-quick-picker/README_zh-CN.md
- packages/zent/src/date-range-quick-picker/demos/preset.md
- packages/zent/src/date-range-quick-picker/helper.js
- packages/zent/typings/libs/DateRangeQuickPicker.d.ts
chooseDays 和 preset 目前只支持设置相对于今天的偏移量。
报表为非实时数据，需要按照一定周期选择时间范围。
如果周期为一天，则快捷选择的时间范围，就需要相对于昨天。
如果周期为一周，则快捷选择需要支持“上一周”的功能。
通过支持任意时间范围选择，即可覆盖此类需要设置绝对时间的场景。
> [new feature] DateRangeQuickPicker: 支持选择任意时间范围

- packages/zent/src/clamp-lines/ClampLines.tsx
- packages/zent/src/menu/SubMenu.tsx
#1060 
- 迁移```ClampLine```组件中的```componentWillReceiveProps```到```getDerivedStateFromProps```
- 迁移```Menu```组件中```SubMenu```的```componentWillReceiveProps```到```getDerivedStateFromProps```
- 补齐```Menu```组件中```SubMenu```的变量定义
> [refactor] ClampLine、Menu: 移除即将废弃的生命周期componentWillReceiveProps

- packages/zent/src/datetimepicker/DatePicker.tsx
- packages/zent/src/datetimepicker/MonthPicker.tsx
- packages/zent/src/datetimepicker/QuarterPicker.tsx
- packages/zent/src/datetimepicker/TimePicker.tsx
- packages/zent/src/datetimepicker/TimeRangePicker.tsx
- packages/zent/src/datetimepicker/WeekPicker.tsx
- packages/zent/src/datetimepicker/YearPicker.tsx
- packages/zent/src/datetimepicker/constants/index.ts
#1060 
- 迁移```DatePicker```中几个组件的```willReceiveProps```到```getDerivedStateFromProps```
- 移除了```defaultProps```中的```openPanel```，如果default中有这个值的话gdsfp中没法判断open是否是受控的。（虽然应该没人把openPanel设置成受控的）
- ```WeekPicker```改动比较大，因为要把耦合在类里的逻辑抽出来
> [refactor] DatePicker: 重构 willReceiveProps

- packages/zent/assets/upload.scss
[bug fix] Uploader: 屏幕分辨率过窄时，写死宽度会导致内容超出，需加上个max-width
> feat: fix uploader width overflow when screen width is narrow

- packages/zent/src/tabs/components/TabPanel.tsx
> Add missing props to TabPanel, a temporary workaround, needs rewrite

- packages/zent/src/loading/BlockLoading.tsx
`children` will re-mount if we remove the wrapper when mask is off.
> Wrap loading content with a div no matter loading or not

- packages/zent/RELEASE_NEXT.md
- packages/zent/__tests__/block-header.js
- packages/zent/assets/block-header.scss
- packages/zent/src/block-header/BlockHeader.tsx
- packages/zent/src/block-header/README_en-US.md
- packages/zent/src/block-header/README_zh-CN.md
- packages/zent/src/block-header/demos/basic.md
- packages/zent/src/tag/README_en-US.md
- packages/zent/src/tag/README_zh-CN.md
- 整体布局改为 flex 布局
- 删除 `content` 和 `childAlign`，改用 `leftContent` 和 `rightContent` 来控制左右侧额外展示的内容
- 不再渲染 `children` 中的内容
> [Refactor] BlockHeader

- packages/zent/src/pagination/components/button/ArrowButton.tsx
- 修复分页组件 double 属性传递到基础 react 元素上时 warning 信息报警
> [bugfix] Pagination: 修复分页组件 double 属性的 warning

- packages/zent/__tests__/tree.js
- packages/zent/src/tree/README_en-US.md
- packages/zent/src/tree/README_zh-CN.md
- packages/zent/src/tree/Tree.tsx
- packages/zent/src/tree/demos/option.md
- packages/zent/src/tree/index.ts
- packages/zent/src/tree/utils/common.ts
- packages/zent/src/tree/utils/correctExpand.ts
- packages/zent/src/tree/utils/correctMark.ts
- packages/zent/src/tree/utils/createStateByProps.ts
- packages/zent/src/tree/utils/getJudgeInfo.ts
[breaking change] Tree：check 模式重新实现并只保留受控模式
* check 模式移除了默认模式，仅保留受控模式
* check 模式的计算方式重新实现
```javascript
onCheck = (checked, helpInfo) => {
console.log(checked, helpInfo);
this.setState({
checkedKeys: checked,
});
}
<Tree
checkable
data={treeData}
onCheck={this.onCheck}
// defaultCheckedKeys={this.state.checkedKeys}
checkedKeys={this.state.checkedKeys}
disabledCheckedKeys={disabledCheckedKeys}
/>
```
1. 由于只保留受控制模，所以对选中入参名进行变更
**defaultCheckedKeys** => **checkedKeys**
2.  **onCheck**(checked, helpInfo) **onCheck** 将会接受两个参数
**checked**： 当前check操作后，所有被选中节点的id数组，
**helpInfo**： 用来帮助开发者做一些更自定义的选中操作
```javascript
interface IOncheckHelpInfo {
// 触发onCheck的节点
currentRoot: Node;
// 禁用节点集合
disabled: Node[];
//  所有选中的节点集合
all: Node[];
//  所有选中节点的祖先节点；即全选可能只有顶部节点
top: Node[];
// …
```
> fix: 重新实现check计算，并只保留受控模式break change

- packages/zent/src/upload/components/UploadPopup.tsx
getDerivedStateFromProps每次setState的时候也会触发，由于props的categoryId没改，而state的categoryId改了，导致一直无法设置categoryId。去除getDerivedStateFromProps也无所谓，因为props的categoryId改变时，UploadPopup早已销毁
> [bug fix] Upload:: 去除upload popup的getDerivedStateFromProps

- packages/zent/src/input/InputCore.tsx
- packages/zent/src/input/TextArea.tsx
fix a warning where 'inline' is passed to DOM mistakenly
> [input] fix warning

- packages/zent/assets/select.scss
Fix wrong `margin` and `padding` in Select
> Fix select tag style

- packages/zent/__tests__/table/combine.js
- packages/zent/assets/grid.scss
- packages/zent/src/grid/Grid.tsx
- packages/zent/src/table/Table.tsx
* [bug fix] Table: 修复排序错误，由于有 `props` 有默认值，导致undefined无法设置
* [bug fix] Grid: hover背景色由灰色改为蓝色&y轴滚动条设置为auto，高度不够时不显示滚动条
> [bug fix] Table: 排序错误，第二次没有取消

- packages/zent/assets/notify.scss
- add word-break style to notify-content container
> [bug fix] Notify：fix content overflow style;

- packages/zent/src/popover/Content.tsx
`scroll` events on elements don't bubble, but we can capture it.
> Use capture phase for scroll event on window

- packages/zent/package.json
- packages/zent/src/sortable/Sortable.tsx
- packages/zent/src/typings/sortablejs.ts
- packages/zent/src/upload/components/UploadPopup.tsx
- packages/zent/src/upload/utils/sortable.tsx
- yarn.lock
1.10.0 adds native es6 default export, this breaks old type definition.
A fork is created within this repository.
> Fix sortablejs typescript definition for 1.10.0

- packages/zent/src/alert/Alert.tsx
- 对 `.zent-alert-extra-content` div 添加了是否需要渲染的判断，防止不传 extraContent 时 Alert 内部右侧有多余 margin 存在的情况
> [bugfix]: Alert 组件不传 extraContent 参数时，不渲染外层包裹的 div

- packages/zent/assets/checkbox.scss
- packages/zent/assets/radio.scss
将单选(radio)和多选(checkbox)禁用选项文字色值由C8C9CC($theme-stroke-4)改成969799($theme-stroke-3)
> fix:修改了单选和多选的禁用选项文字颜色

- packages/zent/src/slider/Slider.tsx
- packages/zent/src/split-button/SplitButton.tsx
- packages/zent/src/tree/utils/createStateByProps.ts
- site/package.json
- site/webpack/webpack.config.js
- site/webpack/webpack.dev.config.js
- yarn.lock
- Tree: 移除plain模式对数据源的修改
- Slider: props.value 默认值设置为0
- SplitButton: contextType 添加 static 
- site/webpack: 增加 alias => 'react-dom': '@hot-loader/react-dom', 移除开发模式warnning
> [bug fix]Tree: 移除plain模式对数据源的修改 以及 其他组件微小调整

- packages/zent/__tests__/tabs.js
- packages/zent/assets/tabs.scss
- packages/zent/src/tabs/Tabs.tsx
- Tabs 组件匹配不到 types 时，展示默认的组件类型
- 删除 normal 类型下的 min-width 宽度限制
> [bug fix] Tabs: 添加类型不匹配时的默认展示行为

- packages/zent/src/tabs/README_en-US.md
- packages/zent/src/tabs/README_zh-CN.md
- packages/zent/src/tabs/Tabs.tsx
- packages/zent/src/tabs/VerticalTabs.tsx
- packages/zent/src/tabs/components/TabPanel.tsx
- packages/zent/src/tabs/components/base/BaseTabs.tsx
- packages/zent/src/tabs/types.ts
- packages/zent/src/tabs/utils.ts
- 修改 Panel 的默认渲染行为为使用 `display:none` 隐藏，而不是返回 `null`
- 添加 `unmountPanelOnHide` 和 `unmountOnHide` 参数，支持 Panel 的两种不同的渲染行为
> [bugfix] Tabs: 添加 Panel 的不同渲染行为模式

- packages/babel-plugin-zent/__tests__/index.js
- packages/babel-plugin-zent/src/index.js
Transforms
```js
import { NotFound, NotExists, Button, Icon }  from 'zent'
```
into 
```js
import { NotFound, NotExists } from 'zent';
import Button from 'zent/es/....';
import Icon from 'zent/es/....'; 
```
It throws when processing `NotFound` or `NotExists` before.
> Retain imports if not matched

- packages/zent/src/cascader/index.ts
暴露出 Cascader 内部的 interface，主要是 ICascaderItem，避免业务方在代码中重复定义。
> [new feature] Cascader: : export cascader interface

- packages/zent/assets/checkbox.scss
- packages/zent/assets/radio.scss
- packages/zent/src/radio/Radio.tsx
Remove extra space introduced by `inline-block`  in `Radio` and `Checkbox`.
> fix Radio and Checkbox height

- packages/zent/src/copy-button/index.tsx
- 修复 `CopyButton` 组件的 `text` prop 类型错误
> bugfix: 修复 CopyButton 的类型错误

- packages/zent/src/form/form-components/SelectField.tsx
- packages/zent/src/form/shared.tsx
[bug fix]: 修正IFormSelectFieldProps的类型错误
+ Omit在用于联合类型时会推断成never，因此把Omit放在IFormComponentProps内部，之后需要特别Omit时直接传入OmitKeys泛型参数即可。
> [bug fix] FormSelectField: 修复 IFormSelectFieldProps['name'] 类型推断

- packages/zent/src/datetimepicker/common/types.ts
`value` is accidentally changed to required in #1219
> datepicker value is optional

- packages/zent/src/grid/Row.tsx
The following code is not transformed by ts-plugin-version-attribute, so `data-zv` is missing.
```js
const Tr = props.something || 'tr';
return <Tr>...</Tr>
```
> fix missing data-zv in zent-grid-tr

- packages/zent/assets/checkbox.scss
- packages/zent/assets/radio.scss
- packages/zent/src/checkbox/Checkbox.tsx
- packages/zent/src/checkbox/README_en-US.md
- packages/zent/src/checkbox/README_zh-CN.md
- packages/zent/src/checkbox/demos/multi-line.md
- packages/zent/src/radio/README_en-US.md
- packages/zent/src/radio/README_zh-CN.md
- packages/zent/src/radio/Radio.tsx
- packages/zent/src/radio/demos/multi-line.md
- Revert `Radio` label display to `inline`
- Fix `font-size` in `RadioGroup` and `CheckboxGroup` children that is not a radio nor checkbox
- Add `labelStyle` to `Radio` and `Checkbox`
> Fix Radio and Checkbox style, add labelStyle prop

- packages/zent/src/sortable/Sortable.tsx
- `initSortable` 只在 `componentDidMount` 生命周期中执行一次，而不是挂载在 ref 上，以避免在每次重新渲染时重复执行 init
- 更新 Sortable 组件 props 类型
- `filterClass` 判断逻辑修改为 `classList.contains`，而不是直接判断 `className` 是否不等
> [Bugfix] Sortable: 修复组件的一些遗留bug

- packages/zent/src/form/Form.tsx
Form组件的IFormProps泛型不够完善导致传入Form.form()生成的builder时会报类型错误
> [bug fix] Form: 修复Form组件的form属性类型

- packages/zent/src/upload/ImageUpload.tsx
- packages/zent/src/upload/Upload.tsx
- packages/zent/src/upload/components/AbstractUpload.tsx
- packages/zent/src/upload/components/normal/Trigger.tsx
- packages/zent/src/upload/demos/manual.md
- packages/zent/src/upload/index.ts
- packages/zent/src/upload/types.ts
- 修改上传组件的文件数量计算规则，将上传失败的文件也统计到上传文件数量中
- 修改 `FILE_UPLOAD_STATUS` 常量的导出方式，将其设置为组件静态属性而不是顶部变量
- 更新 Demo 示例代码
> [bugfix] Upload: 修改文件数量计算规则

- packages/zent/src/form/shared.tsx
IFormComponentProps中的ModelDriven类型改defaultValue为可选属性
> [bug fix] Form: IFormComponentProps类型修复

- packages/zent/src/form/Field.tsx
只做编译时类型强转会导致潜在的bug，改成了String(xxx)
> [bug fix] Form: 默认加入的required校验函数required属性为boolean时改为空串message

- packages/zent/src/collapse/Panel.tsx
`Collapse.Panel`在配合`Collapse`使用时不需要传入`panelKey`、`onChange`
> [bug fix] Collapse: optional onChange and panelKey props

- packages/zent/__tests__/alert.js
- packages/zent/src/alert/ScrollAlert.tsx
- check the type of scroll-alert's children, so that ScrollAlert only render AlertItem.
- add tests about the type of ScrollAlert's children-node.
> fix: check the type of scroll-alert's children

- packages/zent/src/form/form-components/SelectField.tsx
1. 透传`props.children`给`Select`，与`CheckboxGroup`、`RadioGroup`保持统一
2. 访问`props.props.xxx`时使用`?.`
> [bug fix] FormSelectField: 透传children

- packages/zent/src/form/form-components/NumberInputField.tsx
- packages/zent/src/input/types.ts
- packages/zent/src/number-input/NumberInput.tsx
和`FormInputField`之前的问题一样，`Omit`里使用联合类型导致的问题
> [bug fix] NumberInput: 类型修复

- packages/zent/src/table/Table.tsx
- 修复 batchComponents 为空数组时页面渲染出一个 0
> [Table]: 修复 batchComponents 为空数组时页面渲染出一个 0

- packages/zent/src/clamp-lines/ClampLines.tsx
- packages/zent/src/clamp-lines/demos/non-cjk.md
ClampLines 内容中非CJK连续单词字符无法一行内展示时，允许词内折行
> [bug fix]: ClampLines 非CJK连续字符超长时允许词内折行

- packages/zent/src/form/demos/8.field-array.md
- packages/zent/src/form/formulr/models/ref.ts
增加`ModelRef.prototype.id`，在列表渲染时作为`key`使用，避免使用`index`
> [new feature] Form: ModelRef增加id属性

- packages/zent/src/form/Form.tsx
- packages/zent/src/utils/dom/getScollPosition.ts
1. `scrollToFirstError`需要滚动至视图内首个校验未通过的表单字段，以位置信息作为判断标准
2. `getScrollPosition`优化
> [bug fix] Form: 修复scrollToError无法滚动至首个错误字段的问题

- packages/zent/__tests__/color-picker.js
- packages/zent/assets/colorpicker.scss
- packages/zent/src/colorpicker/ColorBoard.tsx
- packages/zent/src/colorpicker/README_en-US.md
- packages/zent/src/colorpicker/README_zh-CN.md
- packages/zent/src/colorpicker/SketchFields.tsx
- packages/zent/src/colorpicker/SketchPresetColors.tsx
- packages/zent/src/colorpicker/common/EditableInput.tsx
- packages/zent/src/colorpicker/demos/disabled.md
- packages/zent/src/colorpicker/index.tsx
- packages/zent/src/disabled/demos/1.basic.md
Fixes #1445 
Changes
- ColorPicker支持禁用，属性disabled，以及Disabled组件
- ColorPicker删除prefix属性
- ColorPicker 组件样式更新
- 删除 `zent-colorpicker-board`, `zent-colorpicker-input` 以及 `zent-colorpicker-colors` CSS class
> [bug fix] ColorPicker支持禁用 && 删除prefix属性

- packages/zent/src/form/formulr/models/form.ts
#1470 改出了问题，修复一下，owner在构造函数中会被赋值，单单一个getter会报错
> [bug fix] Form: FormModel.prototype.owner改为只读属性而不是getter

- packages/zent/src/cascader/MenuCascader.tsx
- packages/zent/src/cascader/forest.ts
Decouple `disabled` logic from `getPaths`
> separate UI logic from data structures

- packages/zent/src/form/CombineErrors.tsx
- packages/zent/src/form/Field.tsx
- packages/zent/src/form/formulr/field-array.tsx
- packages/zent/src/form/formulr/field-set.tsx
- packages/zent/src/form/formulr/field.tsx
- packages/zent/src/form/formulr/value-listener.tsx
这是之前在formulr中还没完成的pr，formulr合入zent后遗漏了这个修复，顺便修复了一个类型问题，不影响运行时
解决的问题：
1. 恢复render阶段同步关联model的特性
2. 异步订阅通知，避免react 16.13的update in render的warning（之前的版本是通过异步关联model来避免的）
> [bug fix] Form: value-listener中的rxjs异步订阅通知

- packages/zent/src/input/TextArea.tsx
Fixes #1494 
update TextArea element manually to handle value prop change
> [bugfix] TextArea autosize when set input value asynchronously

- packages/zent/__tests__/clamp-lines.js
- packages/zent/src/clamp-lines/ClampLines.tsx
1. 首次渲染text属性为空时，后续text变更不会更新视图
```jsx
<Form form={form} layout="horizontal">
<FormInputField name="text"></FormInputField>
<Form.FieldValue name="text">
{text => {
return <ClampLines text={text || ''}></ClampLines>;
}}
</Form.FieldValue>
</Form>
```
2. 首次渲染text非空时，后续text为空会忽略下一次视图更新
```jsx
<Form form={form} layout="horizontal">
<FormInputField name="text" defaultValue="abc"></FormInputField>
<Form.FieldValue name="text">
{text => {
return <ClampLines text={text || ''}></ClampLines>;
}}
</Form.FieldValue>
</Form>
```
> [bug fix] ClampLines: 修复text属性为空串时的渲染问题

- packages/zent/package.json
- packages/zent/src/sortable/Sortable.tsx
- yarn.lock
- Upgrade `sortablejs` to `1.12.0`, `@types/sortablejs` to `1.10.6`
- Fix cannot move item to the first in the list
> upgrade sortablejs and fix insertion bug

- packages/zent/src/form/ZentForm.tsx
- packages/zent/src/form/form-components/DateRangeQuickPickerField.tsx
- packages/zent/src/form/form-components/RadioGroupField.tsx
- packages/zent/src/form/form-components/SwitchField.tsx
- packages/zent/src/form/formulr/builders/basic.ts
背景：内部使用BasicBuilder时给了any作为类型参数，导致build方法在类型推断时得出了Partial<any>这样的奇葩类型。
解决方案：BasicBuilder用unknown作为默认值类型，具体类型由子类实现，避免子类实现方法后不报错但又和父类类型不兼容的问题。
> [bug fix] Form: 修复BasicBuilder导致的类型错误

- packages/zent/src/copy-button/CopyToClipboard.ts
- packages/zent/src/copy-button/ReactCopyToClipboard.tsx
- packages/zent/src/utils/component/WindowEventHandler.tsx
1. Skip render in SSR mode
2. Add typings for `CopyToClipboard`
> SSR fix for window event handler

- packages/zent/src/grid/Grid.tsx
`React.ComponentType`默认props类型是`PropsWithChildren<{}>`，一旦自定义Row组件有其他属性就会报类型错误
> [bug fix] Grid: 修复自定义Row组件的属性类型

- packages/zent/src/select/Select.tsx
- fix Select focus move issue during loading
- allow moving to top after pressing down on the last option or pressing up on the first option
> fix Select focus move issue during loading

- packages/zent/src/breadcrumb/Item.tsx
- 用户自定义 `Breadcrumb.Item` 内容时，一般不会使用 `name` 属性，所以感觉把 `name` 属性改成**可选属性**更加合适
> fix(breadcrumb): optimize interface

- packages/zent/src/date-picker/CombinedDateRangePicker.tsx
- packages/zent/src/date-picker/DatePicker.tsx
- packages/zent/src/date-picker/DateRangePicker.tsx
- packages/zent/src/date-picker/context/PickerContext.ts
- packages/zent/src/date-picker/demos/disabled-time.md
- packages/zent/src/date-picker/hooks/useRangeDisabledDate.ts
- packages/zent/src/date-picker/panels/combined-date-range-panel/RangeFooter.tsx
- packages/zent/src/date-picker/panels/date-panel/DateFooter.tsx
- packages/zent/src/date-picker/utils/unifiedDisabledDateFromProps.ts
DatePicker:
- 🦀️   修复 `disabledDate` 传入 `min`、`max`含时间日期不生效问题
- 🦀️   修复 内部属性未透传导致的 disableTime 校验不及时
> [bugfix]: 修复DatePicker `disabled` 失效问题

- packages/zent/__tests__/date-picker/RangePicker.js
- packages/zent/__tests__/date-picker/SinglePicker.js
- packages/zent/src/date-picker/CombinedDateRangePicker.tsx
- packages/zent/src/date-picker/DateRangePicker.tsx
- packages/zent/src/date-picker/README_en-US.md
- packages/zent/src/date-picker/README_zh-CN.md
- packages/zent/src/date-picker/components/RangePickerBase.tsx
- packages/zent/src/date-picker/demos/disabled-time.md
- packages/zent/src/date-picker/hooks/useShowTimeOption.ts
- packages/zent/src/date-picker/panels/combined-date-range-panel/index.tsx
- packages/zent/src/date-picker/panels/date-panel/DateBody.tsx
- packages/zent/src/date-picker/panels/date-panel/DateFooter.tsx
- packages/zent/src/date-picker/types.ts
DatePicker:
- 日期组件showTime开启时，参数 `defaultTime` 类型扩展为 `string | (date: Date) => string`，支持根据当前日期自定义默认时间
> feature: 扩展日期组件showTime时的defaultTime类型

- packages/zent/assets/dialog.scss
- 修复 dialog 组件 overflow 为 auto 导致的滚动条恒显示i问题
> fix: 修改dialog overflow css问题

- packages/zent/src/date-range-quick-picker/DateRangeQuickPicker.tsx
- 🦀️  `DateRangeQuickPicker` 今天的结束时间统一为当前时间
> 快捷选择日期今日结束时间统一为当前时间

- packages/zent/assets/button.scss
- fix Button `bordered: false` not work when `disabled: true`
`.zent-btn-disabled[disabled]` is higher than `.zent-btn-border-transparent`
> fix: button bordered:false not work when disabled

- packages/zent/assets/form.scss
`.zent-form-control` 样式 `margin-bottom` 由于 `20px` 调整为 `24px`
> update form-control style(margin-bottom: 24)

- packages/zent/src/tree/Tree.tsx
- 在getDerivedStateFromProps时，针对expandAll变动，不在保留历史展开记录
Fixes #1634
> [bugfix]: Tree expandAll受控逻辑调整

- packages/zent/__tests__/date-picker/CombinedRangePicker.js
- packages/zent/__tests__/date-picker/RangePicker.js
- packages/zent/src/date-picker/CombinedDateRangePicker.tsx
- packages/zent/src/date-picker/README_en-US.md
- packages/zent/src/date-picker/README_zh-CN.md
- packages/zent/src/date-picker/components/CombinedPickerBase.tsx
- packages/zent/src/date-picker/components/RangePickerBase.tsx
- packages/zent/src/date-picker/demos/basic.md
- packages/zent/src/date-picker/demos/disabled.md
- packages/zent/src/date-picker/panels/date-panel/DateFooter.tsx
- packages/zent/src/date-picker/types.ts
`DateRangePicker`:
- Update disabled and canClear type definition in DateRangePicker
- Current time update to callback's time
> DateRangePicker 属性 `disabled`、`canClear` 类型更新为`boolean | boolean[]`

- packages/zent/src/form/Form.tsx
- Form render 时解构出 `willScrollToError`，原生 `form` 没有相关属性
> 修复 Form 组件 willScrollToError 属性 warn 提示

- packages/zent/src/grid/BatchComponents.tsx
- packages/zent/src/grid/Grid.tsx
- packages/zent/src/grid/README_en-US.md
- packages/zent/src/grid/README_zh-CN.md
- packages/zent/src/grid/SelectionCheckbox.tsx
- packages/zent/src/grid/SelectionRadio.tsx
- packages/zent/src/grid/demos/autoStick.md
- packages/zent/src/grid/demos/columnProvider.md
- packages/zent/src/grid/demos/disable-hover-highlight.md
- packages/zent/src/grid/demos/drop.md
- packages/zent/src/grid/demos/empty.md
- packages/zent/src/grid/demos/expand.md
- packages/zent/src/grid/demos/headerGroup.md
- packages/zent/src/grid/demos/scrollX.md
- packages/zent/src/grid/demos/scrollXY.md
- packages/zent/src/grid/demos/scrollY.md
- packages/zent/src/grid/demos/selection.md
- packages/zent/src/grid/demos/singleSelection.md
- packages/zent/src/grid/demos/sort.md
- packages/zent/src/grid/demos/span.md
- packages/zent/src/grid/types.ts
- packages/zent/src/grid/utils.ts
- Grid 添加 单选支持
- Grid `props.selection` 废弃 `getCheckboxProps` 对应调整为 `getSelectionProps`
Closes #1643
> Grid select support singleSelect

- packages/zent/assets/button.scss
- packages/zent/assets/checkbox.scss
- packages/zent/assets/input.scss
- packages/zent/assets/mixins/_index.scss
- packages/zent/assets/mixins/_pointer-events.scss
- packages/zent/assets/radio.scss
- packages/zent/src/button/Button.tsx
- packages/zent/src/button/Directive.tsx
- packages/zent/src/button/utils.tsx
- packages/zent/src/checkbox/Checkbox.tsx
- packages/zent/src/grid/SelectionCheckbox.tsx
- packages/zent/src/grid/SelectionRadio.tsx
- packages/zent/src/input/Input.tsx
- packages/zent/src/pop/Pop.tsx
- packages/zent/src/pop/README_en-US.md
- packages/zent/src/pop/README_zh-CN.md
- packages/zent/src/pop/demos/disabled.md
- packages/zent/src/popover/trigger/HoverTrigger.tsx
- packages/zent/src/radio/AbstractRadio.tsx
- packages/zent/src/radio/Radio.tsx
- packages/zent/src/radio/RadioButton.tsx
- packages/zent/src/tooltip/README_en-US.md
- packages/zent/src/tooltip/README_zh-CN.md
- packages/zent/src/tooltip/Tooltip.tsx
- packages/zent/src/tooltip/demos/disabled.md
- packages/zent/src/tooltip/demos/trigger.md
Workaround for #142 .
Popover / Pop / Tooltip
- Add `fixTooltipOnDisabledChildren` to fix the tooltip on disabled children when hover
> [Bugfix]: fix the tooltip on disabled children

- packages/zent/src/badge/Badge.tsx
- 独立徽标一般没有 `children` 属性，所以感觉把 `children` 属性改成**可选属性**更加合适
> fix(badge): optimize interface

- packages/zent/src/form/form-components/ImageUploadField.tsx
- packages/zent/src/form/form-components/InputField.tsx
- packages/zent/src/form/form-components/UploadField.tsx
- packages/zent/src/form/utils.ts
- 去除内置 Form Field 中 Upload 相关组件 prop 类型的非受控属性
- 对在 `Field.props` 中使用非受控属性的情况，添加告警提示
> [bugfix]: Form 部分 Field 类型修改，添加非受控属性告警

- packages/zent/src/select/demos/7.virtual-scroll.md
Fix a crash when filtered option list has [1, 8) items  in `Select` virtual scroll demo.
> fix select virtual scroll demo

- packages/zent/__tests__/ime-composition.js
- packages/zent/src/ime-composition/hooks.ts
`IMEComposition`:
- Fix input-elements inside `IMEComposition` event doesn't trigger in  some browser, like Safari.
> [bugfix]: Input inside IMEComposition onchange event doesn't trigger in some brower

- packages/zent/src/infinite-scroller/InfiniteScroller.tsx
- packages/zent/src/infinite-scroller/README_en-US.md
- packages/zent/src/infinite-scroller/README_zh-CN.md
Add `threshold` props to `InfiniteScroller`.
The `threshold` is the distance in pixels before the end of the items that will trigger a call to `loadMore`.
Closes #1704
> add threshold prop to InfiniteScroller

- packages/zent/src/form/FieldSet.tsx
- packages/zent/src/form/Form.tsx
- packages/zent/src/form/README_zh-CN.md
- packages/zent/src/form/demos/21.subscribe-model.md
- packages/zent/src/form/formulr/context.ts
- packages/zent/src/form/formulr/error.ts
- packages/zent/src/form/formulr/field-array.tsx
- packages/zent/src/form/formulr/field-set.tsx
- packages/zent/src/form/formulr/field.tsx
- packages/zent/src/form/formulr/listeners/array.ts
- packages/zent/src/form/formulr/listeners/field.tsx
- packages/zent/src/form/formulr/listeners/use-model.ts
- packages/zent/src/form/formulr/listeners/utils.ts
- packages/zent/src/form/formulr/models/is.ts
- packages/zent/src/form/formulr/utils.ts
1. Allow `Field` and `FieldArray` hooks to be used without form context if using `Model` as argument. `FieldSet` hooks always require a form context.
2. Allow referencing models using names  in `Model` mode, it was only possible in `View` mode.
3. Deprecate `useModelValue` and `useModelValid`, use `useFieldValue` and `useFieldValid` instead.
> loose context check in Form hooks

- packages/zent/src/tag/Tag.tsx
-  添加 Tag 组件对基本元素 div 上的原生属性的支持，以支持其他组件通过 cloneElement 方式注入的 props 属性。例如在  `Pop` 中使用的时候需要透传鼠标处理事件。
> feat: tag 组件支持传递 div 元素上的原生属性

- packages/zent/assets/date-picker.scss
- packages/zent/src/date-picker/components/TimePickerBase.tsx
- packages/zent/src/date-picker/context/PanelContext.ts
- packages/zent/src/date-picker/panels/date-panel/DateFooter.tsx
- packages/zent/src/date-picker/panels/time-panel/TimeFooter.tsx
`DatePicker`
- 修复组件面板底部的 '当前时间' 快捷按钮的禁用逻辑
> [bugfix]: 修复DatePicker组件中'当前时间'快捷按钮的禁用逻辑

- packages/zent/src/select/Select.tsx
fix: 当select初始化样式display为none，再显示时triggerWidth为0
> fix: 当select初始化样式display为none，再显示时triggerWidth为0

- .lintstagedrc
- packages/zent/__tests__/tree.spec.jsx
- packages/zent/assets/tree.scss
- packages/zent/src/preview-image/README_en-US.md
- packages/zent/src/preview-image/README_zh-CN.md
- packages/zent/src/tree/Tree.tsx
CSS class names affected:
```
switcher => zent-tree-switcher
content => zent-tree-content
opt => zent-tree-operation
operation => zent-tree-operation-container
off => zent-tree-bar--off
```
Fixes #1748
> prefix all css classnames in Tree

- packages/zent/package.json
- packages/zent/scripts/check-deadlink.js
- packages/zent/src/form/demos/13.interact.md
- packages/zent/src/infinite-scroller/InfiniteScroller.tsx
- packages/zent/src/infinite-scroller/README_en-US.md
- packages/zent/src/infinite-scroller/README_zh-CN.md
- packages/zent/src/waypoint/README_en-US.md
- packages/zent/src/waypoint/README_zh-CN.md
- packages/zent/src/waypoint/Waypoint.tsx
- Adjust `threshold` default value from 0 to 1 in InfiniteScroller. This should fix `loadMore` not triggered when page in zoomed in in most cases.
- Dead link checking now covers all markdown files in `packages/zent/src`
- Replace usage of `offsetWidth`/`offsetHeight` with `getBoundingClientRect` in `Waypoint` to avoid mixing rendered size and layout size. https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements
> fix InfiniteScroller loadMore not triggered when page is zoomed in

- packages/zent/src/form/Form.tsx
- 阻止 Form 组件的 submit reset keydown 事件继续向上冒泡，继而被外层 Form 捕获到。
> fix: 阻止 Form 的若干事件向上冒泡

- packages/zent/src/waypoint/README_en-US.md
- packages/zent/src/waypoint/README_zh-CN.md
- packages/zent/src/waypoint/Waypoint.tsx
- packages/zent/src/waypoint/cssom.ts
- packages/zent/src/waypoint/demos/01-basic.md
Fixes #1781 
Only supports CSS absolute length units, `em` and `rem` in `border-width`.
> add auto mode for topOffset and bottomOffset in Waypoint

- packages/zent/assets/theme/semantic/_color.scss
- packages/zent/src/button/README_en-US.md
- packages/zent/src/button/README_zh-CN.md
- packages/zent/src/pop/README_en-US.md
- packages/zent/src/pop/README_zh-CN.md
- packages/zent/src/pop/demos/custom-confirm.md
- packages/zent/src/split-button/README_en-US.md
- packages/zent/src/split-button/README_zh-CN.md
- packages/zent/src/split-button/demos/basic.md
- packages/zent/src/split-button/demos/dropdown-position.md
- packages/zent/src/split-button/demos/dropdown.md
- packages/zent/src/sweetalert/README_en-US.md
- packages/zent/src/sweetalert/README_zh-CN.md
- packages/zent/src/sweetalert/demos/button-type.md
- packages/zent/src/upload/demos/custom-item.md
1. 去除 Button 中 danger/success/waring 类型的文档显示，保留已使用的场景代码
2. 已使用的场景不区分hover/active的状态颜色变化，警示色不存在状态区分
Fixes #1787
> 移除按钮的danger/success/waring类型的hover/active状态

- .eslintrc.js
- packages/babel-plugin-zent/.babelrc
- packages/babel-plugin-zent/__tests__/index.spec.js
- packages/babel-plugin-zent/package.json
- packages/babel-plugin-zent/src/index.js
- yarn.lock
1. Bump required Node.js to 12
2. Better error message when processing `require('zent')`, and `console.error` instead of throwing an error
> warn instead of error on `require` in babel-plugin-zent

- packages/zent/src/date-picker/README_en-US.md
- packages/zent/src/date-picker/README_zh-CN.md
- packages/zent/src/date-picker/components/TimeRangePickerBase.tsx
- packages/zent/src/date-picker/panels/combined-date-range-panel/index.tsx
Fixes #1823 .
1. Keep startDate's time value when endDate updates in combined-date-picker
2. OnChange can be triggered only when the confirm button is clicked in time-range-picker
> keep startDate's time value when endDate updates in combined-date-picker(#1823)

- packages/zent/src/form/FieldSet.tsx
- packages/zent/src/form/formulr/builders/array.ts
- packages/zent/src/form/formulr/builders/basic.ts
- packages/zent/src/form/formulr/builders/field.ts
- packages/zent/src/form/formulr/builders/set.ts
- packages/zent/src/form/formulr/field-utils.ts
- packages/zent/src/form/formulr/models/array.ts
- packages/zent/src/form/formulr/models/field.ts
- packages/zent/src/form/formulr/models/set.ts
- packages/zent/src/form/formulr/utils.ts
- Add `destroyOnUnmount` and `normalizeBeforeSubmit` support to `FieldSet` and `FieldArray`
- Fix crash when using `destroyOnUnmount` on `FieldSet` and `value` is never read
> add destroyOnUnmount and normalizeBeforeSubmit support to FieldSet and FieldArray

- packages/zent/src/date-picker/panels/date-panel/DateFooter.tsx
- packages/zent/src/date-picker/types.ts
当日期选择器设置了showTimes属性选择具体时间时，通过onOpen和onClose修改timePicker的选择面板开启状态，当选择面板开启时，确认按钮置为disabled
> 日期选择器选择具体时间时，确认按钮置为disabled

- packages/zent/src/popover/withPopover.tsx
- 去除 withPop 生成的 HOC 组件的 props 类型中多余的字段
> fix: 修复 withPop HOC 的类型错误

- packages/zent/assets/theme/semantic/_color.scss
- packages/zent/assets/theme/semantic/_helper.scss
- packages/zent/plugins/postcss-plugin-theme-css-vars.js
1. 生成的theme-css-vars.json里weak-link匹配成了weak
2. 老版的$theme-stroke-x可以覆盖，加上!default
3.  内部无使用的get-rgb-css-var去除重复的rgb前缀
> fix: 修复css variable名字匹配问题,老版颜色可覆盖,删除无用前缀

- packages/zent/assets/tooltip.scss
- packages/zent/src/tooltip/README_en-US.md
- packages/zent/src/tooltip/README_zh-CN.md
- packages/zent/src/tooltip/Tooltip.tsx
- packages/zent/src/tooltip/demos/positions.md
- 🦀️   `tooltip`背景色与padding大小的修改，去掉阴影
- 📚  文档中删除LT、LB、RT、RB 四个方向。
> V10 tooltip

- packages/zent/src/form/Field.tsx
- packages/zent/src/form/README_zh-CN.md
- packages/zent/src/form/demos/11.normalizer.md
- packages/zent/src/form/shared.tsx
使用场景：
- 在输入框失焦时，删除头部和尾部的空字符
```
<FormInputField
name="field"
label="field"
normalizeBeforeBlur={value => value.trim()}
/>
```
> feat: 添加 normalizeBeforeBlur 属性，支持 onBlur 时修改值

- packages/zent/assets/sortable.scss
- 🦀️ `sortable`元素拖拽中占位覆盖元素`zIndex`层级设置
> fix: sortable 拖拽中占位覆盖元素 zIndex 层级设置

- packages/zent/assets/sortable.scss
- 🦀️ `Sortable`取消拖拽过程中拖拽元素`overflow:hidden`样式设置
> fix: [sortable]移除拖拽元素overflow:hidden设置

- packages/zent/assets/tabs.scss
- `Tabs`
- 🦀️ 多标签滚动模式下,隐藏项tab弹框宽度限制,超出显示省略号
> feat: [Tabs]多标签滚动模式下, 隐藏项 tab 弹框宽度限制, 超出显示省略号

- packages/zent/assets/breadcrumb.scss
- `Breadcrumb`
- 🦀 元素高度&行高样式调整
> feat: [Breadcrumb]元素高度&行高样式调整

- packages/zent/src/tree/README_en-US.md
- packages/zent/src/tree/README_zh-CN.md
- packages/zent/src/tree/Tree.tsx
- packages/zent/src/tree/demos/array-data.md
- packages/zent/src/tree/demos/async.md
- packages/zent/src/tree/demos/basic.md
- packages/zent/src/tree/demos/custom-node.md
- packages/zent/src/tree/demos/custom-operate.md
- packages/zent/src/tree/demos/disable-select.md
- packages/zent/src/tree/demos/one-line.md
- packages/zent/src/tree/demos/option.md
- packages/zent/src/tree/demos/size.md
- `tree`
- 🦀 `selectable`默认值修改为`true`
- 🦀 修复`small`、`large`尺寸下同层级节点位置未对齐的样式问题
- 📚 `selectable`相关文档、demo更新
> feat: [tree]selectable默认值修改为true

- packages/zent/src/sortable/Sortable.tsx
- `sortable`
- 🦀️ 修复拖拽后有时数据会变为`empty` 的问题
> fix: [sortable]修复拖拽后有时数据会变为 empty 的问题

- packages/zent/assets/button.scss
- packages/zent/src/button/demos/style.md
- `button`
- 🦀  `outline`模式下修复`hover`背景色为#fff
> fix(button): outline模式下修复hover背景色为#fff

- packages/zent/src/cascader/components/MenuContent.tsx
- `casacder`
- 🦀  修复级联选择器选中`option`文字没有加粗
> fix(casacder): 修复级联选择器选中option文字没有加粗

- packages/zent/src/form/demos/9.model-first.md
- `form`
- 📚  修复`vertical`变更导致的demo样式布局错位
> fix(form): 修复vertical变更导致的demo样式布局错位

- packages/zent/assets/alert.scss
- `alert`
- 🦀 Icon样式写法调整,与v9保证一致
> fix(alert): Icon样式写法调整,与v9保证一致

- packages/zent/RELEASE_zh-CN.md
- packages/zent/src/cascader/trigger/BaseTrigger.tsx
v9.12.8 
- Cascader
- ✨ 当配置了 `searchable` 时，也支持了placeholder
> feat(Cascader) ：当配置了 searchable 时，也支持了placeholder

- packages/zent/package.json
- yarn.lock
> hotfix(dep): 修复因 observable-hooks 自动升级 4.3.2 下的打包报错问题

- packages/zent/__tests__/dialog/Dialog.spec.jsx
- packages/zent/src/dialog/Dialog.tsx
- packages/zent/src/dialog/DialogEl.tsx
- packages/zent/src/dialog/README_en-US.md
- packages/zent/src/dialog/README_zh-CN.md
- packages/zent/src/dialog/position.ts
- [FIX]：修复弹窗自动打开与关闭位置不一致问题
- [FEATURE]：Dialog组件支持通过 `position ` 指定弹窗打开位置
- 默认 `auto` 自动选择打开位置
- 可选值 `center` 从屏幕中心打开
> feature(dialog)：add position prop support

- packages/zent/src/grid/Grid.tsx
- packages/zent/src/grid/README_en-US.md
- packages/zent/src/grid/README_zh-CN.md
- packages/zent/src/grid/SelectionCheckbox.tsx
- packages/zent/src/grid/demos/selection.md
- packages/zent/src/grid/types.ts
- Grid的getSelectionProps方法的返回值支持indeterminate配置（仅在多选模式下生效）
> Grid: getSelectionProps function support indeterminate return

- packages/zent/src/grid/Row.tsx
- change the key of cell in gird component with column name and index
> fix(grid): fix the key of cell in grid component to rerender correctly(zent10)

- packages/zent/assets/grid.scss
修复Grid的hover样式不生效的问题 
原 @include theme-color(background-color, default, bg); 生成的--theme-default-bg 变量未定义
> fix(Grid): fix hover color in grid row
